services/cd-service/Dockerfile, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go
The garbage collector runs at a certain rate and packs the loose git objects into git object packs.
=> Added Garbage collector

pkg/logger/http.go, services/cd-service/pkg/cmd/server.go
I was waiting for a log line to appear but apparently, I never correctly added the loggers to the http stack
=> Added missing logger to http endpoints

services/frontend-service/pkg/cmd/server.go, services/frontend-service/src/ui/Api.tsx
this is part one of [this PR](https://github.com/freiheit-com/kuberpult/pull/29)
=> Add Batch api logic to the frontend

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/testrepository/testrepository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go
Refactored a bit, so that the commit message of a transformer can be tested more easily
=> Improve errors/logs + tests

services/cd-service/pkg/repository/transformer.go
it will be re-used later by the "undeploy" version
=> refactoring: extract getLastRelease into function

.gitignore, docker/build/Dockerfile, go.mod, go.sum, services/cd-service/Dockerfile, services/cd-service/Makefile, services/cd-service/pkg/fs/fs.go, services/cd-service/pkg/fs/fs_test.go, services/cd-service/pkg/history/history.go, services/cd-service/pkg/history/history_test.go, services/cd-service/pkg/repository/certificates.go, services/cd-service/pkg/repository/certificates_test.go, services/cd-service/pkg/repository/credentials.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/service/overview.go, services/frontend-service/Dockerfile
upgrade alpine to alpine:3.15
upgrade git2go to v33 to support libgit2 v1.3.0 [link](https://github.com/libgit2/git2go#which-go-version-to-use)
=> upgrade libgit2 to v1.3.0

services/frontend-service/.eslintrc, services/frontend-service/src/ui/Batch.tsx, services/frontend-service/src/ui/ReleaseDialog.tsx, services/frontend-service/src/ui/Releases.test.tsx, services/frontend-service/src/ui/Releases.tsx, services/frontend-service/src/ui/Warnings.tsx
The warnings will show up if there is an "undeploy" version and if the versions are inconsistent (first undeploy, then normal version).
=> Added Undeploy Button and Warnings to the UI

services/frontend-service/src/ui/Releases.test.tsx
the releases test is breaking atm because the class names are diffferent. this is the fix
=> fix the unit test after changing the class names

.github/workflows/check-license-header.yml, .gitignore, Makefile, check.sh, services/frontend-service/src/ui/AppBar/styles.ts, services/frontend-service/src/ui/Batch.test.tsx, services/frontend-service/src/ui/Batch.tsx
Modify check script to return error when a file is changed
Add a github action for running the check on PRs
Ignore .envrc file which is used by direnv
=> Add a license check github action

charts/kuberpult/Chart.yaml, charts/kuberpult/values.yaml, charts/kuberpult/values.yaml.tpl
Someone changes the version number manually, this is just a fix for version number
=>  increase kuberpult memory

services/frontend-service/src/ui/Batch.test.tsx, services/frontend-service/src/ui/Batch.tsx, services/frontend-service/src/ui/ReleaseDialog.tsx, services/frontend-service/src/ui/Releases.test.tsx, services/frontend-service/src/ui/Releases.tsx, services/frontend-service/src/ui/Warnings.test.tsx, services/frontend-service/src/ui/Warnings.tsx
set the settings to `Hide whitespace` could make this review easier. 
the biggest refactoring is in `Batch.test.tsx`
=> SRX-2PM2DM - Refactoring and removing dialogs

services/frontend-service/src/ui/ActionsCart/ActionsCart.test.tsx, services/frontend-service/src/ui/ActionsCart/ActionsCart.tsx, services/frontend-service/src/ui/ActionsCart/CheckoutDialog.test.tsx, services/frontend-service/src/ui/ActionsCart/CheckoutDialog.tsx, services/frontend-service/src/ui/AppBar/Header.tsx, services/frontend-service/src/ui/ConfirmationDialog.test.tsx, services/frontend-service/src/ui/ConfirmationDialog.tsx, services/frontend-service/src/ui/ReleaseDialog.tsx, services/frontend-service/src/ui/Releases.tsx, services/frontend-service/src/ui/Warnings.tsx
there was some edits to `ActionsCart` and the file was moved to a new directory.
=> SRX-2PM2DM - Add a Checkout dialog

services/cd-service/pkg/cmd/server.go
=> cd-service: Fix import order

services/cd-service/pkg/cmd/server.go
=> cd-service: Fix golang struct tags

pkg/setup/setup.go
=> pkg/setup: Fix code format

services/cd-service/Makefile
Use make built-in functionality instead of calling into the shell.
=> services/cd-service/Makefile: Simplify

services/frontend-service/src/ui/ReleaseDialog.test.tsx, services/frontend-service/src/ui/ReleaseDialog.tsx
This PR fixes a compile error that was accidentally merged.
=> Fix for compile error in queue diff

.github/workflows/execution-plan.yml, infrastructure/scripts/execution-plan/plan-pr.sh, services/cd-service/Buildfile, services/cd-service/Makefile
- Update from init/build/publish steps to single parallel matrix build
- Add upload artifacts command for each build step
=> SRX-8BD1P4 Execution plan workflow with parallel matrix build and artifact uploads

infrastructure/scripts/execution-plan/container.inc.sh, infrastructure/scripts/execution-plan/container.sh, infrastructure/scripts/execution-plan/plan-main.sh, infrastructure/scripts/execution-plan/plan-pr.sh
optimization comments on previous pull request
=> Fix main branch build

services/frontend-service/src/setupTests.ts
Suggested-by: Viktor Luft <viktor.luft@freiheit.com>
=> Use new setupTests global.nextTick function by Viktor Luft

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/values.yaml.tpl
Story: SRX-4SBVE2
Story: https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-MuKyBzuXfRSQveZCHl1/
=> Make datadog environment configurable

CHANGELOG.md, services/cd-service/pkg/cmd/server.go, services/frontend-service/pkg/cmd/server.go
Story: SRX-4SBVE2
Story: https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-MuKyBzuXfRSQveZCHl1/
=> Support tracing of gRPC requests

CHANGELOG.md
Story: SRX-4SBVE2
Story: https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-MuKyBzuXfRSQveZCHl1/
Fixes: d2712227059974b875a290d3b236c52f0825c593
=> Changelog for d2712227059974b875a290d3b236c52f0825c593 / #197

.github/workflows/execution-plan-snippet.yml, services/cd-service/Buildfile
change job name to path/to/folder - Build and publish
sample: https://github.com/freiheit-com/kuberpult/runs/7000813016?check_suite_focus=true
story: [SRX-L4KWVE](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-N4S3jPrKFSL2qW0v8Yt/)
=> Clearer job names for matrix jobs

CHANGELOG.md, services/cd-service/pkg/argocd/render_test.go, services/cd-service/pkg/argocd/v1alpha1/types.go, services/cd-service/pkg/config/config.go, services/cd-service/pkg/repository/transformer_test.go
Signed-off-by: Eike Wichern <13048266+e96wic@users.noreply.github.com>
=> Added additional fields to argoCD ignore changes

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go, services/cd-service/pkg/repository/transformer.go
Some of the state parameters are not provided properly.
So full state is provided to transform function instead.
[SRX-NXORS9](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-N4m28IVhuVJW1-LvRHi/)
=> Change transform parameter from fs to full state

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/templates/frontend-service.yaml, charts/kuberpult/values.yaml.tpl, docker-compose.yml, pkg/api/api.proto, services/cd-service/Dockerfile, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/service/overview.go, services/cd-service/pkg/service/service.go, services/frontend-service/pkg/cmd/server.go, services/frontend-service/pkg/config/config.go, services/frontend-service/pkg/service/config.go
* clean up unused Argocd arguments
* add Argocd baseurl argument
* create getConfig rpc
=> SRX-GUPKQB - argocd baseurl argument

infrastructure/docker/backend/Dockerfile, infrastructure/docker/frontend/Dockerfile, infrastructure/docker/ui/Dockerfile
Buf caused an issue in Leandro machine ( Mac m1 chip ) when running docker images
=> fix buf installing in docker images

services/frontend-service/src/legacy-ui/App/AuthContext.test.tsx
https://github.com/freiheit-com/kuberpult/runs/7834909962?check_suite_focus=true#step:9:174
=> Add fix for document.cookie being null

pkg/auth/azure.go, pkg/auth/azure_test.go, services/frontend-service/pkg/cmd/server.go
react ui is still unable to load as static js files return 401.
only add auth for actual apis
=> Remove auth for /static folders as well

services/frontend-service/src/legacy-ui/ActionDetails.tsx, services/frontend-service/src/legacy-ui/ActionsCart/ActionsCart.tsx, services/frontend-service/src/legacy-ui/ActionsCart/CheckoutDialog.tsx, services/frontend-service/src/legacy-ui/AppBar/LocksDrawer.tsx, services/frontend-service/src/legacy-ui/ConfirmationDialog.tsx
=> Import icons directly instead of the entire icon pack

services/frontend-service/src/assets/_variables.scss, services/frontend-service/src/ui/NavigationBar/NavigationBar.scss, services/frontend-service/src/ui/components/navigation/navListItem.scss, services/frontend-service/src/ui/components/navigation/navListItem.tsx
* ![image](https://user-images.githubusercontent.com/88655074/186439915-3a50df09-56fb-4358-a1f4-d96c89322f83.png)
* https://github.com/freiheit-com/kuberpult/blob/3e475af187db15d0624c5918f72435ea5ffb636c/services/frontend-service/src/ui/NavigationBar/NavigationBar.scss#L19-L31
* https://github.com/freiheit-com/kuberpult/blob/3e475af187db15d0624c5918f72435ea5ffb636c/services/frontend-service/src/ui/components/navigation/navListItem.scss#L1-L14
=> Add round corners on indicator and fix css issues

services/frontend-service/src/ui/components/navigation/__snapshots__/navListItem.test.tsx.snap, services/frontend-service/src/ui/components/navigation/navList.scss, services/frontend-service/src/ui/components/navigation/navList.tsx, services/frontend-service/src/ui/components/navigation/navListItem.test.tsx
fix a bug with overflow scrollbar
=> Add tests for nav List Item

services/frontend-service/src/assets/_base.scss, services/frontend-service/src/assets/_components.scss, services/frontend-service/src/setupTests.ts, services/frontend-service/src/ui/App/index.tsx, services/frontend-service/src/ui/Pages/Home/Home.test.tsx, services/frontend-service/src/ui/Pages/Home/Home.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.scss, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx, services/frontend-service/src/ui/utils/store.tsx
* subscribing to the overview service at `index.tsx` is enough to track all changes and stream updates
* the first release cards belong to undeploy versions created locally.
=> Add service lanes and show the new kuberpult homepage

services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go
Old PR: https://github.com/freiheit-com/kuberpult/pull/367
=> SRX-AEY0CN Datadog Metrics

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
More margin to commit message, hash, author and release date Add Close button as a close icon
Add more radius to release dialog upper border
=> Fix Dialog header style

docker-compose.yml
Without this, the frontendservice cannot reach the backend service over http
=> Add missing url to docker-compose.yml

README_DEVELOPERS.md, infrastructure/scripts/create-testdata/Readme_testdata.md, infrastructure/scripts/create-testdata/create-release.sh, infrastructure/scripts/create-testdata/run-releasetrain.sh, infrastructure/scripts/create-testdata/testdata_template/environments/development/config.json, infrastructure/scripts/create-testdata/testdata_template/environments/fakeprod/config.json, infrastructure/scripts/create-testdata/testdata_template/environments/staging/config.json
This is useful to run kuberpult locally
=> Added scripts to create test data

services/frontend-service/src/legacy-ui/ReleaseDialog.tsx
Queues already have no effect anymore
=> Removed misleading tooltip about queues in old UI

pkg/setup/doc.go, pkg/setup/setup.go, pkg/setup/setup_test.go, services/cd-service/pkg/cmd/server.go, services/frontend-service/pkg/cmd/server.go
We have 3 types that have to do with "config", this PR renames one of them
=> refactoring: Rename config to ServerConfig

infrastructure/scripts/create-testdata/create-release.sh, infrastructure/scripts/create-testdata/testdata_template/environments/fakeprod-ca/config.json, infrastructure/scripts/create-testdata/testdata_template/environments/fakeprod-de/config.json, pkg/api/api.proto, services/cd-service/pkg/config/config.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go, services/cd-service/pkg/service/overview.go
And return it in GetDeployedOverview
=> Backend: Add environmentGroup to envConfig

Makefile.variables
This line hardcoded the registry, but we want to have it dynamic, as we push to 2 registries in the github action
=> Fix docker push to 2 registries

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.test.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.tsx, services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx, services/frontend-service/src/ui/utils/store.tsx
When adding anything to the cart: Open the cart
show number of actions in the top: "planned actions (42)"
=> Automatically open cart when actions are added

infrastructure/scripts/create-testdata/create-release.sh
Randomizes the authors and commit messages when creating a new release.
=> Create more readable test data

services/cd-service/pkg/repository/repository.go
ideally we should also warn in CreateEnvironment, but that requires a more involved approach, so this commit is only checking it on startup
=> Warn on startup if an upstream does not exist

pkg/api/api.proto, services/frontend-service/pnpm-lock.yaml, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx, services/frontend-service/src/ui/utils/store.tsx
field "environments" is deprecated.
=> refactoring: Use environmentGroup in servicelane

services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.test.tsx, services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
=> Allow deleting env locks from release dialog

services/frontend-service/src/ui/App/index.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.tsx, services/frontend-service/src/ui/utils/GrpcApi.tsx
Before azure authentication in the new UI only worked for the overviewservice, meaning one could see all the services, but not do anything with them.
Also removed some services that are not needed in the UI.
=> Fix: Azure Auth for batch service in new UI

services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx, services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/utils/store.tsx
refactored the "useRelease" functions
=> Refactoring: remove type assertion in store

services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
Before: 
https://github.com/freiheit-com/kuberpult/issues/602
After:
=> fix hidden releases tooltip undefined

services/frontend-service/src/assets/_variables.scss, services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx, services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.scss, services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.test.tsx, services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap, services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.test.tsx, services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx, services/frontend-service/src/ui/components/chip/chip.scss, services/frontend-service/src/ui/utils/store.tsx
=> Fix environment colors on Environments Page

services/frontend-service/src/ui/components/NavigationBar/NavigationBar.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx, services/frontend-service/src/ui/components/navigation/navListItem.tsx, services/frontend-service/src/ui/utils/store.test.tsx, services/frontend-service/src/ui/utils/store.tsx
closes https://github.com/freiheit-com/kuberpult/issues/620
* add a hook to navigate while keeping search params
hint: hide whitespaces
=> Fix Navigation to History page clears search filters

services/frontend-service/src/setupTests.ts, services/frontend-service/src/ui/components/FormattedDate/FormattedDate.test.tsx, services/frontend-service/src/ui/components/FormattedDate/FormattedDate.tsx, services/frontend-service/src/ui/components/LockDisplay/LockDisplay.test.tsx, services/frontend-service/src/ui/components/LockDisplay/LockDisplay.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx, services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.test.tsx, services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
* refactor a new component
* fix tests
* unify the usage of this Formatted Date component
* add tests
* more precision (minutes, hours, days... ago)
=> Improve Relative and formatted time calculation

pkg/api/api.proto, services/cd-service/pkg/service/overview.go, services/cd-service/pkg/service/overview_test.go, services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.test.tsx, services/frontend-service/src/ui/Pages/Home/Home.test.tsx, services/frontend-service/src/ui/Pages/Locks/LocksPage.test.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx, services/frontend-service/src/ui/components/Releases/Releases.test.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.test.tsx, services/frontend-service/src/ui/utils/store.tsx
Removed unused endpoints Get/StreamDeployedOverview and field "environments", because it has been replaced by "environmentGroups".
=> Removed unused Field "environments"

services/frontend-service/Makefile, services/frontend-service/pkg/config/config.go
This is relevant for the local setup.
When using the helm chart, the value is automatically set
=> Allow Origin * by default

services/cd-service/pkg/argocd/render.go, services/cd-service/pkg/argocd/render_test.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer_test.go
This always renders the finalizer and sets AllowEmpty to true.
This is a preparation for SRX-W559H7.
=> Allow easier app removal

pkg/api/api.proto, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go
Added a batch endpoint to remove one environment from an app in frontend and cd service.
SRX-W559H7
=> Delete Environment from App in backend

services/frontend-service/src/ui/App/index.test.tsx, services/frontend-service/src/ui/components/FormattedDate/FormattedDate.test.tsx, services/frontend-service/src/ui/components/LockDisplay/LockDisplay.test.tsx
This is a preparation for the jest upgrade https://github.com/freiheit-com/kuberpult/pull/616
=> Adapt jest.useFakeTimers for jest upgrade

renovate.json
Docs: https://docs.renovatebot.com/key-concepts/dashboard/
=> Add dashboard to renovate

services/rollout-service/pkg/service/broadcast.go, services/rollout-service/pkg/service/broadcast_test.go
The broadcast is responsible for propagating events from argocd to all subscribers.
=> Add broadcast implementation and tests

services/cd-service/pkg/repository/repository.go, services/frontend-service/pkg/cmd/server.go
Also added a new span to see the argoCd rendering in datadog.
=> Adding username/email as datadog tags to span

charts/kuberpult/templates/rollout-service.yaml
I forgot to add this secret in the previous step
=> Add missing argocd token secret

pkg/auth/rbac.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go, services/cd-service/pkg/service/batch_test.go
CheckPermissions function moved to Transformer.go and tests adapted
=> CheckPermissions function moved to transformer

services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx, services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
=> Improve azure error handling

pkg/auth/rbac.go, pkg/auth/rbac_test.go
Adds the Wildcard check for the environment, environment group and application.
=> Add Wildcard Check for Env/EnvGroup/Application

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go
Add RBAC to the DeleteEnvironmentApplicationLock action.
=> DeleteEnvironmentApplicationLock Role Based Access Control

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go, services/cd-service/pkg/service/batch_test.go
Implements RBAC on DeployApplicationVersion. Only activated if DEX is enabled.
=> DeployApplicationVersion Role based Access Control 

pkg/auth/rbac.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go
Implements RBAC on DeleteEnvironmentApplication. Only activated if DEX is enabled.
=> DeleteEnvironmentApplication Role Based Access Control

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go
Adds Role Based Access Control to CreateApplicationVersion.
=> CreateApplicationVersion Role Based Access Control

pkg/testutil/testutil.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go
Add RBAC to the CreateUndeployApplicationVersion action.
=> CreateUndeployApplicationVersion Role Based Access Control 

pkg/auth/rbac.go, pkg/auth/rbac_test.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go, services/cd-service/policy.csv
Adds Role Based Access Control to `UndeployApplication`.
=> UndeployApplication Role Based Access Control

charts/kuberpult/templates/frontend-service.yaml, charts/kuberpult/values.yaml.tpl, pkg/auth/rbac.go, pkg/auth/rbac_test.go, services/frontend-service/pkg/cmd/server.go, services/frontend-service/pkg/config/config.go
Registers Dex Handlers if enabled.
=> Create Dex API if enabled

services/frontend-service/src/ui/App/index.test.tsx, services/frontend-service/src/ui/App/index.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.scss, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx, services/frontend-service/src/ui/utils/GrpcApi.tsx, services/frontend-service/src/ui/utils/store.test.tsx, services/frontend-service/src/ui/utils/store.tsx
Add the rollout GRPC service to the frontend code
TODO(HVG): write tests
=> Add rollout service in grpc api

services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx, services/frontend-service/src/ui/Pages/Home/Home.tsx, services/frontend-service/src/ui/Pages/Locks/LocksPage.tsx, services/frontend-service/src/ui/Pages/Releases/ReleasesPage.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.tsx, services/frontend-service/src/ui/components/Spinner/Spinner.scss, services/frontend-service/src/ui/components/Spinner/Spinner.tsx, services/frontend-service/src/ui/components/Spinner/__snapshots__/Spinner.test.tsx.snap, services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
This adds a Spinner when submitting Actions:
=> Added spinner for submitting planned actions

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go
And changed commit message a tiny bit to make it more clear.
This was done to test the hot fix https://github.com/freiheit-com/kuberpult/pull/867/ more thoroughly.
=> Added tests for release train to env groups

pkg/auth/rbac.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch_test.go
=> Conditionally show team name in error message 

services/rollout-service/pkg/versions/versions.go, services/rollout-service/pkg/versions/versions_test.go
We need the environment group name for emitting the metrics with the correct key. The other method of the service could also supply this, but it's actually more complicated because `GetVersion` can access historic states and the environment group of an environment may have changed in the meantime. Therefore, I only added this data to the event, which is 100% sufficient for us now.
=> Add environment group name to kuberpult events

Makefile, Makefile.variables
We are using bash features in the shell script, so we cannot call it with sh
=> Fix shell invocation for license check

charts/kuberpult/templates/ingress.yaml
Adding ingressclass as an optional helm parameter
=> Add ingress class name as optional parameter

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
This fixes https://github.com/freiheit-com/kuberpult/issues/977
=> Fix: Show "deployed by" also for other versions in ReleaseDialog

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/templates/frontend-service.yaml, pkg/auth/rbac.go, services/cd-service/pkg/cmd/server.go, services/frontend-service/pkg/cmd/server.go, services/frontend-service/pkg/config/config.go
REV: [DSN-5XS7E0](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-NQPLdkfXUNc4bE9KOiO/STORY/-N_jS5MYUy6FO-8vUHd0/)
=> Change Dex and PgpKeyRing variable name

README_DEVELOPERS.md
=> Readme improvement evans

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go
This is a workaround for a BitBucket issue, where it does not display directories, if they have an empty directory in them.
With this change kuberpult deletes empty lock directories.
Note that it's rather unlikely to run into this issue locally or on another git hosting provider.
The git command line client handles empty directories transparently: They are deleted automatically if empty, and they are added automatically, if a file gets added. However, this is done in the git command line, but not in libgit2, which is more low-level and which is what we use in kuberpult.
=> Deleting empty directories in the manifest repository

renovate.json
See https://docs.renovatebot.com/configuration-options/#prconcurrentlimit
=> Increase renovates limit from 10 to 25

services/cd-service/pkg/argocd/reposerver/reposerver.go, services/cd-service/pkg/argocd/reposerver/reposerver_test.go
This feature is used when having  multiple root apps.
=> Implement include feature of repo server

charts/kuberpult/Chart.yaml.tpl, charts/kuberpult/run-kind.sh, charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/templates/frontend-service.yaml, charts/kuberpult/values.yaml.tpl
If Dex is enabled, installs the DEX helm chart together with Kuberpult.
REV: DSN-0Z3L73
=> Add DEX helm chart to Kuberpult helm chart 

pkg/api/api.proto, services/rollout-service/pkg/service/broadcast.go, services/rollout-service/pkg/service/broadcast_test.go, services/rollout-service/pkg/versions/versions.go, services/rollout-service/pkg/versions/versions_test.go
This is the backend part for my story regarding the rollout status by team. The code for the frontend service will be in a follow up commit.
=> Add filtering by team for the GetStatus endpoint

services/frontend-service/pkg/handler/handle_test.go, services/frontend-service/pkg/handler/rolloutstatus.go
Follow up of https://github.com/freiheit-com/kuberpult/pull/1112
=> Add filtering by team to the frontend-service

services/frontend-service/pkg/cmd/server.go, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.scss, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx, services/frontend-service/src/ui/utils/GrpcApi.tsx, services/frontend-service/src/ui/utils/store.tsx
Add dropdown to Product Version Page. Below is an image of the dropdown both before and after being selected
REV: DSN-UXZ54Z
=> Display tags in dropdown

pkg/setup/health_test.go
I forgot to add the tests that I wrote for the health checking
=> Add missing health tests

.github/workflows/integration-tests.yml, charts/kuberpult/run-kind.sh
- SRX-8HW1TP: always use the latest build from all services in i-test
- SRX-8HW1TP: simplify run-kind.sh by using just one image tag
- SRX-8HW1TP: simplify run-kind.sh by using just one image tag
- fix(run-kind): fix shellcheck warnings
=> fix(ci): build all services (SRX-8HW1TP)

pkg/api/api.proto, services/rollout-service/pkg/service/broadcast.go, services/rollout-service/pkg/service/broadcast_test.go
The frontend part will come in a second MR. The configurable limit will also be implemented there
=> Implement waiting in the rollout service

pkg/api/api.proto, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/service/tags.go, services/cd-service/pkg/service/tags_test.go, services/frontend-service/pkg/cmd/server.go
=> Add endpoint that returns the version of all services in an environment at a given commit

charts/kuberpult/templates/frontend-service.yaml, charts/kuberpult/values.yaml.tpl, services/frontend-service/pkg/config/config.go, services/frontend-service/pkg/handler/handle_test.go, services/frontend-service/pkg/handler/rolloutstatus.go
Followup to https://github.com/freiheit-com/kuberpult/pull/1143
=> Add waiting to frontend

services/frontend-service/pkg/cmd/server.go, services/frontend-service/pkg/cmd/server_test.go, services/frontend-service/public/index.html, tests/integration-tests/release_test.go
=> Force browsers to stop caching index.html

services/frontend-service/src/ui/App/PageRoutes.tsx, services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx, services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.test.tsx, services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.tsx, services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.test.tsx, services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.scss, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx, services/frontend-service/src/ui/components/ProductVersion/__snapshots__/ProductVersion.test.tsx.snap, services/frontend-service/src/ui/utils/Links.tsx, services/frontend-service/src/ui/utils/store.tsx
filtering done based on value in dropdown which is saved in SearchParams
=> Add env Dropdown to Product Version Page

pkg/api/api.proto, services/cd-service/pkg/service/version.go, services/cd-service/pkg/service/version_test.go
I noticed that I need this field as well.
=> feat: Add source commit id to new version protocol

services/rollout-service/pkg/versions/versions.go, services/rollout-service/pkg/versions/versions_test.go
The author is missing for this endpoint.
=> fix: add missing author for new version endpoint

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/values.yaml.tpl, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go
=> feat: report deployments to datadog

charts/kuberpult/templates/frontend-service.yaml, docker-compose-earthly.yml, docker-compose.tpl.yml, docker-compose.yml, services/frontend-service/Makefile
It has not been used in a while
=> fix: remove unused env var

services/rollout-service/pkg/argo/argo.go
When we are consuming argo events, we should retry the consuming.
=> fix: add health retry when consuming argo events

.github/workflows/release.yml
according to this documentation: https://github.com/docker/login-action?tab=readme-ov-file#github-container-registry
=> fix: login to ghcr in pipeline

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
=> fix: display locks on release dialog

pkg/api/v1/api.proto, services/cd-service/pkg/service/tags.go, services/cd-service/pkg/service/tags_test.go, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
- To be used on the front end in the next PR
REV: DSN-EDJDXS
=> feat: add team value to GetProductSummary endpoint's response

services/frontend-service/src/ui/components/TopAppBar/TopAppBar.scss, services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
=> fix: Remove material top bar

services/frontend-service/src/ui/components/navigation/navList.scss, services/frontend-service/src/ui/components/navigation/navList.tsx
=> fix: Remove MDCList dependency

services/frontend-service/src/ui/components/CommitInfo/CommitInfo.test.tsx, services/frontend-service/src/ui/components/CommitInfo/CommitInfo.tsx
=> feat: Display events of commits

services/frontend-service/src/ui/Pages/CommitInfo/CommitInfoPage.test.tsx, services/frontend-service/src/ui/Pages/CommitInfo/CommitInfoPage.tsx
=> fix: typo in commit info page

pkg/api/v1/api.proto, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/mapper/environments_config.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/service/batch.go, services/cd-service/pkg/service/environment.go, services/cd-service/pkg/service/environment_test.go, services/frontend-service/pkg/cmd/server.go, services/frontend-service/src/assets/_components.scss, services/frontend-service/src/assets/_variables.scss, services/frontend-service/src/ui/App/index.tsx, services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.test.tsx, services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx, services/frontend-service/src/ui/components/EnvironmentConfigDialog/EnvironmentConfigDialog.scss, services/frontend-service/src/ui/components/EnvironmentConfigDialog/EnvironmentConfigDialog.test.tsx, services/frontend-service/src/ui/components/EnvironmentConfigDialog/EnvironmentConfigDialog.tsx, services/frontend-service/src/ui/utils/GrpcApi.tsx, services/frontend-service/src/ui/utils/Links.tsx, services/frontend-service/src/ui/utils/store.tsx
=> feat: show environment config (SRX-QB4TU5)

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go
Reference: SRX-8X7UOZ
Reference: https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/FILESYSTEM/FOLDER/ROOT/STORY/-NcSCuNJwO8jjxtUwquk
=> fix: add tests for argocd webhooks

services/frontend-service/src/ui/components/ServiceLane/DotsMenu.test.tsx, services/frontend-service/src/ui/components/ServiceLane/DotsMenu.tsx, services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx
=> fix: dropdowns not closing when clicking outside

services/frontend-service/src/ui/components/ServiceLane/DotsMenu.test.tsx
=> chore: (dotsMenu) add tests for closing behavior

Earthfile, Makefile.variables, infrastructure/earthly/go/Earthfile, pkg/Earthfile, pkg/Makefile, services/cd-service/Earthfile, services/cd-service/Makefile, services/frontend-service/Makefile, services/rollout-service/Earthfile, services/rollout-service/Makefile, tests/integration-tests/Makefile
=> feat: supply args to 'go test' via GO_TEST_ARGS

charts/kuberpult/templates/frontend-service.yaml, docker-compose-earthly.yml, docker-compose.yml, pkg/api/v1/api.proto, services/frontend-service/pkg/cmd/server.go, services/frontend-service/pkg/config/config.go, services/frontend-service/pkg/service/config.go, services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx, services/frontend-service/src/ui/utils/Links.test.tsx, services/frontend-service/src/ui/utils/Links.tsx, services/frontend-service/src/ui/utils/store.tsx
=> fix: use namespace from config for argoCD links

services/frontend-service/src/ui/components/SideBar/SideBar.scss, services/frontend-service/src/ui/components/SideBar/SideBar.tsx, services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx, services/frontend-service/src/ui/components/textfield/textfield.scss, services/frontend-service/src/ui/components/textfield/textfield.tsx
Comparison:
* Before
* After
Rev: SRX-53N7TA
=> feat: remove MDCTextfield from lock message

charts/kuberpult/run-kind.sh, charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/values.yaml, go.mod, go.sum, services/cd-service/pkg/cmd/server.go
In order to use datadogs profiling, you need to set these variables in the helm chart:
```
datadogProfiling.enabled: true
datadogProfiling.apiKey: <get this from datadog>
```
=> feat: add helm option to enable datadog profiling

services/frontend-service/pkg/interceptors/interceptors.go
=> fix: request not aborted on invalid credentials

services/frontend-service/pkg/cmd/server.go
=> fix: check for GKEProjectNumber instead of service ID

charts/kuberpult/run-kind.sh
* solution is to overwrite the current main branch
Rev: SRX-0AE3N0
=> fix: run-kind.sh not starting if main branch exists

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/values.yaml, docker-compose-earthly.yml, services/cd-service/pkg/argocd/reposerver/reposerver_test.go, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch_test.go, services/cd-service/pkg/service/git_test.go
Kuberpults ArgoCD file generation can now be configured
=> feat: argo cd file generation on cd-service is now configurable

docs/remove-service.md
clarify when the "delete forever" button is visible
=> chore: Update remove-service.md

services/frontend-service/pkg/interceptors/interceptors.go, services/frontend-service/src/ui/Pages/CommitInfo/CommitInfoPage.tsx, services/frontend-service/src/ui/utils/AzureAuthProvider.tsx, services/frontend-service/src/ui/utils/store.tsx
the auth header was not passed in the new call GetCommitInfo, so the new commits page did not work on azure.
=> fix: azure login on commits page

services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx, services/frontend-service/src/ui/components/EnvironmentConfigDialog/EnvironmentConfigDialog.tsx, services/frontend-service/src/ui/components/EnvironmentLockDisplay/EnvironmentLockDisplay.tsx, services/frontend-service/src/ui/components/LockDisplay/LockDisplay.tsx, services/frontend-service/src/ui/components/LocksTable/LocksTable.tsx, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap, services/frontend-service/src/ui/components/ServiceLane/DotsMenu.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.tsx, services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx, services/frontend-service/src/ui/components/button/ExpandButton.tsx, services/frontend-service/src/ui/components/button/button.scss, services/frontend-service/src/ui/components/button/button.test.tsx, services/frontend-service/src/ui/components/button/button.tsx, services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx, services/frontend-service/src/ui/components/dropdown/checkbox.tsx, services/frontend-service/src/ui/components/dropdown/dropdown.tsx, services/frontend-service/src/ui/components/navigation/navListItem.tsx, services/frontend-service/src/ui/components/snackbar/snackbar.tsx
=> chore: remove mdc ripple

go.mod, go.sum, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/db.go, services/cd-service/pkg/repository/db_test.go
This separates the DBHandler form the DBConfig.
The DBConfig has data related to authentication, so we do not want to pass it around longer than necessary. Also added a Connect function that creates the DBHandler
Ref: SRX-T8YG6D
=> chore: refactor db connection setup

cd_database/migrations/Readme.md, docs/database.md
=> chore: add docs for db & migration

services/cd-service/pkg/repository/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go
=> chore: refactor transaction handling for DB

services/cd-service/pkg/repository/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go
plus some smaller changes like adding transactions to the custom migration
=> feat: update all apps table when removing an app

charts/kuberpult/tests/charts_test.go, charts/kuberpult/values.yaml
This fixes https://github.com/freiheit-com/kuberpult/issues/1571
=> fix: disable database by default

charts/kuberpult/templates/frontend-service.yaml, charts/kuberpult/values.yaml, pkg/auth/dex.go, pkg/auth/dex_test.go, services/frontend-service/pkg/cmd/server.go, services/frontend-service/pkg/config/config.go, services/frontend-service/pkg/interceptors/interceptors.go
closes https://github.com/freiheit-com/kuberpult/issues/1599
Recreation of https://github.com/freiheit-com/kuberpult/pull/1600
=> feat(dex): Add cluster-internal dex communication

charts/kuberpult/install-kuberpult-helm.sh, charts/kuberpult/run-kind.sh
run-kind takes some time to finish, so it is nice to be able to just re-run the last part of it, which is the interesting part about installing kuberpult in helm
=> chore: split up kuberpult installation from run-kind

Makefile.variables
This fixes the release pipeline which does not re-tag the new services.
=> fix(ci): Add new services to release pipeline

pkg/api/v1/api.proto, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/batch.go, services/frontend-service/pkg/handler/release.go
Removed next commit id from CreateReleaseRequest. There was no use case for it.
=> chore: removed next commit id from create release request

.github/workflows/commitlint.yml, .github/workflows/execution-plan-snippet-earthly.yml, .github/workflows/execution-plan-snippet.yml, .github/workflows/integration-tests.yml, .github/workflows/release.yml, .github/workflows/trivy-scan.yml
Also updates earthly to v0.8.13
=> fix(ci): Remove earthly runner from CI

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/tests/charts_test.go, charts/kuberpult/values.yaml
and fix the values.yaml linter violation
=> fix(db): correct name for env var

pkg/db/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/service/overview.go, services/cd-service/pkg/service/version.go
for example in the overview service
=> chore(db): use deploymentMetadata from Database

pkg/db/db.go, services/cd-service/pkg/repository/repository.go
And handle nil in GetDeploymentMetaData
=> fix(db): close rows

pkg/db/db.go, services/manifest-repo-export-service/pkg/cmd/server.go, services/manifest-repo-export-service/pkg/db/cutoff.go
and check for errors.
This also removes some unnecessary logging.
=> fix(db): close rows properly

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go
- Removing excess code for finding environment name
- Corrected issue that needed the environment and environment group to match
- Also fixed logging message for number apps deployed
=> fix(productVersion): correct environment for release train based on commit hash

services/cd-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go
Note that the change in the test is just a refactoring, it does not really reflect the change in the code.
The test can only be completed one `CreateEnvironment` is implemented.
=> fix(db): manifest-export: call deploy in CreateApplicationVersion

pkg/db/db.go
Better checking for migrations transformer
=> fix: migration transformer 

pkg/db/db.go, pkg/db/transactions.go, services/cd-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/db/cutoff.go, services/manifest-repo-export-service/pkg/repository/repository.go
and cleanup some unused fields
=> chore(db): add missing traces

services/manifest-repo-export-service/pkg/repository/transformer.go
There were some files that were not written to the manifest when creating a new application version
=> fix: missing release data from manifest

database/migrations/sqlite/1720105703004874_fk_deployments.up.sql, pkg/db/db.go, pkg/db/db_test.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go
Added transformer IDS to deployments, making it possible to optimize release trains on the export service side
=> feat: add transformer id deployments

pkg/db/transactions.go, services/cd-service/pkg/repository/repository.go
this is the maximum that postgres supports
=> chore(db): set isolation level to serializable

pkg/db/db.go, pkg/db/overview.go, pkg/db/overview_test.go
- Use protojson for marshaling api objects
- Fix Deploy time in overview cache
- ForceRecalculate should not write anything when overview cache is already empty
=> fix(db): Fix json marshaling and deploy time in overview cache

.github/workflows/check-license.yml, .github/workflows/commitlint.yml, .github/workflows/execution-plan-snippet-earthly.yml, .github/workflows/execution-plan-snippet.yml, .github/workflows/integration-tests.yml, .github/workflows/trivy-scan.yml, .github/workflows/trivy-secret-scan.yml
Upgraded:
* actions/upload-artifact to v4
* actions/checkout to v4
=> chore: Upgrade actions to v4

services/frontend-service/src/assets/_components.scss, services/frontend-service/src/ui/App/PageRoutes.tsx, services/frontend-service/src/ui/Pages/EslWarnings/EslWarningsPage.scss, services/frontend-service/src/ui/Pages/EslWarnings/EslWarningsPage.test.tsx, services/frontend-service/src/ui/Pages/EslWarnings/EslWarningsPage.tsx, services/frontend-service/src/ui/components/EslWarnings/EslWarnings.scss, services/frontend-service/src/ui/components/EslWarnings/EslWarnings.test.tsx, services/frontend-service/src/ui/components/EslWarnings/EslWarnings.tsx, services/frontend-service/src/ui/utils/GrpcApi.tsx, services/frontend-service/src/ui/utils/store.tsx
=> feat(ui): Visualize failed Esls in a new page

services/frontend-service/src/ui/Pages/EslWarnings/EslWarningsPage.tsx
=> fix(ui): add top app bar in failed esls page

services/manifest-repo-export-service/pkg/service/version.go, services/manifest-repo-export-service/pkg/service/version_test.go
=> chore(manifest-service): move GetManifests from cd-service to manifest-repo-export-service

services/manifest-repo-export-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go
=> chore: added lock tests for export service

charts/kuberpult/install-kuberpult-helm.sh, charts/kuberpult/templates/ingress.yaml
=> fix: do not use ssl mode when using run-kind.sh

charts/kuberpult/templates/ingress.yaml, charts/kuberpult/tests/charts_test.go
This is just the first commit, the next one will make it so you can enable individual paths.
Ref: SRX-XCZB2E
=> feat: split up ingress into separate paths

pkg/db/db.go, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/repository.go
Read and insert in-place for Deployments
=> feat: More efficient custom migrations

charts/kuberpult/install-kuberpult-helm.sh, cli/pkg/release/http.go, cli/pkg/release/parsing.go, cli/pkg/release/parsing_test.go, cli/pkg/release/release.go, docs/endpoint-release.md, go.mod, go.sum, infrastructure/scripts/create-testdata/create-release.sh, services/frontend-service/pkg/handler/handle.go, services/frontend-service/pkg/handler/handle_test.go, services/frontend-service/pkg/handler/release.go, tests/integration-tests/cluster-setup/argocd-kuberpult.sh, tests/integration-tests/release_test.go, tests/integration-tests/rollout_test.go
=> feat: Add /api/release endpoint

pkg/db/db.go, pkg/db/db_test.go, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/repository.go
Read and insert in-place for Commit-Events
=> feat: More efficient custom migrations for Commit-Events

pkg/db/db.go, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/repository.go
Read and insert in-place for Queued Application Versions
=> feat: More efficient custom migrations for Queued Application Versions

services/manifest-repo-export-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/repository/repository_test.go, services/manifest-repo-export-service/pkg/service/git.go
=> feat(manifest-service): add GetGitTags RPC to manifest-repo-export-service

charts/kuberpult/Earthfile, charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/templates/manifest-repo-export-service.yaml, charts/kuberpult/tests/charts_test.go
=> fix: Define database username/password in a secret

charts/kuberpult/templates/ingress.yaml, charts/kuberpult/tests/charts_test.go
This fixes https://github.com/freiheit-com/kuberpult/pull/1826
=> fix: paths for ingress

charts/kuberpult/templates/ingress.yaml, charts/kuberpult/tests/charts_test.go
=> fix: add callback to ingress for dex

services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
=> fix: Only show warnings in /home

services/frontend-service/pkg/handler/release.go
=> fix: Log deprecation warning for /release endpoint

charts/kuberpult/templates/ingress.yaml, charts/kuberpult/tests/charts_test.go
=> fix: add /token to ingress

.github/workflows/execution-plan-snippet-earthly.yml, .github/workflows/execution-plan-snippet.yml
=> chore(CI): Upgrade exec-plan github converter

.gitignore, pkg/db/db.go, pkg/db/db_test.go, pkg/event/event.go, services/cd-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/transformer.go
=> feat(manifest-service): list skipped services in release train commit message

services/frontend-service/src/ui/components/TopAppBar/TopAppBar.test.tsx, services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
* Display a welcome message for the logged-in user.
* If the cookie `kuberpult.oauth` is not set, nothing is displayed.
Ref: SRX-Y5QM5R
=> feat: Display logged-in user

services/frontend-service/src/ui/App/PageRoutes.tsx, services/frontend-service/src/ui/Pages/ReleaseHistory/ReleaseHistoryPage.test.tsx, services/frontend-service/src/ui/Pages/ReleaseHistory/ReleaseHistoryPage.tsx, services/frontend-service/src/ui/components/Releases/Releases.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
=> fix: Rename Releases page to Release History

cli/pkg/cli_utils/http.go, cli/pkg/cmd/cli.go, cli/pkg/cmd/handlers.go, cli/pkg/locks/env_lock_parsing.go, cli/pkg/locks/env_lock_parsing_test.go, cli/pkg/locks/lock.go, cli/pkg/release/http.go, cli/pkg/release/release.go
Added a command for creating environment locks to the CLI. Also moved http code to cli_utils package, as it is used by more than the release now.
Ref: SRX-QMIIYB
=> feat: cli create env locks

services/frontend-service/src/ui/components/ServiceLane/ServiceLane.scss, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
BEFORE:
https://github.com/user-attachments/assets/6edd63e2-6b7d-4b90-a309-5c129fdfefa5
AFTER:
https://github.com/user-attachments/assets/f3269baf-3efd-4e72-8594-0e72ece6b75c
Ref: SRX-RXAQ2D
=> feat(ui): Make commit bubble clickable

docs/minor-commits.md, pkg/db/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/manifest-repo-export-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go
=> feat(manifest-service): skip minor commits during cleanup

pkg/db/overview.go
=> fix(overview): init team locks map if not already

services/cd-service/pkg/repository/transformer.go
Fixes https://github.com/freiheit-com/kuberpult/issues/1895
Ref: SRX-ORIWUQ
=> fix: Check if WriteCommitData is enabled before writing skip causes

cli/pkg/cmd/cli.go, cli/pkg/cmd/handlers.go, cli/pkg/releasetrain/releasetrain.go, cli/pkg/releasetrain/releasetrain_parsing.go, cli/pkg/releasetrain/releasetrain_parsing_test.go
=> feat(cli): release train 

cli/README.md
=> chore(docs): user documentation for CLI

cli/DEVELOPERS_README.md, cli/README.md
=> chore(docs): CLI documentation for developers

services/frontend-service/pkg/cmd/server.go, services/frontend-service/pkg/handler/commit_deployments.go, services/frontend-service/pkg/handler/commit_deployments_test.go, services/frontend-service/pkg/handler/handle.go
=> feat: Implement /api/commit-deployments endpoint

cli/README.md, cli/pkg/cli_utils/file_operations.go, cli/pkg/cli_utils/file_operations_test.go, cli/pkg/cli_utils/http.go, cli/pkg/cmd/cli.go, cli/pkg/cmd/handlers.go, cli/pkg/deployments/deployments.go, cli/pkg/deployments/deployments_parsing.go, cli/pkg/deployments/deployments_parsing_test.go, cli/pkg/deployments/deployments_test.go
=> feat(cli): Support commit deployments in the CLI

services/frontend-service/src/ui/components/ServiceLane/ServiceLane.scss
=> fix: some more css tweaks for sidebar

services/cd-service/pkg/argocd/reposerver/reposerver.go
=> fix(cd-service): add ignorePrepublishes parameter to one of the db calls

charts/kuberpult/install-kuberpult-helm.sh, services/frontend-service/pkg/handler/grpc.go, tests/integration-tests/cluster-setup/argocd-kuberpult.sh, tests/integration-tests/commit_deployments_test.go
=> chore(ci): Add integration tests for commit deployments

pkg/db/db.go, services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): fix getting latest esl version in the create application version

pkg/db/db.go
=> fix(db): change span names

services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): check release not to be nil in the check minor flag function

services/frontend-service/src/assets/_base.scss
=> fix: tweak main content yet again

charts/kuberpult/values.yaml
=> fix(charts): fix charts annotations

pkg/db/transactions.go, services/cd-service/pkg/service/overview.go, tests/integration-tests/commit_deployments_test.go
=> fix: Use Repeatable Read isolation level for postgres transactions

services/cd-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/service/version.go
=> fix(db): make more transactions read-only

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap, services/frontend-service/src/ui/components/SideBar/SideBar.tsx, services/frontend-service/src/ui/utils/store.test.tsx, services/frontend-service/src/ui/utils/store.tsx
=> chore(ui): show release diff in planned actions and release dialog

services/frontend-service/src/setupTests.ts, services/frontend-service/src/ui/Pages/Home/Home.test.tsx, services/frontend-service/src/ui/Pages/Home/Home.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx, services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx, services/frontend-service/src/ui/components/dropdown/dropdown.scss, services/frontend-service/src/ui/components/dropdown/dropdown.test.tsx, services/frontend-service/src/ui/components/dropdown/dropdown.tsx, services/frontend-service/src/ui/utils/Links.tsx, services/frontend-service/src/ui/utils/store.tsx
=> feat(ui): add filters dropdown for filtering minor releases

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/templates/manifest-repo-export-service.yaml, charts/kuberpult/tests/charts_test.go, charts/kuberpult/values.yaml, docker-compose.yml, pkg/db/db.go, pkg/valid/validations.go, services/cd-service/pkg/cmd/server.go, services/cloudrun-service/pkg/cmd/server.go, services/manifest-repo-export-service/pkg/cmd/server.go
=> feat(db): Allow setting max connections

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
=> chore(ui): fix release dialog warning

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/templates/frontend-service.yaml, charts/kuberpult/templates/manifest-repo-export-service.yaml, charts/kuberpult/templates/rollout-service.yaml, charts/kuberpult/values.yaml
=> fix(helm): add datadog partial tracing

services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): skip cleanup during releasetrain

pkg/db/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go
=> fix(db): less calls to DBSelectAllReleasesOfApp

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/service/overview.go
=> fix(cd-service): optimize some queries in UpdateOverview in ReleaseTrain

pkg/db/db.go, services/cd-service/pkg/repository/transformer.go
=> fix(db): retrieve manifests before expensive step on prognosis

database/migrations/postgres/1727264269691278_environments_applications.up.sql, database/migrations/sqlite/1727264269691278_environments_applications.up.sql, pkg/db/db.go, pkg/db/db_test.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go, services/manifest-repo-export-service/pkg/service/git_test.go
=> fix(cd-service): add applications column to the environments table, fix DeleteEnvFromApp

pkg/db/db.go
We are creating a lot of spans, so this is an attempt to reduce the number of spans.
=> fix: Remove very small spans

pkg/db/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go
Ref: SRX-09Z4A6
* Update overview cache on create environment
* Update environment applications table in custom migrations
=> fix(cd-service): update environment applications in overview correctly

pkg/db/db.go, services/cd-service/pkg/cmd/server.go
=> fix(cd-service): make sure environment applications list gets updated during custom migrations

charts/kuberpult/templates/cd-service.yaml
=> fix: increase volume of emptyDir

pkg/db/transactions.go, pkg/db/transactions_test.go
=> fix(db): endless loop in UnwrapUntilPostgresError

services/cd-service/pkg/argocd/reposerver/reposerver.go
=> fix: Return an error if no commit was found

pkg/db/overview.go
=> fix: potential nil pointer when creating a new release

services/cd-service/pkg/repository/transformer.go
Do not update the overview for all apps on a release (of one app).
=> fix(db): Optimize release endpoint

pkg/db/db.go
=> fix(db): fix query for releases without environments to get only latest esl versions

pkg/db/db.go
=> fix(db): fix get manifests query

pkg/db/db.go
=> fix(db): do custom migrations for releases iteratively

charts/kuberpult/templates/cd-service.yaml
=> fix(charts): fix quotes for cache ttl

pkg/db/overview.go, pkg/db/overview_test.go
=> fix(db): fix update overview when app does not exist

services/frontend-service/pkg/service/batch.go
Added new logs to be checked on dev env with respect to context cancelation around the `processBatch` call.
Ref: SRX-BJVFRL
=> fix(frontend-service): New experimental logs added

services/cd-service/pkg/repository/transformer.go
This applies for undeploy versions.
Also fixes a potential nil pointer.
Ref: SRX-LEIHOZ
=> fix: skip event for releases with commit id

services/frontend-service/package.json, services/frontend-service/src/ui/App/index.tsx
=> fix(ci): Changed linting to strict and added corresponding test

.github/workflows/execution-plan-snippet-earthly.yml
=> fix(ci): fix gcloud error on execution plan

services/manifest-repo-export-service/pkg/repository/transformer.go
=> fix(manifest-repo-export-service): Changed json signature of transformer

services/cd-service/pkg/repository/transformer.go
=> fix: skip apps without releases in release train

Makefile, docker-compose.persist.yml
=> chore(docker): option to persist data on startup

services/frontend-service/pkg/service/batch.go
Final logs fix. Realized they were not clear at all to an outside reader.
Ref: SRX-BJVFRL
=> fix(frontend-service): Made the logs clearer

services/cd-service/pkg/repository/transformer.go
Added new Span "EnvReleaseTrain Transform" with tags "ConsideredApps" and "DeployedApps".
Existing Span "ReleaseTrain" got new tag "environments".
All of these tags are relevant for release train performance.
Ref: SRX-S6EKO3
=> feat(db): add more detailed information to release train spans

docker-compose.yml
Added environment variable needed to add ci links.
Ref: SRX-G46ZAL
=> chore(cli): Added KUBERPULT_ALLOWED_DOMAINS to docker-compose

cli/pkg/releasetrain/releasetrain.go, cli/pkg/releasetrain/releasetrain_parsing.go
=> fix(cli): option to run release trains on environment groups when dex  is enabled

pkg/db/overview.go
Overview was returning empty locks, so some 'ghost' locks appeared on the ui 
Ref: SRX-ZYK5HN
=> fix(UI): fix lock deletion bug

pkg/db/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/service/git.go, services/cd-service/pkg/service/git_test.go
=> feat(GetProductSummary): migrate getproductsummary endpoint to new Overview

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/service/overview.go
=> chore(tracing): added traces for getting and calculating overview

services/cd-service/pkg/service/overview.go, services/cd-service/pkg/service/overview_test.go
=> feat(performance): app details performance improvements

services/cd-service/pkg/service/version.go
=> fix: GetVersion failing when release was not found

services/frontend-service/src/ui/App/index.tsx, services/frontend-service/src/ui/Pages/Home/Home.test.tsx, services/frontend-service/src/ui/Pages/ReleaseHistory/ReleaseHistoryPage.test.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx, services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.test.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx, services/frontend-service/src/ui/components/ReleaseTrainPrognosis/ReleaseTrainPrognosis.test.tsx, services/frontend-service/src/ui/components/Releases/Releases.test.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.scss, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx, services/frontend-service/src/ui/utils/store.test.tsx, services/frontend-service/src/ui/utils/store.tsx
=> feat(UI): added time since last update for each app

services/frontend-service/src/ui/components/SideBar/SideBar.tsx, services/frontend-service/src/ui/utils/store.tsx
=> feat(UI): cache invalidation for special actions

pkg/db/db.go, pkg/db/db_test.go, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/repository.go
Ref: SRX-O2YISZ
* Retrieve list of environments' applications using releases table in custom migration
* Set applications list to empty list when creating new environment
* When Undeploying an application delete it from applications list in environments table
=> fix(cd-service): fix apps in envs

services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap, services/frontend-service/src/ui/components/button/ExpandButton.tsx, services/frontend-service/src/ui/components/button/button.scss
=> fix(ui): always enable 'lock only' button

services/cd-service/pkg/repository/transformer.go
=> fix: handle not found for all_app_locks table when deleting app lock

services/rollout-service/pkg/service/broadcast.go
This adds a trace for the code that runs when a client requests the StreamStatus.
Ref: SRX-8PS60H
=> fix: add trace for StreamStatus

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
Previously it repeated an app lock for multiple environments.
Ref: SRX-8PS60H
=> fix(ui): do not list app locks for each env

services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
=> fix(UI): apps that come into view through search bar now get loaded

services/cd-service/pkg/service/version.go, services/rollout-service/pkg/versions/versions.go
=> fix: add tags to GetVersion

pkg/db/db.go
=> fix(db): fix select app

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/repository/transformer_test.go
=> fix(cd-service): comment update dd metrics

services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): do not write empty overview after release train

services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): fix nil pointer when deleting a team lock

pkg/db/db.go, services/cd-service/pkg/repository/repository.go
This removes some boring spans,
and it fixes the parent of the "ApplyTransformers" span.
=> fix: improve datadog spans

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/service/overview_test.go, services/frontend-service/pkg/handler/environments.go
=> fix: create environment does not update complete overview

pkg/db/db_test.go
There were multiple complex queries without unit tests. This PR adds tests to 3 complex queries related to releases.
Ref: SRX-THO0EO
=> fix(db): test complex release queries

pkg/db/db_test.go
=> fix(tests): fix missing argument in db_test.go

pkg/db/overview_test.go
The new migration add an additional row to overviews
=> fix(db): fix delete old overviews

services/rollout-service/pkg/argo/argo.go
We currently have no visibility over the changed apps the rollout service receives from the cd-service. This PR adds a new datadog span that traces the processing of each changed app the rollout service receives from the cd service.
Ref: SRX-FEUSCN
=> fix(rollout-service): Add datadog span

database/migrations/postgres/1732637175997202_releases_autoincrement.up.sql, database/migrations/sqlite/1732637175997202_releases_autoincrement.up.sql, pkg/db/db.go, pkg/db/db_test.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go, services/manifest-repo-export-service/pkg/service/git_test.go, services/manifest-repo-export-service/pkg/service/version_test.go
=> chore(db): add auto-incremental version to releases table

charts/kuberpult/templates/rollout-service.yaml, charts/kuberpult/values.yaml, services/rollout-service/pkg/cmd/server.go, services/rollout-service/pkg/notifier/notifier.go, services/rollout-service/pkg/notifier/notifier_test.go
=> feat(rollout-service): add timeout parameter for notify argocd

services/cd-service/pkg/repository/transformer_db_test.go
=> fix(cd-service): fix flaky TestUpdateDatadogMetricsInternal

pkg/db/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): optimize delete environment locks

services/rollout-service/pkg/versions/versions.go
The version client was storing the versions seen in the previous call to `StreamChangedApps` endpoint. Then it would set the versions of this app to 0 and notify argo cd in case they did not come in the next `StreamChangedApps` call.
This incorrect behavior stayed from when we got the full overview instead of just the changed apps and could check every version every time.
This PR changes the logic so that the version client now stores every previously seen version and, if a deployment from a changed app is not sent or sent as nil, deletes missing deployments (set version to 0).
=> fix(rollout-service): fix 0 version

pkg/db/transactions.go
Some IDEs have an issue without the type annotation.
=> fix(db): fix comment and add type annotation

pkg/db/db.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): less calls to db select app in releasetrains

pkg/api/v1/api.proto, pkg/db/db.go, pkg/db/db_test.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/service/overview.go, services/cd-service/pkg/service/overview_test.go, services/frontend-service/pkg/cmd/server.go, services/rollout-service/pkg/versions/versions_test.go
Added new endpoint to get all application locks
Ref: SRX-JTRV7H
=> feat(overview): Implement new endpoint for getting all app locks

pkg/db/db.go
- Added extra parameter by mistake. This removes it
Ref: SRX-JTRV7H
=> fix: number of arguments for all apps query

database/migrations/postgres/1732637175997202_releases_autoincrement.up.sql, infrastructure/scripts/create-testdata/delete-environments.sh, pkg/api/v1/api.proto, pkg/auth/rbac.go, pkg/db/db.go, pkg/grpc/errors.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/service/batch.go, services/cd-service/pkg/service/overview.go, services/frontend-service/pkg/handler/environments.go, services/frontend-service/pkg/handler/handleEnvironments.go
=> feat: delete environments

services/cd-service/pkg/repository/repository.go
=> fix(cd-service): fix overview team locks

pkg/db/db.go
=> fix(db): fix a corner case for DBSelectAllActiveAppLocksForSliceApps

services/cd-service/pkg/repository/transformer.go
=> feat: allow group deployment of undeploy releases

README.md
=> feat: add hint in README on how to CLI debug unittests w/ earthly

charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/values.yaml, database/migrations/postgres/1736855898709581_migrationcutoff.up.sql, services/cd-service/pkg/cmd/server.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/service/migration.go
=> fix(cd-service): put a maximum on the number of threads for releasetrain

README.md, README_DEVELOPERS.md
=> fix(docs): move debugging info to developers readme

services/cd-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/migrations/types.go, services/manifest-repo-export-service/pkg/service/migration.go
=> fix: add more spans in manifest-export-service

charts/kuberpult/run-kind.sh
=> fix: run kind load in parallel

pkg/db/db_releases.go
=> fix(cd-service): DBSelectAllReleases should return releases sorted by releaseVersion

pkg/logger/logger.go
This enables correlation of logs and traces in datadog.
Note that both logs and traces must be enabled for this to work - in datadog and kuberpult.
The result would then look something like this:
Here the log "writing esl event" is correlated with the trace.
Ref: SRX-42QN2C
=> fix: enable log-trace correlation in datadog

services/frontend-service/pnpm-lock.yaml, services/frontend-service/src/ui/App/index.tsx, services/frontend-service/src/ui/Pages/Home/Home.test.tsx, services/frontend-service/src/ui/Pages/ReleaseHistory/ReleaseHistoryPage.test.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx, services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.test.tsx, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx, services/frontend-service/src/ui/components/ReleaseTrainPrognosis/ReleaseTrainPrognosis.test.tsx, services/frontend-service/src/ui/components/Releases/Releases.test.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.scss, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx, services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx, services/frontend-service/src/ui/utils/store.test.tsx, services/frontend-service/src/ui/utils/store.tsx
Added new states to service lanes. New colors for when app has not been requested, return an error or no info has been found 
New error state:
New Not requested:
New not found state:
Ref: SRX-92SG9X
=> feat: UI representation of other app details states

pkg/db/db.go, pkg/db/db_apps.go
=> fix(db): db select all apps should not return deleted apps

services/manifest-repo-export-service/pkg/cmd/server.go, services/manifest-repo-export-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go
Add transformer for deleting the environment folder from the manifest repo.
Ref: SRX-R3DKS5
=> feat(manifest-service): add DeleteEnvironment transformer

services/cd-service/pkg/repository/transformer.go
=> fix(db): less calls to DBSelectLatestDeployment

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
Deploying and canceling deployments for a group wasn't taking into account environments that should be skipped.
Ref: SRX-3I6YKY
=> fix: skipped envs with cancel deployments

services/rollout-service/pkg/argo/argo.go
=> fix(rollout-service): increase channel size for argo events

pkg/api/v1/api.proto, services/cd-service/pkg/service/overview.go, services/cd-service/pkg/service/overview_test.go, services/frontend-service/src/ui/components/Compliance/Compliance.test.tsx, services/frontend-service/src/ui/components/Compliance/Compliance.tsx
Filter the deployment history by an environment selected through a dropdown.
Ref: SRX-4MO8Z4
=> feat: filter deployment history by an environment

docker-compose.yml, services/frontend-service/pkg/config/config.go, services/frontend-service/src/ui/App/index.tsx, services/frontend-service/src/ui/utils/store.tsx
=> fix(frontend): fixing manifest export service connection

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
Fix cancel deploys for environment group not working.
Ref: SRX-JWS0HZ
=> fix(ui): cancel env group deploys

services/cd-service/pkg/repository/transformer_test.go
Ref: SRX-0KW8CJ
* Some of the tests need filesystem and have an equal in the transformer_db_test.go, they're removed.
* Some other tests could be adapted to use db
=> fix(cd-service): remove tests related to git 

services/frontend-service/src/assets/_components.scss, services/frontend-service/src/ui/components/Compliance/Compliance.test.tsx, services/frontend-service/src/ui/components/Compliance/Compliance.tsx, services/frontend-service/src/ui/components/ProgressBar/ProgressBar.scss, services/frontend-service/src/ui/components/ProgressBar/ProgressBar.test.tsx, services/frontend-service/src/ui/components/ProgressBar/ProgressBar.tsx
Show progress bar with the progress reported by the streaming endpoint for deployment history.
Ref: SRX-XURUQB
=> feat(ui): show deployment hist progress bar

services/frontend-service/src/ui/components/EslWarnings/EslWarnings.test.tsx, services/frontend-service/src/ui/components/EslWarnings/EslWarnings.tsx
=> feat(UI): skip events button

services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss, services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap, services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.test.tsx, services/frontend-service/src/ui/utils/Links.tsx, services/frontend-service/src/ui/utils/__snapshots__/Links.test.tsx.snap
=> feat(ui): argo icon with link to app and env

services/frontend-service/src/ui/components/SideBar/SideBar.test.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.tsx
Show which planned action failed and 
Ref: SRX-POX8R5
=> feat(ui): better failed action error reporting

pkg/api/v1/api.proto, services/cd-service/pkg/service/git.go, services/frontend-service/pnpm-lock.yaml, services/frontend-service/src/ui/components/GitSyncStatusDescription/GitSyncStatusDescription.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx, services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx, services/frontend-service/src/ui/utils/store.test.tsx, services/frontend-service/src/ui/utils/store.tsx, services/manifest-repo-export-service/pkg/service/git.go, services/manifest-repo-export-service/pkg/service/git_test.go
=> chore: return map instead of lists for GitSyncStatus

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/version.go
=> chore(cd-service): remove git related stuff from transformers

services/manifest-repo-export-service/pkg/cmd/server.go, services/manifest-repo-export-service/pkg/cmd/server_test.go
Add metrics for git sync status.
Ref: SRX-IOLM7K
=> feat(export-service): add git sync status metrics

.github/workflows/shellcheck.yml, charts/kuberpult/install-kuberpult-helm.sh, check.sh, deploy.sh, infrastructure/docker/builder/test_builder.sh, infrastructure/docker/git-ssh/start.sh, infrastructure/scripts/create-testdata/create-environments.sh, infrastructure/scripts/create-testdata/create-release.sh, infrastructure/scripts/create-testdata/stress_testing/create-releases.sh, infrastructure/scripts/execution-plan/container.inc.sh, infrastructure/scripts/execution-plan/plan-main.sh, infrastructure/scripts/execution-plan/plan-pr.sh, infrastructure/scripts/generate-changelog.sh, infrastructure/scripts/metadata-migration/create-metadata-locks.sh, infrastructure/scripts/metadata-migration/create-metadata-releases.sh, shellcheck.sh, tests/integration-tests/cluster-setup/argocd-kuberpult.sh, trivy/cache_db_image.sh
Adds a script for running shellcheck on every shell script and a ci workflow running that script.
Ref: SRX-0LZ0AV
=> chore(ci): add shellcheck workflow

services/frontend-service/src/ui/Pages/Home/Home.tsx
=> fix(UI): git sync status only appears when rollout is not enabled

services/manifest-repo-export-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/repository/repository_test.go, services/manifest-repo-export-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go
=> chore(manifest-export-service): Manifest Export Service no longer commits on NoOp transformers

services/manifest-repo-export-service/pkg/cmd/server.go
We now need to check if the commit ids differ when writing transaction timestamps so that we dont get database errors for primary key collisions
Ref: SRX-JYK0WX
=> fix(manifest-export-service): Only write transaction timestamps when new commit is generated

infrastructure/scripts/create-testdata/stress_testing/country_codes.csv, infrastructure/scripts/create-testdata/stress_testing/generate_environments.sh
=> chore: fix generate envs script for stress tests

database/migrations/postgres/1720014158596691_fk_commit_events.up.sql, database/migrations/postgres/1721380299181172_rename_eslid.up.sql, database/migrations/postgres/1741018309340699_delete_fk_constraint_commit_events.up.sql
=> fix(db): remove commit events foreign key

cli/pkg/cmd/cli.go, cli/pkg/cmd/handlers.go, cli/pkg/environments/delete.go, cli/pkg/environments/delete_test.go, cli/pkg/environments/parsing.go, cli/pkg/environments/parsing_test.go
Add command for deleting environments to the CLI
Ref: SRX-8XR09K
=> feat(cli): add delete environment command

charts/kuberpult/templates/manifest-repo-export-service.yaml, charts/kuberpult/tests/charts_test.go, charts/kuberpult/values.yaml
=> feat(charts): add option to disable export service

pkg/db/db_sync_status.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/service/git.go, services/manifest-repo-export-service/pkg/cmd/server.go, services/manifest-repo-export-service/pkg/cmd/server_test.go, services/manifest-repo-export-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/repository/repository_test.go, services/manifest-repo-export-service/pkg/repository/transformer.go, services/manifest-repo-export-service/pkg/service/git.go
=> chore(metrics): git sync status metrics are reported more often

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go
=> fix(cd-service): send git sync status metrics periodically

services/frontend-service/src/ui/App/index.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.test.tsx, services/frontend-service/src/ui/components/SideBar/SideBar.tsx, services/frontend-service/src/ui/utils/store.tsx
Brought back feature of showing off many versions we were rolling back or advancing on side bar deploy actions.
Ref: SRX-41ZF5J
=> fix(UI): rollback/advancing on side bar item

charts/kuberpult/templates/cd-service.yaml, pkg/db/db.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/service/batch.go
=> fix(cd-service): isolate some transformers

services/frontend-service/src/ui/components/button/button.scss
=> fix(UI): fixing visual bugs where buttons would appear on top of eachother

go.mod, go.sum, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/repository/transformer_test.go
=> fix(cd-service): remove commit message from outputs in cd-service

services/cd-service/pkg/argocd/reposerver/reposerver.go
=> fix(cd-service): reimplementing resolve revision so that manual sync is possible

services/cd-service/pkg/argocd/reposerver/reposerver.go
=> fix(cd-service): fixing resolve revision endpoint response

services/cd-service/pkg/argocd/reposerver/reposerver.go, services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx, services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
=> fix(UI): remove outdated description for manual deployment tooltip

services/frontend-service/src/ui/components/ReleaseTrainPrognosis/ReleaseTrainPrognosis.tsx, services/frontend-service/src/ui/utils/store.tsx
=> fix(ui): get commit id when not available in the prognosis page

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/manifest-repo-export-service/pkg/repository/transformer.go
=> fix(cd-service): fix release trains on upstream

services/rollout-service/pkg/service/service.go, services/rollout-service/pkg/service/service_test.go
=> chore(rollout-service): change discarded events from Gauge to Incr

services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go
=> fix(cd-service): fix applications list issue when updating an environment

services/frontend-service/src/ui/components/EnvironmentConfigDialog/EnvironmentConfigDialog.tsx, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx, services/frontend-service/src/ui/utils/store.tsx
=> fix(frontend): pass azure auth header to GetEnvironments and GetGitTags

infrastructure/earthly/go/Earthfile, services/cd-service/Earthfile, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/repository_test.go, services/manifest-repo-export-service/Earthfile, services/manifest-repo-export-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/repository/repository_test.go
=> fix(manfiest-service): fix benchmark test and add earthly task for it

services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): Write timestamp into env lock metadata

charts/kuberpult/templates/rollout-service.yaml, charts/kuberpult/values.yaml
=> fix(rollout-service): fix max age value in dora configs

charts/kuberpult/templates/ingress.yaml, charts/kuberpult/values.yaml
=> fix(charts): make timeout in ingress backendConfig configurable

trivy/.trivyignore, trivy/Earthfile
=> fix(trivy): temporary skip a CVE since it needs golang version update

services/cd-service/pkg/repository/transformer.go
=> fix(cd-service): less calls to GetApplicationTeamOwner in DeployApplicationVersion

docs/metrics.md
=> chore(documentation): complete metrics documentation

pkg/argocd/render.go, pkg/argocd/render_test.go, services/manifest-repo-export-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/repository/repository_test.go, services/manifest-repo-export-service/pkg/repository/transformer.go
=> feat(manifest-export-service): AA environments

Earthfile, Makefile, Makefile.variables, docker-compose.yml, services/reposerver-service/Buildfile.yaml, services/reposerver-service/Dockerfile, services/reposerver-service/Earthfile, services/reposerver-service/Makefile, services/reposerver-service/cmd/server/main.go, services/reposerver-service/pkg/cmd/server.go, services/reposerver-service/pkg/reposerver/reposerver.go, services/reposerver-service/pkg/reposerver/reposerver_test.go
=> feat: create reposerver microservice

charts/kuberpult/install-kuberpult-helm.sh, charts/kuberpult/run-kind.sh, charts/kuberpult/templates/cd-service.yaml, charts/kuberpult/templates/reposerver-service.yaml, charts/kuberpult/tests/charts_test.go, charts/kuberpult/values.yaml, docker-compose.yml, services/cd-service/pkg/cmd/server.go, services/reposerver-service/pkg/cmd/server.go
=> feat: add reposerver-service to helm chart

cli/Earthfile, cli/Makefile, infrastructure/earthly/go/Earthfile, services/manifest-repo-export-service/Makefile
=> chore: fix ci tasks for cli and export-service

charts/kuberpult/install-kuberpult-helm.sh, charts/kuberpult/values.yaml, services/rollout-service/pkg/cmd/server.go
=> chore(rollout): deprecate argo app filters

services/frontend-service/src/ui/components/SideBar/SideBar.scss
=> fix(ui): fix apply button position

database/migrations/postgres/1746623680709943_index_release_environments.up.sql, pkg/db/db.go, pkg/db/db_environments.go, pkg/db/db_test.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/service/git_test.go, services/cd-service/pkg/service/overview.go, services/manifest-repo-export-service/pkg/repository/repository.go
=> chore(db): do not use environment applications column anymore

services/frontend-service/pkg/handler/handle_test.go, services/frontend-service/pkg/handler/releasetrain.go, services/frontend-service/pkg/handler/requests.go
=> fix(frontend): cilink with azure signature for release trains

Earthfile, tests/integration-tests/validation-check.sh, tests/integration-tests/validation-check.sql
=> chore(db): add db validation checks script

infrastructure/earthly/go/Earthfile, pkg/db/db_testutil.go, services/cd-service/Earthfile, services/cd-service/pkg/repository/repository_test.go, services/manifest-repo-export-service/Earthfile, services/manifest-repo-export-service/pkg/repository/repository_test.go
=> chore: fix transformer benchmark tests

docs/what-is-deployed.md, pkg/api/v1/api.proto, services/cd-service/pkg/service/commit_deployment.go, services/cd-service/pkg/service/commit_deployment_test.go, services/frontend-service/pkg/handler/applications.go, services/frontend-service/pkg/handler/commit_deployments_test.go, services/frontend-service/pkg/handler/handleEnvironments.go, services/frontend-service/pkg/handler/handle_test.go
This api gets the environment name and application name and returns the commit information regarding the deployed version of that application on that environment.
Ref: SRX-EHKR00
=> feat(cd-service): add GetDeploymentCommitInfo api

.github/workflows/trivy-cache.yml, .github/workflows/trivy-secret-scan.yml
Fixed quoting issue in webhooks for kuberpult developers.
Ref: SRX-J9GR8V
=> fix: internal webhooks for ci

services/cd-service/pkg/service/git.go
=> fix: better error message for GetProductSummary

pkg/logger/logger.go, services/cd-service/pkg/cmd/server.go, services/frontend-service/pkg/cmd/server.go, services/rollout-service/pkg/cmd/server.go
This removes the dreaded log lines
"finished unary call with code..."
Ref: SRX-3U98Y2
=> fix: reduce logging

services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/service/environment.go
=> fix: do not load env configs per app

.github/workflows/execution-plan-snippet-earthly.yml
=> fix: remove unused cleanup step in CI

charts/kuberpult/templates/manifest-repo-export-service.yaml, charts/kuberpult/values.yaml, pkg/db/db.go, pkg/db/db_releases.go, services/manifest-repo-export-service/pkg/cmd/server.go, services/manifest-repo-export-service/pkg/repository/repository.go
=> fix(export-service): add git timestamp migration for releases

Makefile.variables, cli/Buildfile.yaml
=> chore: fix deps image variable

charts/kuberpult/templates/reposerver-service.yaml, charts/kuberpult/tests/charts_test.go, charts/kuberpult/values.yaml
=> feat: add replicas option for reposerver

services/cd-service/pkg/repository/repository.go
=> fix: remove unused function

.github/workflows/execution-plan-snippet.yml
=> fix: use correct converter image in CD

Makefile
=> fix: do not push datadog images

services/cd-service/Makefile
=> fix: add separate coverage checks for deployments & trains

Earthfile, infrastructure/docker/ui/Dockerfile
=> fix: Upgrade buf and helm

database/migrations/postgres/1751468673639069_revision.up.sql
=> chore(cd-service): DB Migrations for supporting revisions 

services/frontend-service/pkg/cmd/server.go
=> fix: improve logging when failing to get dex user

services/frontend-service/pkg/cmd/server.go
=> fix: return nil when there is no user

services/reposerver-service/pkg/reposerver/reposerver_test.go
=> fix: prepare for golangci-lint upgrade in reposerver

services/cd-service/pkg/repository/releasetrain.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/repository/transformer_test.go
=> fix: remove option to run trains sequentially

infrastructure/make/go/include.mk, services/cd-service/Dockerfile
=> fix(cd-service): Reduce cd-service docker image size

Makefile
=> fix: add make target to start db for unit-tests

.gitignore
=> fix: add coverage to gitignore

database/migrations/postgres/1751468673639069_revision.up.sql, pkg/db/db.go, pkg/db/db_deployments.go, pkg/db/db_releases.go, pkg/db/db_test.go, pkg/types/types.go, services/cd-service/pkg/repository/deployment.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/repository/transformer_db_test.go, services/cd-service/pkg/repository/transformer_deploy_test.go, services/cd-service/pkg/repository/transformer_test.go, services/cd-service/pkg/service/overview_test.go, services/manifest-repo-export-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/repository/repository_test.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go, services/manifest-repo-export-service/pkg/service/git_test.go, services/manifest-repo-export-service/pkg/service/version_test.go, services/reposerver-service/pkg/reposerver/reposerver_test.go, services/rollout-service/pkg/service/service_test.go, services/rollout-service/pkg/versions/versions_test.go
=> fix(cd): change revision from string to uint64

services/cd-service/pkg/service/commit_deployment.go, services/cd-service/pkg/service/commit_deployment_test.go
=> fix: refactor getCommitDeploymentInfo

services/cd-service/pkg/service/batch.go
=> fix: check teamname length on release creation

cli/pkg/release/http.go, cli/pkg/release/http_test.go, cli/pkg/release/parsing.go, cli/pkg/release/parsing_test.go, cli/pkg/release/release.go
=> feat(cli): Add revisions to release command

charts/kuberpult/templates/rollout-service.yaml, charts/kuberpult/values.yaml
=> feat: add k8s probes for rollout-service

pkg/auth/rbac.go, pkg/db/cutoff.go, pkg/db/db.go, pkg/db/db_app_locks.go, pkg/db/db_apps.go, pkg/db/db_argo_events.go, pkg/db/db_deployments.go, pkg/db/db_environments.go, pkg/db/db_releases.go, pkg/db/db_sync_status.go, pkg/db/db_team_locks.go, pkg/db/db_test.go, pkg/event/event.go, pkg/setup/health_test.go, services/cd-service/pkg/repository/transformer_db_test.go
=> fix: prepare pkg for linter upgrade

cli/pkg/cli_utils/file_operations.go, cli/pkg/cli_utils/http.go, cli/pkg/cmd/handlers.go, cli/pkg/locks/lock.go, cli/pkg/locks/lock_test.go, cli/pkg/release/http_test.go, cli/pkg/release/parsing_test.go, cli/pkg/releasetrain/releasetrain.go, cli/pkg/releasetrain/releasetrain_parsing_test.go, cli/pkg/releasetrain/releasetrain_test.go
=> fix: prepare cli for linter upgrade

pkg/db/db_releases.go, pkg/db/db_test.go, services/cd-service/pkg/repository/deployment.go, services/cd-service/pkg/repository/releasetrain.go, services/cd-service/pkg/service/release_train_prognosis.go
=> feat: batch commit id calls in release trains

.github/workflows/trivy-scan.yml
=> fix: trivy on main

infrastructure/scripts/execution-plan/create-matrix.sh
=> fix(CI): build the builder if proto changes

.golangci.yml, cli/Makefile, cli/pkg/cli_utils/http.go, infrastructure/docker/builder/Dockerfile, infrastructure/make/go/include.mk, pkg/Makefile, services/cd-service/pkg/repository/releasetrain.go, services/frontend-service/pkg/handler/handle.go
=> fix: upgrade golangci to 2.2.1

README_DEVELOPERS.md, services/frontend-service/src/ui/Pages/ReleaseTrain/ReleaseTrainPage.test.tsx, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.scss, services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx, services/frontend-service/src/ui/utils/store.tsx
This shows errors in their own box,
instead of just using snack-bar display,
which is always fleeting.
Ref: SRX-2Z82NU
=> fix(ui): visualize errors in product summary

pkg/db/db_releases.go
=> fix: label span correctly (DBSelectCommitIdAppReleaseVersions)

services/frontend-service/Dockerfile, tests/integration-tests/Dockerfile
=> fix(dockerfile): fix caching in docker

services/manifest-repo-export-service/pkg/repository/repository.go
=> fix(manifest-service): fix git timestamp use correct branch

database/migrations/postgres/1755007326623354_env_history_releases_json.up.sql, pkg/db/db_environments.go
=> fix(db): change releases_history to json

pkg/db/db_environments.go, pkg/db/db_test.go, services/cd-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/repository/repository.go
Previously we used 1 query per app.
Ref: SRX-GVSM9Y
=> fix(export): use only 1 query to get apps/teams

database/migrations/postgres/1755016745648909_deployment_history_index.up.sql, pkg/db/db_deployments.go, pkg/db/db_releases.go, pkg/db/db_test.go, services/cd-service/pkg/repository/transformer.go, services/cd-service/pkg/service/overview_test.go, services/manifest-repo-export-service/pkg/db_history/db_history.go, services/manifest-repo-export-service/pkg/db_history/db_history_test.go, services/manifest-repo-export-service/pkg/repository/repository.go, services/manifest-repo-export-service/pkg/repository/transformer_test.go, services/manifest-repo-export-service/pkg/service/git_test.go, services/manifest-repo-export-service/pkg/service/version_test.go, services/reposerver-service/pkg/reposerver/reposerver_test.go
=> fix(db): optimize query to get all deployments

pkg/db/db_deployments.go, services/cd-service/pkg/repository/transformer_db_test.go
=> fix: use right table to find latest deployment attempt

Makefile, pkg/db/db_deployments.go, pkg/db/db_testutil.go, services/cd-service/pkg/repository/repository.go, services/cd-service/pkg/repository/transformer_db_test.go, services/frontend-service/Makefile, services/frontend-service/pnpm-lock.yaml, tests/integration-tests/cluster-setup/argocd-kuberpult.sh
- ... so move it to testutil
- remove unused GetQueuedVersionFromDB
- test ...OnAllEnvs and ...OfAllApps too
Ref: SRX-UGIFDH
=> fix: DBSelectLatestDeploymentAttempt is only used in tests

charts/kuberpult/templates/ingress.yaml, charts/kuberpult/values.yaml
=> fix(helm): add virtualservice to helm chart options

services/cd-service/pkg/repository/transformer.go
=> fix: allow direct deployment of non-latest

services/frontend-service/src/ui/Pages/CommitInfo/CommitInfoPage.scss, services/frontend-service/src/ui/components/CommitInfo/CommitInfo.scss
=> fix(ui): fix text color in commit history page for dark mode

pkg/db/db_releases.go
=> chore(releases): do not update release creation time with updates

charts/kuberpult/values.yaml
=> fix(docs): recommend manifest-export
