- docker/build/Dockerfile
- services/cd-service/Dockerfile
- services/frontend-service/Dockerfile
Using a mix of edge + latest causes a desync of some shared libraries
> Use fixed alpine base images instead of edge/latest

- chart/values.yaml.tpl
- docker/build/Dockerfile
- services/cd-service/Dockerfile
- services/cd-service/Makefile
- services/frontend-service/Dockerfile
- services/frontend-service/Makefile
Ghcr has only one level of naming hierachy so we cannot have `ghcr.io/freiheit-com/kuberpult/xyz` but we need to use `ghcr.io/freiheit-com/kuberpult-xyz`.
> Fix ghcr container names

- services/cd-service/pkg/cmd/server.go
While testing the GitGC, I noticed that it was not enabled by default. This enables it by default with a frequency of 1/20 commands.
> Fix: Git GC was not enabled

- pkg/api/api.proto
- services/cd-service/pkg/argocd/render.go
- services/cd-service/pkg/argocd/render_test.go
- services/cd-service/pkg/argocd/v1alpha1/types.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/service_test.go
This endpoint creates a new version that we call "undeploy":
* Creating the undeploy version is similar to createApplicationVersion: it also deploys to envs, if the config is set to upstream.
* The undeploy version works like any other version, except it deploys nothing ("the empty set").
* Trying to deploy the undeploy version if it is already deployed, is essentially a no-op, but is allowed
* This change only touches the backend, so there is no button in the UI to create the undeploy version yet.
The goal is to have a process of undeployment (e.g. removing a microservice), similar to how new services are added: first on one environment, then the next, etc.
> added "undeploy" endpoint

- services/cd-service/pkg/history/history.go
- services/cd-service/pkg/history/history_test.go
The new algorithm calculates much bigger parts of the tree up-front.
```
/build/services/cd-service $ go test -bench . -benchmem -benchtime 1m ./pkg/history/...
goos: linux
goarch: amd64
pkg: github.com/freiheit-com/kuberpult/services/cd-service/pkg/history
cpu: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
BenchmarkHistoryNew-8                244         302610217 ns/op        44486087 B/op    2501890 allocs/op
BenchmarkHistoryOld-8                 22        2963958233 ns/op        253691023 B/op  17944738 allocs/op
PASS
ok      github.com/freiheit-com/kuberpult/services/cd-service/pkg/history       228.461s
```
> Reimplement History.Change in a much faster way

- Makefile
- pkg/Makefile
this will be used to run the test files in the pkg directory. including `setup_test.go` which is not running atm.
> Add Makefile in pkg directory and add it to make directories

- pkg/api/api.proto
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
Added un-deploy endpoint to completely remove a service.
There are two checks before un-deploy an application:
1) check locks ( ignore env locks )
2) check that all releases are un-deployed
>  undeploy endpoint with tests SRX-M5GOA4

- go.sum
`pkg/api` needs `protoc-gen-grpc-gateway`.  Otherwise it complains about:
```
$ make -C pkg/api 
buf generate
Failure: plugin grpc-gateway: could not find protoc plugin for name grpc-gateway
make: *** [Makefile:19: api_grpc.pb.go] Error 1
```
Quick research shows that the `grpc-gateway` plugin for `protoc` is
`github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway`.
Installing the same then complains about:
```
$ go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
[...]
../../../../../go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.4.0/internal/descriptor/grpc_api_configuration.go:8:2: missing go.sum entry for module providing package github.com/ghodss/yaml (imported by github.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor); to add:
go …
```
> Fix missing entry for github.com/ghodss/yaml in go.sum

- charts/kuberpult/Makefile
Their documentation recommends to use the container image, which has all
necessary tools installed [^1] and simplifies running the tool greatly.
[^1]: https://github.com/helm/chart-testing#installation
> make: Run `ct` in container

- go.mod
- go.sum
- services/cd-service/pkg/history/history.go
- services/cd-service/pkg/history/history_test.go
- services/cd-service/pkg/repository/repository.go
The history algorithm currently recalculates the whole history for the repository on every run. However, most of the things in a repo do not change on each commit. I introduced a cache that memorizes the last ten calculation results so that we can reuse them later. This bring the history calculation in most cases down from O(N) to O(1) for N = number of commits in repo.
Benchmark:
```
/build/services/cd-service/pkg/history $ go test -benchmem -bench=.
goos: linux
goarch: amd64
pkg: github.com/freiheit-com/kuberpult/services/cd-service/pkg/history
cpu: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
BenchmarkHistoryNoCache-12             4         289058522 ns/op        36413094 B/op    2330716 allocs/op
BenchmarkHistoryCache-12             465           2560525 ns/op          596726 B/op …
```
> Optimize history calculation to reuse previously computed results

- infrastructure/docker/backend/Dockerfile
- infrastructure/docker/frontend/Dockerfile
- infrastructure/docker/install-dependencies/Dockerfile
- infrastructure/docker/ui/Dockerfile
When we download something from the net (instead of installing it via our
Linux distribution, whose tools already include checksum verification), we
need to check that the file is what we expect it to be, so that no one can
smuggle malware into our images.
> infrastructure/docker: Update buf from 1.0.0 to 1.4.0 and ensure we do not run malware

- infrastructure/docker/backend/Dockerfile
When running docker-compose up, cd-service errors out during make with gcc - command not found.
Adding gcc dependancy into cd-service Dockerfile
> Add build-base into cd-service dockerfile

- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
When kuberpult is running and an invalid config.json file is pushed and /release is run. If a valid config.json file is then pushed and /release is called, it should not throw an error stating config file is invalid
> SRX-VM44MY reload config file when changed in repository

- services/cd-service/Dockerfile
When make run is run from within cd-service, it tries to run make from within the docker container, but fails with error gcc not found. Once pull request is merged, ghcr.io/freiheit-com/kuberpult/build:latest would need to be rebuilt
exec docker run -it --tmpfs /.cache:rw,noexec,nosuid --mount type=bind,source=/Users/nisham/go,target=/go --mount type=bind,source=/Users/nisham/workspace/kuberpult/test,target=/etc/ssh --mount type=bind, source=/Users/nisham/workspace/kuberpult,target=/build -w /build --rm -u 501 --security-opt=seccomp=default.json -e WITHOUT_DOCKER=true ghcr.io/freiheit-com/kuberpult/build:latest make -C services/cd-service bin/main
Add build-base which contains gcc to avoid the error.
> Add build-base to avoid error gcc not found, when running make run

- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/overview_test.go
- services/cd-service/pkg/service/service.go
- services/cd-service/pkg/service/service_test.go
This change allows a new parameter for the deploy endpoint `version` to make the endpoint (nearly) idempotent. The parameter is optional. If it's omitted, kuberpult will use the existing behaviour and use the latest release+1.
This also slightly changes the http status code. Until now, the status code 204 ("No Content") is used to indicate success. However, we have now two different success outcomes. To reflect this, kuberpult will respond with 201 ("Created") when a new release was created and 200 ("Okay") when the release already exists.
> SRX-4JC9OG allow setting the release number when creating new commits

- services/frontend-service/src/ui/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/ReleaseDialog.tsx
The version and queue diff algorithm assumed that version numbers are
always consecutive. That was actually never guaranteed but never
happened in practise. However, with the latest changes, this may happen
basically all the time.
> SRX-4JC9OG Calculate the VersionDiff correctly when versions are missing

- services/frontend-service/pkg/cmd/server.go
`http.ServerMux` only supports prefix matches when the path ends with a slash.
> Fix /environments/ endpoint

- go.mod
- go.sum
- services/cd-service/pkg/argocd/render.go
- services/cd-service/pkg/argocd/render_test.go
- services/cd-service/pkg/argocd/v1alpha1/types.go
- services/cd-service/pkg/config/config.go
This will allow us to add SyncOptions like [these](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#selective-sync) to the ArgoCD application resources
> Add SyncOptions to rendered ArgoCD application manifests

- .github/workflows/execution-plan-main.yml
- .github/workflows/execution-plan-pr.yml
- .github/workflows/execution-plan-snippet.yml
- infrastructure/scripts/execution-plan/plan-main.sh
Refactor execution plan workflow, to be called from both pull request and main workflow, such that inputs can be provided for the minor changes required between them.
Use git-versioning to get the version number so as to avoid conflicts
On main branch, since release is common and not independant for all services, all buildfiles are passed to execution plan, in effect building everything
> SRX-5VUIF9 Refactor execution plan workflow to be used with parameters

- services/frontend-service/src/ui/ConfirmationDialog.test.tsx
- services/frontend-service/src/ui/ConfirmationDialog.tsx
- services/frontend-service/src/ui/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/ReleaseDialog.tsx
When application is manually deployed to production, check that all its upstream environments are already updated, if not give warning. 
story: [SRX-5VUIF9](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-N3YKNILyrB8A0ik5B41/)
> Warn when manually deployed to production

- services/frontend-service/src/ui/ConfirmationDialog.tsx
Before, if the sync window warning would have been the only warning,
the confirmation dialog would not show.  This commit fixes it.
Fixes: e4cfa8348dcb97a917daf1d97400a80d1620ed3c
> Fix: Show sync window warning

- charts/kuberpult/templates/frontend-service.yaml
Tracing for the frontend was enabled in #198 but the helm chart wasn't yet updated to include the necessary envs.
> SRX-4SBVE2 Add tracing envs to frontend

- .gitignore
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/config/config.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
If `KUBERPULT_BOOTSTRAP_MODE=true` env variable is provided, then read kuberpult configuration from `./environment_configs.json` and not from manifest repo. 
If bootstrap mode is true, then updating configurations is not allowed. But creating environment without configuration is still allowed.
This file will be created in a subsequent pr from configmap
[SRX-NXORS9](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-N4m28IVhuVJW1-LvRHi/)
> Read config from file in bootstrap mode

- CHANGELOG.md
- services/frontend-service/pkg/cmd/server.go
HTST is a security feature that tells the browser to remember the domain
and never use http requests, but instead use https.
https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
> Add HTST header to frontend service

- charts/kuberpult/ci/test-values-override.yaml
- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml.tpl
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
Add bootstrap mode in chart.
When bootstrap mode is enabled, configuration is read from configmap in source repository and not from config files in manifest repo
[SRX-NXORS9](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-N4m28IVhuVJW1-LvRHi/)
> Add bootstrap mode in kuberpult chart

- pkg/testfs/testfs.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
Several file operations didn't have useful error messages. I've added more context to them and also made sure that we actually get good error messages by using a special testfs that injects errors at arbitrary places.
> Add better error messages to deleting locks SRX-9TWQNN

- charts/kuberpult/templates/cd-service.yaml
With GitLib2 we have the issue that the storage slowly, but eventually runs full.
Using emptyDir works around this issue,
as it restarts the pod and creates a new volume when the original volume is full.
Plus, we never needed our volume to be persistent anyway.
All critical data is saved in the manifest repository.
> Use emptyDir in order to work around volume growth

- CHANGELOG.md
- charts/kuberpult/templates/cd-service.yaml
Currently we still have a cache, and that cache only works when the data is stored beyond pod restarts.
In the future we will remove the cache and go back to emptydir, but for now, we need the cache working.
This does not fix the high memory usage, but it will improve startup times after the cache is filled once.
This is almost an exact revert of commit fc057869dc4656cc59e5db195f1cb4879c720add.
> Temporarily going back to use a persistant volume

- pkg/auth/azure.go
- services/cd-service/Buildfile
- services/frontend-service/Buildfile
without this, when loading the url for kuberpult, the react ui would not be displayed. Instead it would throw an error that invalid auth header specified. So to get access to react ui, this path shouldn't have authorization
> Remove token validation from root path

- services/frontend-service/src/legacy-ui/App/AuthContext.test.tsx
Adding full instance of msal instance is uncontrollable and calls dom methods in test which break the test.
There are tests that exist with mocked msal isntance, the real one can't be used here. So removing those tests
https://github.com/freiheit-com/kuberpult/runs/7834909962?check_suite_focus=true#step:9:174
> Remove full auth context (without dummy msal instance) test. To avoid document.cookie error

- infrastructure/scripts/metadata-migration/Migration.md
- services/cd-service/pkg/repository/repository.go
quote from the story: 
> Do not read old data. If data is not found, just return nil/"". 
> Since we have the migration script, this should be fine.
> Add documentation for scripts and return nil when locks are not found

- charts/kuberpult/values.yaml.tpl
the ui is taking more memory. could be because the overview response is bigger. or because V2 UI is taking memory too. 
after upgrade from 0.4.33 to 0.4.38
> Increase frontend service memory to stop OOM-killed

- services/frontend-service/src/ui/utils/GrpcApi.tsx
Previously, we had the `GrpcProvider`
https://github.com/freiheit-com/kuberpult/blob/fc2f1933f12663a8fa9a6ef3945e6f4d1d2de7e6/services/frontend-service/src/legacy-ui/Api.tsx#L81-L86
now we can just use the exported `useApi`
> Copy api definitions to new UI directory.

- services/frontend-service/.eslintrc
- services/frontend-service/.npmrc
- services/frontend-service/package.json
- services/frontend-service/pnpm-lock.yaml
- services/frontend-service/src/legacy-ui/ActionsCart/ActionsCart.test.tsx
- services/frontend-service/src/legacy-ui/ReleaseDialog.test.tsx
- services/frontend-service/src/legacy-ui/Releases.test.tsx
* new prettier update merged the different configs into "prettier"
* don't fail on missing peers
* update eslint version
* pnpm allows react 18 and mutes warnings from mui requiring react 17
* add babel to dev deps
* ignore eslint it's already installed by another package
* fix failing tests after complaining of unmatched types
https://github.com/freiheit-com/kuberpult/issues/289
> Update eslint plugins, force allow react 18, fix tests

- charts/kuberpult/templates/frontend-service.yaml
- pkg/auth/azure.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/config/config.go
- services/frontend-service/pkg/handler/handle.go
- services/frontend-service/pkg/handler/handle_test.go
- services/frontend-service/pkg/handler/releasetrain.go
Add reading the gpgkeyring to the frontend service. 
this is used to verify the signature of the release train requests. 
in the backend the API requests can't be verified easily. 
any release train curl requests will have to be modified to be signed by gpg to be accepted by the service
> Verify releasetrain requests with pgp

- services/frontend-service/package.json
- services/frontend-service/pnpm-lock.yaml
- services/frontend-service/src/legacy-ui/App/AuthContext.tsx
- services/frontend-service/src/legacy-ui/App/index.tsx
when az auth is on, the authorization token might take a little time to be ready (basically till we login) and so we need to refresh the overview again after getting the token.
fix a bug with `react-error-overlay` where react sometimes fails with `Uncaught ReferenceError: process is not defined` after using an `iframe`. 
source: 
* https://github.com/facebook/create-react-app/issues/11773
* https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined
sorry about the typos will fix before merging.
> Refresh overview on login

- CHANGELOG.md
- README.md
- pkg/api/api.proto
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/frontend-service/src/legacy-ui/ActionDetails.tsx
- services/frontend-service/src/legacy-ui/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
* rename Queue Lock Behavior to Record
* Remove "Delete Queue" button and action from UI
* Stop deploying queued version when deleting a lock
> SRX-XYKGST Don't deploy queued version when unlocking

- CHANGELOG.md
- charts/kuberpult/templates/ingress.yaml
- charts/kuberpult/values.yaml.tpl
* teams can decide on their own whether or not to make kuberpult public
* introduces `ingress.create` helm template variable
> MSD-I2FA2Q - Make ingress creation optional

- CHANGELOG.md
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/service/deploy_test.go
- services/frontend-service/pkg/handler/environments.go
- services/frontend-service/pkg/handler/releasetrain.go
Until now, only the grpc version of the release train was able to filter for teams. Now also the rest endpoint can filter by team.
The logic has not changed.
Also added the team to the commit message for release trains, if the train runs for only one team.
> Allow team based train via rest

- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.scss
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
- services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/Releases/Releases.test.tsx
- services/frontend-service/src/ui/components/chip/chip.test.tsx
- services/frontend-service/src/ui/components/chip/chip.tsx
The colors will be set automatically, depending on the "upstream" settings in config.json.
There are 4 groups:
* prod: Green. These are all envs that are the last in the chain.
* pre-prod: Blue: All envs that come directly before prod.
* upstream=true: Orange. These are all envs that are deployed immediately (usually called "dev").
* other: Grey: All envs that are none of the above, e.g. if you have a chain of 4.
> SRX-OMXZMI Adding colors to environments

- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch_test.go
- services/cd-service/pkg/service/service_test.go
we have 3 structs called "config", which is unnecessarily confusing. This PR is renaming one of them.
> refactoring: rename config to RepositoryConfig

- services/cd-service/pkg/service/overview.go
This endpoint is still being used, also in the new ui, so we have to supply it with the group as well
> Add EnvironmentGroup to getOverview endpoint

- CHANGELOG.md
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
go-billys WriteFile function has a funny behavior: It does not allow overwriting an existing file with empty content. We work around this by giving the file a single space. For argoCd this should not make a difference
> Bugfix: Write undeploy versions correctly into manifest repo

- infrastructure/scripts/create-testdata/create-release.sh
Added `LC_CTYPE=C` env var before `tr` in `create-release.sh` script to work on M1 mac
> Fix `tr` issue on mac in test-data script

- services/frontend-service/src/ui/components/LocksTable/LocksTable.tsx
this change fixes the `<div> cannot appear as a child of <tbody>` errors that show up in the locks page
> SRX-ZP4P4F  Fix wrong tags in LocksTable

- pkg/api/api.proto
- pkg/logger/http.go
- services/cd-service/pkg/config/config.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
- services/frontend-service/pkg/handler/releasetrain.go
This adds a new field `EnvironmentGroups` to the server response.
The old field `Environments` still exists, but is deprecated. Logically, they contain the same information, but `EnvironmentGroups` is structured better for use in the UI.
This commits moves over functions like `calculateEnvironmentPriorities` to the server, that where implemented on client side before.
> Add Environment Groups to getOverview response

- CHANGELOG.md
- services/frontend-service/pkg/cmd/server.go
Before this change, when AzureAuth was enabled, the frontend services's health check did not work, as it responds with `Invalid authorization header provided`.
With this change, the health endpoint does not requires authentication anymore. It does not matter anymore if AzureAuth is enabled or not.
> Bugfix: Do not require authentication in frontend-service health check

- .github/workflows/execution-plan-snippet.yml
`git config --global --add safe.directory "$GITHUB_WORKSPACE"` is required, presumably because the `Test, Build and Publish` step is now running in parallel
> Fix kuberpult release

- services/cd-service/pkg/cmd/server.go
- services/frontend-service/pkg/cmd/server.go
Enables the url path `/v2/home` for everyone.
Note that this url is usable, but still missing some features. In general, we recommend to keep using the old UI for now, under url path `/`.
> Make v2 publicly available (beta)

- services/cd-service/pkg/httperrors/httperrors.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/deploy.go
- services/cd-service/pkg/service/lock.go
- services/cd-service/pkg/service/overview.go
We now differentiate between "internal" and "public" errors. Internal errors are returned as http code 500 with no further details. Public errors are returned as http code 400 with the error message attached.
Also moved the function "internalError" into its own package "httperrors".
> Improved error handling for release trains

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
When a version is queued, we display this in the UI.
Note that queues are for informational purposes only. They don't effect how something is deployed.
A version can be queued when a deployment fails, either because the release train ran into an application lock, or the /release endpoint ran into (any) lock.
SRX-2DXE9T
> Display queued version in v2 release dialog

- services/frontend-service/.eslintrc
- services/frontend-service/src/legacy-ui/.eslintrc
- services/frontend-service/src/legacy-ui/Releases.tsx
- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx
- services/frontend-service/src/ui/components/LockDisplay/LockDisplay.tsx
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
- services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/Releases/Releases.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
- services/frontend-service/src/ui/components/button/button.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
- services/frontend-service/src/ui/components/dropdown/dropdown.tsx
- services/frontend-service/src/ui/components/navigation/navList.tsx
- services/frontend-service/src/ui/components/navigation/navListItem.tsx
- services/frontend-service/src/ui/components/textfield/textfield.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
- services/frontend-service/src/ui/utils/store.tsx
Added rule '@typescript-eslint/explicit-function-return-type' which requires all functions to have an explicit return type.
Also added a specific .eslintrc for the old ui, which disables this rule, because we do not want to spend much time with the old ui anymore.
Adapted all functions that didn't have a return type.
This is a refactoring, it does not change any behavior.
SRX-2DXE9T
> Refactoring: Require return types in new ui

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
> Fix alignment for queue information in release dialog

- services/cd-service/pkg/repository/repository.go
Kuberpult cannot work properly without at least one environments configured, so we print a warning on startup, if none are found.
Usually this is an error (at least when running locally). However, sometimes it is intended to start up without environments (and then add them dynamically via the "createEnvironment" endpoint).
Therefore, it's just a warning.
> Added warning if there are no envs configured during startup

- services/frontend-service/src/assets/_variables.scss
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.scss
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.scss
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.test.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
- services/frontend-service/src/ui/components/chip/chip.scss
- services/frontend-service/src/ui/utils/store.tsx
* As in the figma design, show a trailing number of releases after the currently deployed ones.
* add a margin for whenever environment tags are not displayed.
* add Diff Elements and styles
* add the small lock icons on environment chips
> Show more older releases on home

- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
If an environment doesn’t have an `Upstream`, calculating distance upstream stuck in infinite for loop
>  fix distance to upstream

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
This makes the Release dialog more compact in height. It also fixes an issue where the "deploy" button was out of bounds when there was too much text on the left.
New: ![2023-03-07_17-24_after](https://user-images.githubusercontent.com/3481382/223484907-1abbce14-699b-4b8c-b483-54ce3f7c1ccd.png)
Old: ![2023-03-07_17-24_before](https://user-images.githubusercontent.com/3481382/223484910-6f9ddca6-a6b4-4f8b-add4-74fefd6792e4.png)
> Remove whitespace in ReleaseDialog of new UI

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
Instead of "version 5" we now display the commit message of the release
Added tooltip to save some space.
New tooltip:
> Rephrase release dialog text

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/utils/store.tsx
Some releases do not exist. When a new app is created, it will not be deployed everywhere instantly. This fixes a crashing ReleaseDialog in this situation
> Fix ReleaseDialog if not all envs deployed

- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
- services/frontend-service/src/ui/components/chip/chip.scss
Before they were display vertically, now they are displayed horizontally.
Old:
New:
> Fix rendering of group labels on ReleaseCards

- services/frontend-service/src/ui/utils/store.tsx
When services were not deployed, the service lane crashed, because useDeployedReleases returned the 0 release.
Now it skips the 0 release, because it is not an actual release. It just means "no release".
SRX-M2E91H
> Fix 0 deployment in new UI

- infrastructure/scripts/create-testdata/create-release.sh
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
This fixes an issue when the "release" endpoint gets a "version" parameter that is less than the newest version number.
In that case, kuberpult didn't generate any manifest files (just the basic files like "author" were written).
> Fix version parameter of release endpoint

- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
This fixes a bug in the "undeploy" request.
The issue was that kuberpult checked if the app was deployed (with version "undeploy") in all environments. This was a prerequisitve to run "undeploy".
However, some apps are not supposed to be deployed in all environments. (It's an edge case, but it can happen, especially when environments are added later on).
Now, we allow to delete apps, even if they don't exists everywhere.
This is a fix for https://github.com/freiheit-com/kuberpult/issues/451
SRX-M2E91H
> Fix undeploy for apps that are not in all envs

- pkg/api/api.proto
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
We should do all complex calculations in the backend.
The undeploy summary will be used to determine which option to show the user (create undeploy version or delete completely)
> Return undeploy summary in cd-service

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/store.tsx
* move the `envs[]` from release dialog props type into testdata type. in release dialog test
* show the app name on release dialog
* show team name also when it's available
* refactor a little in release dialog test (fix the red squiggles)
[SRX-HLVCYS](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-NOAP23nj5zjMg-U0fo4/)
> Show Application and Team on Release Dialog

- pkg/api/api.proto
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
If there is an app lock while deleting an app, we ignore the lock (and delete it too).
Env locks are not considered or touched for deletion of apps.
> Fix bug in app deletion when there are app locks

- services/frontend-service/pkg/cmd/server.go
Before this change, a full page reload in the browser on the pages "/locks" and "/environments" lead to a "not found" or similar message
> Bugfix: Allow full page reload in UI

- services/frontend-service/src/ui/App/index.test.tsx
- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/Pages/Releases/ReleasesPage.tsx
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
- services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.test.tsx
- services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/Releases/Releases.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
The two query parameters `dialog-app` and `dialog-version` open the dialog automatically. the release card would set the parameters to show a new dialog. closing the dialog will simply clear the parameters. 
* delete the `useReleaseInfo` hook from the store.
* `useOpenReleaseDialog` to add the query params for some app/version
* `useCloseReleaseDialog` to clear those params
* `useReleaseDialogParams` to get the app/version from the URL and verify that they represent an actual release. => Then open the dialog.
* remove the release dialog store
> Allow Release Dialog to open via query parameters

- services/frontend-service/pkg/cmd/server.go
Allow url paths starting with home to be served
this is a fix for #635
> Allow direct links/reloads of releases page of an application

- README_DEVELOPERS.md
- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml.tpl
- check.sh
- codereviewr.yaml
- infrastructure/docker/backend/Dockerfile
- services/cd-service/Dockerfile
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/httperrors/httperrors.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/sqlitestore/README.md
- services/cd-service/pkg/sqlitestore/sqlite.c
- services/cd-service/pkg/sqlitestore/sqlite.h
- services/cd-service/pkg/sqlitestore/sqlitestore.go
- services/cd-service/pkg/sqlitestore/sqlitestore_test.go
The git storage format is a tricky thing. Git stores new files as single files on disk and compacts them occassionally into bigger files containing multiple smaller files. We need to start an external process that does this compaction. When the process works, it deletes the packed files that are still openend by libgit and so leaves deleted file descriptors hanging around. When the process doesn't work, it leaves ugly error messages.
Sqlite in contrast is a proven storage mechanism that always uses a single file to store its data regardless of the number of entries added. The good thing is that it doesn't require any external compaction runs. By leveraging the libgits storage backend interface, we get libgit to store its data in sqlite instead of git pack files. The effect can be seen in …
> Add sqlite backend to kuberpult

- pkg/api/api.proto
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/testrepository/testrepository.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
- services/frontend-service/src/ui/utils/store.tsx
In the rollout service, I get the currently deployed commit id from argo cd. I need some way to figure out the application version of the services in each environment. The overview endpoint already contains this information and we also have a streaming endpoint for it which would make it a perfect fit to use for that usecase. The only thing that is missing is, is the git commit id and an option to retrieve older overviews.
This commit implements exactly this.
> Added git commit parameter and field to the overview service

- services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/store.tsx
This will be used later to identify locks by ID.
SRX-VMZUKT
> Use same lock ID for locks in one batch

- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.scss
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
Render only first line in the release cards, but render all of the lines with proper newlines in the tooltip
> Render commit message nicer in ReleaseCards

- services/frontend-service/src/assets/_variables.scss
- services/frontend-service/src/setupTests.ts
- services/frontend-service/src/ui/components/LocksTable/LocksTable.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.scss
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
If a user removes a lock (adds it to the planned actions), kuberpult now checks if there are "similar" locks. We assume a lock is similar, if it has the same ID. Locks can have the same ID if they are different in other fields like "app" and "env".
UI:
> Add button to delete all similar locks

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
New:
Old: (notice the scrollbar)
> Reduce Whitespace in ReleaseDialog

- services/cd-service/pkg/argocd/render.go
- services/cd-service/pkg/argocd/render_test.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer_test.go
By adding the annotations
- com.freiheit.kuberpult/team
- com.freiheit.kuberpult/application
- com.freiheit.kuberpult/environment
it's possible to connect applications in argocd directly to applications/envs/teams in kuberpult
> Add annotations to ArgoCD application

- charts/kuberpult/templates/frontend-service.yaml
- pkg/setup/setup.go
- pkg/setup/setup_test.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/cmd/server_test.go
- services/frontend-service/pkg/config/config.go
This adds a `Content-Security-Policy` and adds a proper allowed origin to cors.
Most code is actually spend to make it testable. Most notably to shut down the go http/grcp server. This was only possible using a global queue or OS signal but now it's sufficient to cancel the context it's running in.
> Add more secure header configurations and add tests to frontend server

- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/cmd/server_test.go
emotionjs injects dyanmic sytle elements. This of course conflicts with CSP. There are some complicated ways around this with csp nonce. However, we want to get rid of emotionjs anyway. In the meantime, we have to use unsafe-inline.
> Allow style elements from emotionjs

- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/cmd/server_test.go
For the simple test case that was already added by the 404 handler. However, when we actually serve files, it's not. This adds it explicitly for all cases.
> Add content-type nosniff header

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/values.yaml.tpl
This is *technically* a breaking change.
This change allows to specify different docker image tags for the cd service and the frontend service.
However, this is only the case if you specify the "tag" in the helm chart. It is rather unlikely that you do this.
In almost every case, kuberpult should run with the same version for all microservices (cd services and frontend service).
> Separate tags for services

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
Manual deployment happen usually when there is an important bugfix to be deployed. In that scenario, usually a lock is a good idea. With this change, the "deploy" button is replaced by "deploy & lock".
SRX-S3C8AL
> Also lock when deploying manually

- README_DEVELOPERS.md
- services/frontend-service/src/react-app-env.d.ts
- services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
This change should enable renovate (https://github.com/freiheit-com/kuberpult/pull/632) to succeed with the upgrade to node18
> Prepare for upgrade to node 18

- go.mod
- go.sum
- pkg/auth/azure.go
- pkg/auth/azure_test.go
- services/frontend-service/pkg/cmd/server.go
They both belong together and require some changes in the returned error messages (and therefore renovate could not create a working PR).
This is based on https://github.com/freiheit-com/kuberpult/pull/676/files
> Update module github.com/MicahParks/keyfunc to v2 and jwt to v5

- services/cd-service/Makefile
- services/cd-service/pkg/httperrors/httperrors.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/batch_test.go
Do not ignore git push errors
Also return readible error in case we cannot push to the manifest repo.
2 error cases are handled in this PR:
1) the ssh key does only have read only access. This returns a normal error (at least on github)
2) there is a branch protection rule stopping access. This is not a normal error, but signaled via the "PushUpdateReferenceCallback"
In both cases we return the error to the caller instead of "internal error".
In order to test these 2 error cases, I had to introduce 2 Callbacks for `ProcessQueueOnce`.
This is the solution for https://github.com/freiheit-com/kuberpult/issues/712
> Do not ignore git push errors

- services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
This is required because we rely on those headers to be set in order to write the author to the commit message.
> Append email and username and pass it along to the batchservice

- go.mod
- go.sum
This reverts commit 0af55faa161e0895300bcb405e195e57eb346201.
This upgrade was breaking our tests in the rollout-service, see here https://github.com/freiheit-com/kuberpult/actions/runs/5391300038/jobs/9787944326
> Revert "Update module github.com/argoproj/gitops-engine to v0.7.3

- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/service/service.go
The /release endpoint is  very silent at the moment. Let's make it more chatty.
> Added error messages and error logs to the release endpoint

- pkg/auth/azure.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/interceptors/interceptors.go
They are only used in the frontend, and it doesn't make much sense to share them, given their purpose
> Refactoring: Move interceptors to frontend

- go.mod
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/service/service.go
- services/cd-service/pkg/service/service_test.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/handler/environments.go
- services/frontend-service/pkg/handler/handle.go
- services/frontend-service/pkg/handler/handle_test.go
- services/frontend-service/pkg/handler/locks.go
- services/frontend-service/pkg/handler/releasetrain.go
The x/go-crypto package is deprecated in the sense that _known bugs are not fixed_. Apparently there are real world bugs: https://github.com/orgs/community/discussions/27607#discussioncomment-3414366
The replacement promises to fix them
> Replaced x/go-crypto with ProtonMail/go-crypto

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
Adds details on who deployed and when to the UI
> services/frontend-service: Add deployedBy and deployedAt to UI

- README_DEVELOPERS.md
- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/values.yaml.tpl
- docker-compose.tpl.yml
- infrastructure/scripts/create-testdata/create-release.sh
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/httperrors/httperrors.go
- services/cd-service/pkg/interceptors/interceptors.go
- services/cd-service/pkg/repository/queue.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/batch_test.go
- services/cd-service/pkg/service/deploy_test.go
- services/cd-service/pkg/service/lock_test.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
- services/cd-service/pkg/service/service.go
- services/cd-service/pkg/service/service_test.go
- services/cd-service/pkg/testutil/testutil.go
- services/frontend-service/Makefile
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/config/config.go
- services/frontend-service/pkg/handler/release.go
- services/frontend-service/pkg/interceptors/interceptors.go
Make git author configurable in helm chart & refactor context usage
This is technically not a breaking change, but it is recommended to now set the author and email when invoking the /release endpoint. Note that both headers must be base-64 encoded. See create-release.sh for a valid example call with headers. If you do not provide these headers, the git author will be set to "empty".
New helm chart variables can be set, but they come with the same default values as before:
* git.author.name
* git.author.email
This also refactored how to access the context.
The cd-service now always* returns an error when the context should be there but is not, instead of always falling back to default values.
Exception is the release endpoint, as this would be a breaking change. (And of course /health …
> Make git author configurable in helm chart & refactor context usage

- services/frontend-service/src/assets/_components.scss
- services/frontend-service/src/ui/components/ServiceLane/DotsMenu.scss
- services/frontend-service/src/ui/components/ServiceLane/DotsMenu.test.tsx
- services/frontend-service/src/ui/components/ServiceLane/DotsMenu.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
- services/frontend-service/src/ui/components/button/button.tsx
The buttons "show history", "Prepare Undeploy Release" and "Delete Forever" are now hidden in a menu, since they are rather uncommon.
This also allows us to add more buttons easily.
Story SRX-36LKZS
> Hide Buttons behind "..." menu in service lane

- services/frontend-service/src/ui/utils/store.tsx
In the previous implementation locks would also be displayed on apps that names are contained in a locked app's name.
> Bugfix: Display locks only for the correct  application

- services/cd-service/pkg/interceptors/interceptors.go
- services/frontend-service/src/setupTests.ts
- services/frontend-service/src/ui/components/ServiceLane/DotsMenu.scss
- services/frontend-service/src/ui/components/ServiceLane/DotsMenu.tsx
- services/frontend-service/src/ui/components/ServiceLane/EnvSelectionDialog.test.tsx
- services/frontend-service/src/ui/components/ServiceLane/EnvSelectionDialog.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.test.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/store.tsx
Adds a button to the "..." menu that allows the user to delete environments from one app.
It is possible to select multiple envs, but it is not allowed to delete all environments.
Also this re-enables the tooltip in the planned actions and gets rid of some unnecessary logs.
Story SRX-36LKZS
> UI: Delete environments from an app

- renovate.json
* DIsable autorebase for renovate.
* Change schedule to be daily.
> Disable autorebase when behind base branch option for renovate

- pkg/tracing/service.go
- pkg/tracing/service_test.go
- services/cd-service/pkg/cmd/server.go
- services/frontend-service/pkg/cmd/server.go
- services/rollout-service/pkg/cmd/server.go
Our traces currently show up as "cd-service" and "kuberpult-cd-service" in datadog. This is due to us setting the DD_SERVICE to one value and the tell the tracer to use another. This commit fixes that to always prefer the DD_SERVICE env and adds the correct default value for testing.
> Use correct service names in all services

- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
The cd service requires a user in the grpc metadata. It can be literally anything but it must be there.
> Add a dummy user to the rollout service

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml.tpl
- services/cd-service/pkg/cmd/server.go
If Dex is enabled, adds the config map specifying the Policy to be used. 
Rev: SN-CV2ND9
> Add Dex RBAC Config Map

- charts/kuberpult/values.yaml.tpl
- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
- services/cd-service/pkg/cmd/server.go
Adds the RBAC policy parser methods.
Rev: DSN-CV2ND9
> Add RBAC policy parser methods

- services/frontend-service/src/assets/_components.scss
- services/frontend-service/src/ui/components/ServiceLane/EnvSelectionDialog.test.tsx
- services/frontend-service/src/ui/components/ServiceLane/EnvSelectionDialog.tsx
- services/frontend-service/src/ui/components/dropdown/checkbox.scss
- services/frontend-service/src/ui/components/dropdown/checkbox.test.tsx
- services/frontend-service/src/ui/components/dropdown/checkbox.tsx
- services/frontend-service/src/ui/components/dropdown/dropdown.tsx
The goal is to get rid of material-ui.
The checkbox is now used in more places, so this PR gets rid of the material-ui checkbox component.
This changes the rendering slightly, but not the behavior.
New Checkbox:
Old Checkbox:
SRX-Z1SMB9
> Refactor checkbox to reduce material-ui usage

- codereviewr.yaml
- pkg/auth/auth.go
- pkg/auth/rbac.go
- pkg/testutil/testutil.go
- services/cd-service/Makefile
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/interceptors/interceptors.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/batch_test.go
- services/cd-service/policy.csv
Takes the extracted role information from the GRPC context. 
When Dex is enabled then checks if associated role has permissions for createEnvironmentLock. 
Blocks user if their role does not have permissions.
> Block Users without Permission from Creating Environment Locks

- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
From tracing, I saw that the rendering requests to the repo server take quiet long when you have > 2k apps. There is an option in the repo server to make this faster by avoiding the global lock. This lock is in place because some manifests renderer ( e.g. kustomize with parameter overrides ) create local files and therefore cannot run in parallel. By putting a special file in the apps root path, we can signal argocd to avoid this locking all together.
See here: https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#enable-concurrent-processing
And here: https://github.com/argoproj/argo-cd/blob/f1607fee7c3bfad8eb56a53130cf9ac7cc22dd34/reposerver/repository/repository.go#L1023
> Allow argocd to render our manifests in parallel

- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
Reverts freiheit-com/kuberpult#822
I read the documentation and the code in the repository doesn't actually work as documented. Actually it seems like this file is only considered for helm charts ( which is irrelevant for us ).
Here is the code for helm charts, checking the file: https://github.com/argoproj/argo-cd/blob/f1607fee7c3bfad8eb56a53130cf9ac7cc22dd34/reposerver/repository/repository.go#L1064
Here is the code for manifest dirs, not checking the file at all: https://github.com/argoproj/argo-cd/blob/f1607fee7c3bfad8eb56a53130cf9ac7cc22dd34/reposerver/repository/repository.go#L1538C16-L1538C16
Given that the documentation is probably misleading, I would revert this for now.
> Revert "Allow argocd to render our manifests in parallel"

- services/frontend-service/package.json
- services/frontend-service/pnpm-lock.yaml
- services/frontend-service/src/assets/_base.scss
- services/frontend-service/src/assets/_components.scss
- services/frontend-service/src/setupTests.ts
- services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.scss
- services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx
- services/frontend-service/src/ui/components/EnvironmentLockDisplay/EnvironmentLockDisplay.tsx
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.scss
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.test.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
- services/frontend-service/src/ui/components/chip/chip.scss
- services/frontend-service/src/ui/components/tooltip/__snapshots__/tooltip.test.tsx.snap
- services/frontend-service/src/ui/components/tooltip/tooltip.scss
- services/frontend-service/src/ui/components/tooltip/tooltip.test.tsx
- services/frontend-service/src/ui/components/tooltip/tooltip.tsx
- services/frontend-service/src/ui/utils/store.tsx
We now have 2 tooltips: tooltip.tsx, our own implementation using react-tooltip. the "title" attribute for simple text-only tooltips.
Also simplified the EnvironmentLockDisplay a bit.
New Tooltip on Environments page:
New Tooltip on Service Lane:
SRX-Z1SMB9
> Refactoring: Use own tooltip component

- charts/kuberpult/values.yaml.tpl
- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch_test.go
- services/cd-service/policy.csv
Refactors the permission policy to follow the following format: `<ROLE>, <ACTION>, <ENVIRONMENT_GROUP>:<ENVIRONMENT>, <APPLICATION>, allow`
The allowed actions are: `CreateLock`, `DeleteLock`, `CreateRelease`, `DeployRelease`, `CreateUndeploy`, `DeployUndeploy`, `CreateEnvironment`, `CreateEnvironmentApplication` and `DeployReleaseTrain`.
The following actions `CreateUndeploy`, `DeployUndeploy` and `CreateEnvironmentApplication` are environment independent meaning that the environment specified on the permission needs to follow the following format `<ENVIRONMENT_GROUP>:*`, otherwise an error will be thrown.
> Refactor permission policy RBAC

- services/frontend-service/Makefile
- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.test.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
- services/frontend-service/src/ui/components/tooltip/__snapshots__/tooltip.test.tsx.snap
- services/frontend-service/src/ui/components/tooltip/tooltip.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
- services/frontend-service/src/ui/utils/Links.test.tsx
- services/frontend-service/src/ui/utils/Links.tsx
- services/frontend-service/src/ui/utils/__snapshots__/Links.test.tsx.snap
- services/frontend-service/src/ui/utils/store.tsx
Links will be rendered in 3 places in the Release Dialog:
* on the app name: It links to the app (in all envs)
* on the team name: It links to the team
* on the environment chip: It links to the app in that environment
Also moved some react hooks to store.tsx, because they had nothing to do with AzureAuth.
In order to see the links, the helm value "argocd.baseUrl" must be set.
Reference: SRX-MF4E9M
> Add links to ArgoCd in the UI

- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
Add the following 2 cases for the permission check:
- If it is an environment independent action the, the expected format is `<ENVIRONMENT_GROUP>:*`.
- Checks for an wildcard `*` permission for applications.
> Add App/Environment wildcard permission check

- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
We should not render a link in the small environmentGroupChip, because it is way too small. It also had not-so-nice css.
It was never intended to work for environmentGroups - just environments.
Now we just render text, as before.
> Fix broken link in small environmentGroupChip

- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch.go
Adds Role Based Access Control to `ReleaseTrain`.
> ReleaseTrain Role Based Access Control

- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch.go
Adds the Role Based Access Control to CreateEnvironment. Two cases were considered for this action:
- The user provides and environment group. In this case the specified permission needs to have `<ENV_GROUP>:*` specified. 
- The user only provides the environment name. In this case the specified permission needs to have `*:*` for the env field specified.
> CreateEnvironment add Role Based Access Control

- pkg/testutil/testutil.go
- services/cd-service/pkg/argocd/render.go
- services/cd-service/pkg/argocd/render_test.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer_test.go
This avoids the error in argoCd `rpc error: code = Unknown desc = environments/<env>/applications/<app>/manifests: app path does not exist`
This is usually a problem when creating a new app, because generally all manifest are created in the source repo at once, including for production environments.
However, once submitted to kuberpult via /release endpoint, kuberpult rendered the ArgoCd manifests for **all** environments, even those that are not deployed yet (like production).
With this change, kuberpult will only render the apps in an environment, if it is deployed there.
Reference: SRX-638BGR
> Do not render undeployed argoApps

- services/frontend-service/package.json
- services/frontend-service/pnpm-lock.yaml
- services/frontend-service/src/assets/_components.scss
- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.test.tsx
- services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx
- services/frontend-service/src/ui/Pages/Home/Home.test.tsx
- services/frontend-service/src/ui/Pages/Home/Home.tsx
- services/frontend-service/src/ui/Pages/Locks/LocksPage.test.tsx
- services/frontend-service/src/ui/Pages/Locks/LocksPage.tsx
- services/frontend-service/src/ui/Pages/Releases/ReleasesPage.test.tsx
- services/frontend-service/src/ui/Pages/Releases/ReleasesPage.tsx
- services/frontend-service/src/ui/components/Spinner/Spinner.scss
- services/frontend-service/src/ui/components/Spinner/Spinner.test.tsx
- services/frontend-service/src/ui/components/Spinner/Spinner.tsx
- services/frontend-service/src/ui/components/Spinner/__snapshots__/Spinner.test.tsx.snap
- services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
- services/frontend-service/src/ui/utils/store.tsx
This renders a spinner (in the "pacman style") while loading data.
We differentiate between loading the configuration and the overview.
Examples for 'react-spinner': https://www.davidhu.io/react-spinners/
> Render spinner while loading

- services/cd-service/pkg/argocd/render.go
- services/cd-service/pkg/argocd/render_test.go
- services/cd-service/pkg/repository/transformer_test.go
When having thousands of ArgoCd apps, it becomes problematic to sync the whole repository every n minutes (3 by default).
This PR introduces an annotation to tell ArgoCd: If there is a webhook incoming, compare the paths in the webhook with the paths in this annotation. ArgoCd then only needs to synchronize the files that are in that path. If not set, argoCd will synchronize every file in the whole manifest repo.
This change only has an effect, if there is a webhook configured from the git provider that triggers ArgoCd.
> Allow ArgoCd to use Webhooks to improve performance

- charts/kuberpult/run-kind.sh
- charts/kuberpult/templates/cd-service.yaml
- infrastructure/scripts/create-testdata/create-release.sh
- services/cd-service/pkg/argocd/v1alpha1/types.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/testrepository/testrepository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch_test.go
With this feature, kuberpult sends webhooks that imitate github webhooks to argoCd, which trigger argoCds refreshs.
This is intended to reduce load on ArgoCd. Normally, argoCd renders all manifests again whenever there is a new commit in the manifest repository. However, with Webhooks, it only checks the actually changed files that are part of the Webhook body.
Note that this does not work for all cases, like deletion of environments from apps.
So you can make the "timeout.reconciliation" in argoCd bigger (e.g. 30min instead of the default 3min) - however you should not fully disable it. See https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller
To enable this kuberpult feature, set `argocd.server` in the helm chart to a hostname that …
> Tell ArgoCd to sync apps

- charts/kuberpult/templates/ingress.yaml
- charts/kuberpult/values.yaml.tpl
The publish endpoint takes a minute to reply if pushing to git takes a minute. This is not an error but nginx times out the reply after thirty seconds so that the caller has the impression that something went wrong. The timeout should be much higher. We will start with 5 minutes.
> Increase nginx timeout to 300s

- services/frontend-service/buf.gen.yaml
Warning from ts-proto was: "Passing useOptionals as a boolean option is deprecated and will be removed in a future version. Please pass the string messages instead of true."
> Maintenance: handle ts-proto warning

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml.tpl
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
It's different from the url to clone a repo.
WebUrl has https protocol.
Url to clone a repo uses ssh protocol.
ArgoCd requires this url to have https protocol, otherwise it fails to parse the url and webhooks do not work.
> Add webUrl as separate option for argo webhooks

- pkg/api/api.proto
- pkg/auth/auth_test.go
- services/cd-service/pkg/service/overview.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
Headers are genereally not safe with special characters. Instead of encoding the header with base64, we move the data to a normal grpc message (ProcessBatch), because this is the only request where we have this userdata anyway.
This should fix the bug https://github.com/freiheit-com/kuberpult/issues/874 that happened on azure when users have non-ascii usernames - but it is hard to verify this.
> Submit user data via grpc message instead of header

- pkg/api/api.proto
- pkg/auth/auth_test.go
- services/cd-service/pkg/service/overview.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
This solves https://github.com/freiheit-com/kuberpult/issues/893.
The issue is now handled by proper base64 encoding (which is surprisingly difficult in javascript).
This mostly reverts https://github.com/freiheit-com/kuberpult/pull/889, except for the improved logging.
> Fix encoding issue with http header.

- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/service/broadcast_test.go
- services/rollout-service/pkg/service/service.go
ArgoCD reports errors in one additional field. We also need to consider this field when calculating the rollout status.
> Add more error conditions to the rollout service

- pkg/auth/auth.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/interceptors/interceptors.go
- services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
- services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
There were 2 ways to read the headers. This change removes one of them (which was almost identical).
> Fix author header handling (again)

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml.tpl
I did this now as a helm-only thing to unblock the next kuberpult release. We will clean this up soon.
> Add a feature flag to disable sending webhooks

- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
The rollout status is currently always shown, regardles if its backend is deployed. This change makes the frontend aware of the services availability, displaying the rollout status only if the frontend service doesn't responds with "not implemented" error.
> Don't show the rollout status if it's disabled

- docker-compose.yml
- infrastructure/scripts/create-testdata/create-env-group-lock.sh
- infrastructure/scripts/create-testdata/delete-env-group-lock.sh
- pkg/api/api.proto
- pkg/auth/azure.go
- pkg/logger/logger.go
- pkg/testutil/testutil.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/handler/handle.go
- services/frontend-service/pkg/handler/handleEnvironments.go
- services/frontend-service/pkg/handler/handle_test.go
- services/frontend-service/pkg/handler/locks.go
- tests/integration-tests/release_test.go
This makes it's possible to lock/unlock all environments in one group with one rest call.
The endpoint is `/environment-groups/<envGroup>/locks/<lockId>`, see `infrastructure/scripts/create-testdata/create-env-group-lock.sh` and `infrastructure/scripts/create-testdata/delete-env-group-lock.sh` for details.
Note that this will create multiple *environment locks*.
That means if you create an env lock with id "x" you can then delete it for one environment by calling `/environments/<env>/locks/x" - even though it was created with the `environment-groups` endpoint.
So there are still only 2 kinds of locks: environment locks and app locks.
> Allow locking and unlocking env groups over rest

- charts/kuberpult/run-kind.sh
- charts/kuberpult/templates/rollout-service.yaml
- charts/kuberpult/values.yaml.tpl
- services/rollout-service/Makefile
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/notifier/notifier.go
- services/rollout-service/pkg/notifier/subscriber.go
- services/rollout-service/pkg/notifier/subscriber_test.go
- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/service/broadcast_test.go
- services/rollout-service/pkg/service/service.go
- services/rollout-service/pkg/service/service_test.go
- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
This change adds sending refresh notifications to argocd when applications in kuberpult changes. Notifications are send by the rollout service so that they do not slow down the cd service in any way. The current implementation is rather simple at the moment. The rollout service now listens to the cd service for changes, compares the versions with argocd and issues refresh requests if the version differs.
The feature must be explicitly enabled in the helm chart using `argocd.refreshEnabled`
> Notify argocd about updates

- charts/kuberpult/run-kind.sh
- charts/kuberpult/templates/rollout-service.yaml
- charts/kuberpult/values.yaml.tpl
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/notifier/notifier.go
- services/rollout-service/pkg/notifier/notifier_test.go
There is a new option on the helm chart `argocd.refresh.concurrency` that allows for configuring the number of parallel requests to argocd. Also the timeout for argocd is bumped from 5s to 60s.
> Submit refreshes to argocd in parallel

- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
Currently the rollout service needs to obtain the shared lock for every deployed app. This is rather costly. This patch changes that, so that we do send fewer events to that store by deduplicating the notifications in the versions.go locally.
Furthermore, the versions client never cared about removed apps.  This is also handled properly now.
> Rollout service: dedup version notifications and notify for app deletions

- services/rollout-service/pkg/service/broadcast.go
The error appeared in https://github.com/freiheit-com/kuberpult/actions/runs/6119725177/job/16610230224#step:11:174. Sadly it doesn't appear all the time.
> Fix NPE in broadcast.go

- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch_test.go
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
Message has format of "The user [example@example.com](mailto:example@example.com) with role <role> is not allow to perform the action <action> on environment <env> for team <team>"
Error toast looks like this:
> User get notified of permission errors on the frontend

- services/cd-service/pkg/service/batch.go
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
The server always allowed only 100 actions.
Now the UI also checks if there are too many items, and stops the user before adding the 101st action.
This fixes issue https://github.com/freiheit-com/kuberpult/issues/878
> Show error about too many items before submit

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
Before, it was shown also when the currently looked at version (the one the user clicked on) was in "undeploy".
> Fix: Show "undeploy version" only in correct circumstances

- services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.scss
- services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.scss
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
Example of how this would look like for a deployment
and
> Add Release Version to the frontend SideBar

- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/service/batch.go
The timeout is only applied if there is no deadline for the call setup. It's also just a last-resort as most calls should be much faster. This mainly prevents call from getting stuck forever.
> Added default network timeouts for batch service in the frontend service

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml.tpl
- go.mod
- go.sum
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/grpc/errors.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/testssh/README.md
- services/cd-service/pkg/repository/testssh/server.go
The solution take is highly unelegant but kinda unavoidable given the options available. Basically, libgit as most c based libs doesn't allow cancelling anything. The only thing we can do is to run the push operation in a seperate go routine and return our own timeout after some time while throwing a cancellation at the lib to stop. This is now done in the `useRemote` function. The network timeout is now 1 minute which is probably good enough for most consumers.
> Add networking timeouts to git pushes

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
> Fix lock symbol size on history page

- docker-compose.yml
Kill processes earlier when stopping them locally
When running with docker-compose, handling signals is a hassle, because Make invocations are wrapped in shell scripts.
It's much simpler to just let docker-compose send the kill signal quicker.
This is only relevant for local development.
> Kill processes earlier when stopping them locally

- services/frontend-service/src/setupTests.ts
- services/frontend-service/src/ui/components/EnvironmentLockDisplay/EnvironmentLockDisplay.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/ServiceLane/DotsMenu.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
If the user wants to deploy an app that has a lock, or if the user wants to deploy to an environment that has a lock, we now show a warning (when submitting the actions), because generally locks should not be ignored.
The dialog shows which locks are the "offenders".
The user can still choose to ignore this, but now they have been warned.
New Dialog with offending locks:
New Dialog without offending locks:
> UI: Show warning before deploying over a lock

- services/rollout-service/pkg/notifier/subscriber.go
- services/rollout-service/pkg/notifier/subscriber_test.go
- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/service/broadcast_test.go
- services/rollout-service/pkg/service/service.go
- services/rollout-service/pkg/service/service_test.go
- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
I need to have the time when something is deployed to calculate how much argocd is behind kuberpult. The deploy time is available in `DeploymentMetaData.DeployTime`
> Track DeployTime of applications in the rollout service

- infrastructure/docker/builder/Dockerfile
This is required for the shell-checker to work properly https://github.com/freiheit-com/kuberpult/pull/967
> Add bash to builder image

- charts/kuberpult/templates/_helpers.tpl
- charts/kuberpult/templates/rollout-service.yaml
- charts/kuberpult/values.yaml.tpl
This adds a new option to the rollout service to add annotations to the pod directly. The current annotations will be used as a default and will be merge with the specified ones.
> Add pod annotations to the rollout pod

- services/frontend-service/src/ui/components/ServiceLane/EnvSelectionDialog.tsx
- services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx
> Refactor EnvSelection to not use mui

- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/service/broadcast_test.go
In case the argocd app has not been created, the rollout service currently segfaults.
> Fix: segfault in rollout service

- services/frontend-service/src/assets/_variables.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/components/dialog/ConfirmationDialog.scss
- services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx
The layout has been adopted slightly.
Now:
Before:
> Refactor ReleaseDialog to not use mui

- pkg/api/api.proto
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.scss
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
- services/rollout-service/pkg/metrics/metrics.go
- services/rollout-service/pkg/metrics/metrics_test.go
- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/service/broadcast_test.go
- services/rollout-service/pkg/versions/versions_test.go
When looking at the rollout_lag metrics, I noticed that they sometimes jump from zero to several days and back to zero. I inspected this and it turned out that these apps are just becoming unhealthy and recover. In that case the rollout_lag should not go up again. In order to solve this, I added two more intermediate states to the rollout states.
- `progressing` ( = change not applied yet ) is split up into `progressing` ( = argocd is working on it ) and `pending` ( = argocd has not picked it up yet )
- `error` ( = something failed ) is split up into `error` ( = sync failed ) and `unhealthy` ( = health is degraded )
> Distinguish more rollout states

- pkg/auth/azure.go
- pkg/auth/azure_test.go
When azure was enabled in the helm chart, it was not possible to make REST calls to create locks for environment groups.
This was fixed. The REST call for locks to environments were not effected.
> Fix: Allow locks for groups with azure enabled

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
Now:
Before:
This fixes https://github.com/freiheit-com/kuberpult/issues/987
> Fix: ReleaseDialog renders many environments

- charts/kuberpult/run-kind.sh
- tests/integration-tests/.gitignore
- tests/integration-tests/main_test.go
- tests/integration-tests/release_test.go
I increased the run-kind timeout to infinity and I made the integration tests repeatable locally.
> Make it easier to run integration tests locally

- tests/integration-tests/rollout_test.go
There is now a new integration test that checks if we can sync something into the cluster and that argocd sees the right manifests.
> Add an integration test for syncing manifests into the cluster

- charts/kuberpult/run-kind.sh
- go.mod
- go.sum
- services/cd-service/Makefile
- services/cd-service/pkg/argocd/reposerver/reposerver.go
- services/cd-service/pkg/argocd/reposerver/reposerver_test.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/fs/fs.go
- services/cd-service/pkg/grpc/errors.go
- services/cd-service/pkg/interceptors/interceptors.go
The first two endpoints `GenerateManifest` and `ResolveRevision` are the absolute minimum that is  needed to make  the integration test  work. I have made sure  that our implementation is correct by starting the argocd repo server in the unit tests and tested that they give the  same responses.
> Added the first two endpoints for the repository service

- services/frontend-service/pkg/cmd/server.go
The function runServer used the Fatal function of the zap logger. This has really unfortunate results in tests: You cannot see any details, except the name of the test and that it failed Instead we should always log with "Error" and then return the error (or only return the error).
> Fix server_test in frontend-service

- .github/workflows/execution-plan-main.yml
- .github/workflows/execution-plan-pr.yml
- .github/workflows/execution-plan-tag.yml
Chart testing was not working properly.
It has its own logic to decide if it needs to run, and often it just doesn't.
I suspect this has not been working for a long time.
It is not a huge loss to remove it, because we have integration tests that also install our helm chart.
Reference: SRX-WJULW1
> Remove chart testing from CI

- docker-compose.yml
The path must point to a local checked out (git clone) manifest repo.
This is now different, because the docker context for the cd-service is the git root, instead of `services/cd-service`.
> Fix docker-compose path to manifest repo

- services/frontend-service/src/ui/components/dropdown/dropdown.scss
This fixing a missing scrollbar in the filter for teams on the homepage.
Now:
(note that I duplicated the teams just for testing. Usually each team appears once)
Before:
> Fix teams dropdown overflow

- charts/kuberpult/templates/rollout-service.yaml
- charts/kuberpult/values.yaml.tpl
- go.mod
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/revolution/revolution.go
- services/rollout-service/pkg/revolution/revolution_test.go
- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
This adds a new subservice to the rollout service that sends out deployment events to revolution.
> Send dora events to revolution

- renovate.json
Note that the schedule configuration is to limit renovate, not to enable it.
Docs: https://docs.renovatebot.com/configuration-options/#schedule
> Allow renovate to run at any time

- charts/kuberpult/Makefile
This is a workaround for an issue with CT while releasing a new kuberpult version
> Fix: Add helm dependency to release pipeline

- services/frontend-service/Buildfile.yaml
re-release, since the previous release had issues with the dex helm chart.
The rebuild-counter is necessary for the integration tests (otherwise they pick the wrong image, which leads to the wrong thing being tested).
> Release 1.11.0

- pkg/metrics/metrics.go
- pkg/setup/setup.go
- pkg/setup/setup_test.go
- services/rollout-service/pkg/cmd/server.go
This makes the /metrics endpoint available on all services and to all background tasks. I need to have this available in my next MR to register a metric there that is 0/1 for all background tasks depending on wether they are running.
> Always add /metrics endpoint

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/templates/rollout-service.yaml
- pkg/setup/health.go
- pkg/setup/setup.go
- pkg/setup/setup_test.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/cmd/server_test.go
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/service/service.go
- services/rollout-service/pkg/service/service_test.go
This MR adds a dedicated setup for health checking of background tasks. This currently the smallest possible setup but every background job has to mark itself ready to make the service report itself ready as a whole. The readiness status is currently never invalidated.
> Add dedicated setup for health checking

- services/cd-service/Buildfile.yaml
- services/frontend-service/Buildfile.yaml
- services/rollout-service/Buildfile.yaml
This is a first step to simplify our CI.
It also fixes a bug where the integration test do not find the right docker image to test.
> Always build all services

- go.sum
- pkg/setup/health.go
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/notifier/subscriber.go
- services/rollout-service/pkg/notifier/subscriber_test.go
- services/rollout-service/pkg/service/service.go
- services/rollout-service/pkg/service/service_test.go
- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
The new retry mechanism is implemented in the HealthReporter.Retry function. This function retries the function a few times with randomized backoff until the context is cancelled or the number of retries is exhausted. This is necessary because the grpc stream sometimes disconnect when their pods get restarted. Before this change the reconnect logic was reinplemented in multiple places and not consistent. This change adds a consistent method for that and introduces it to various jobs. This also gets rid of several warning logs.
> Add a unified retry mechanism for background tasks

- charts/kuberpult/templates/rollout-service.yaml
When using an empty dora token ( which is totally valid if not using this optional feature ), then the key will not be rendered in the secret which breaks the rollout deployment. By quoting the value, we ensure that keys do get removed even when they are empty.
> Fix: empty dora token break rollout service deployment

- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
I noticed that this line was missing:
```
hr.ReportReady("consuming")
```
However, writing a good test with the current setup turned out to be tricky, so I improved that and also found another bug that can happen in very rare edge cases ( app gets deleted between two reconnects ).
> Fix readyness reporting for the kuberpult event consumer

- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/metrics/metrics.go
- services/rollout-service/pkg/metrics/metrics_test.go
The rollout service processes metrics async. That means, if the check happens too fast we get the wrong result. This MR adds a `done` function that syncs the testing with the processing.
> Fix race condition in rollout-service metrics

- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx
- services/frontend-service/src/ui/Pages/Home/Home.tsx
- services/frontend-service/src/ui/Pages/Locks/LocksPage.tsx
- services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.tsx
- services/frontend-service/src/ui/Pages/Releases/ReleasesPage.tsx
- services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
- move TopAppBar from outside main content router to inside it
- add props to TopAppBar to allow toggling the display of the app and
team filters
- hide these filters on the locks page
> SRC-K0RM01: improve UX for app and team filters (#1033, #1034)

- .github/workflows/integration-tests.yml
* main was only fetched for PR for fallback version logic
* that logic is gone, so no need to fetch the main branch for a PR at
all
> fix(i-test): remove fetching main

- services/frontend-service/src/setupTests.ts
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/button/ExpandButton.test.tsx
- services/frontend-service/src/ui/components/button/ExpandButton.tsx
- services/frontend-service/src/ui/components/button/button.scss
- services/frontend-service/src/ui/components/dialog/ConfirmationDialog.scss
- services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx
- services/frontend-service/src/ui/components/dropdown/dropdown.tsx
Adds a new button "Deploy only" that pops up when the user clicks the dropdown.
This makes it easier for users to deploy without creating a lock. But the default is still to create a lock with every manual deployment.
> UI: Lock without deploying

- services/frontend-service/pkg/handler/release.go
- tests/integration-tests/release_test.go
release endpoint now returns http/409 instead of http/200 if a manifest already exists
> fix(release): if a release already exists, return http/409 Conflict (SRX-627DCD)

- services/frontend-service/pkg/handler/release.go
- tests/integration-tests/release_test.go
We only want to return 409 if the provided yaml contents differ from the previously uploaded ones. This will be merged only once that check is in place.
> Revert "fix(release): if a release already exists, return http/409 Conflict (SRX-627DCD)"

- docker-compose-earthly.yml
- docker-compose.yml
When running locally, we usually have a local repository, so we do not need to wait long for the repository to respond.
Effectively this changes the timeout from 1 minute to 3 seconds.
Reference: SRX-976IRJ
> Reduce network timeout for local setup

- services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
- services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
- services/frontend-service/src/ui/components/ProductVersion/__snapshots__/ProductVersion.test.tsx.snap
Bug was noticed where only the first tag in the list was every displayed in dropdown
Two screenshots showing different tags displayed
REV: DSN-FE1RG6
> Fix dropdown to display the selectedTag

- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/service/broadcast_test.go
The `ev.Version` might be nil in some cases.
> Fixed an NPE in applyArgoEvents

- Earthfile
The script `argocd-kuberpult.sh` already waits for the git server to be ready.
> Remove redundant wait condition in integration tests

- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/service/broadcast_test.go
- services/rollout-service/pkg/service/service_test.go
- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
I re-read the code and I think we made a mistake here. The code basically says that we mark applications as successfully deployed even when we don't know the right version yet. That doesn't make sense. We should have complete data here before saying everything is fine.
> Require kuberpult AND argocd version to mark app as deployed

- services/cd-service/pkg/service/tags.go
- services/frontend-service/src/ui/utils/Links.tsx
- fixes error Internal desc = grpc: error while marshaling: proto: Marshal called with nil
- Frontend no longer stuck on loading when there are no apps associated with environment based on a git tag
- also fix prettier warning within Links
> Fix return from endpoint GetProductSummary() for empty Summary

- services/cd-service/pkg/repository/repository.go
The disconnect might get triggered while the push is still running and then segfaults sometimes.
> Move Disconnect to the go func

- pkg/api/api.proto
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/time.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/version.go
- services/cd-service/pkg/service/version_test.go
Currently this relies on the much heavier GetOverview endpoint which is tricky because it slows down the rollout service in wawi. This new endpoint contains exactly what we need and nothing else.
> perf: Add a new simpler protocol for calculating versions in the rollout service

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/templates/ingress.yaml
Closes #1241 
When using `.Values.cd.backendConfig.create` inside the `values.yaml` a `BackendConfig` gets created with
```
healthCheck:
requestPath:  `/health`
```
instead of the new endpoint `/healthz`.
The same holds for `.Values.ingress.iap.enabled`
> fix(chart): Add healthz endpoint to BackendConfig

- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
- Duplicate check now considers app lock removal actions for different applications to be different
- add basic unittests for all the duplicate checks
Reference: https://github.com/freiheit-com/kuberpult/issues/1188
Reference: https://github.com/freiheit-com/kuberpult/issues/1049
> fix: unable to queue lock removal for different apps (SRX-SSGFKY)

- Makefile
In this particular case this caused the build to fail with some invalid syntax error. However, in general, `docker-compose` refers to `v1` of compose, which is deprecated now and probably must be avoided in favor of `v2` with `docker compose` command.
> fix: change `docker-compose` to `docker compose`

- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/Pages/Locks/LocksPage.tsx
- services/frontend-service/src/ui/components/TopAppBar/TopAppBar.scss
- services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
- make application filter visible on locks page
- adjust CSS to prevent filter controls to resize switching between home/app/locks page
- adjust order of top bar elements
- fix "vv" version prefix in top bar
Reference: https://github.com/freiheit-com/kuberpult/issues/1187
> fix: show app filter on the locks page (SRX-1X2H6E)

- services/cd-service/Makefile
- services/frontend-service/Makefile
- services/rollout-service/Makefile
This is not the intended final behvaior; we would like to upload the maximum cache only upon pushedto main. This is merely a test commit.
Edit: added new commits, so now the behavior is correct.
> feat: Add `--max-remote-cache` option to earthly buids

- .github/workflows/release.yml
This fixes an issue were the release of kuberpult did only pushed to
europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult
Now it also pushes to
ghcr.io/freiheit-com/kuberpult
> fix: publish to both docker registries

- infrastructure/earthly/go/Earthfile
- services/cd-service/Earthfile
- services/frontend-service/Earthfile
- services/rollout-service/Earthfile
* Copy only the source files before the `compile` target.
* Changing test files will now not cause the compile target to re-run.
> fix: Copy only source files before compile target

- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- the release endpoint should be idempotent
- however, it did not compare author, message, display version, team and repo correctly (all were compared to the commit_id errorously)
- team also had a wrong path (releaseDir instead of app dir)
- also introduce constants for the field names to minimize typo errors and further inconsistencies
> fix: release endpoint reports conflicts for an idempotent call

- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/components/snackbar/snackbar.scss
- services/frontend-service/src/ui/components/snackbar/snackbar.tsx
- services/frontend-service/src/ui/utils/store.tsx
This is mostly a refactoring, with 2 exceptions:
* It also fixes a react warning about a missing `key` attribute
* It increases the time to show the snackbar (errors/warnings/successes) to 15 seconds instead of 5.
New Snackbar success:
New Snackbar error:
> fix: Refactor Snackbar to not use external libraries

- charts/kuberpult/run-kind.sh
- services/cd-service/pkg/mapper/environments_config.go
- services/cd-service/pkg/service/overview.go
- services/rollout-service/pkg/argo/argo.go
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/versions/versions.go
There were some issues with the rollout-service and how the overview response is used. We were not providing the argo config to each environment. This caused for new apps to be wrongly configured and created improperly (in some cases, not created at all).
> fix: issues in rollout-service overview response

- services/rollout-service/pkg/argo/argo.go
When updating apps that are self-managed, the request to update fails because we are not using the env as prefix as we set it using the normal argo requests. Example: https://argocd.int.wawi.lidl/applications?search=blueprint&appNamespace=argocd&showFavorites=false&proj=&sync=&autoSync=&health=&namespace=&cluster=&labels=
> fix: env prefix for self-manage applications

- pkg/valid/validations.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch_test.go
Here we add logic to `CreateApplicationVersion`, `UndeployApplication`, and `CleanupOldApplicatioVersions` transformers so that there is a separate `commits` directory in the manifest repository that maintains the currently-tracked commits.
The new path has the format `commits/<first two characters of the hash>/<remaining letters of the hash>/applications/<app>/.empty`. It's possible that there will be more than one application in one commit's subtree. The `.empty` file is there so that the path is tracked by Git.
This is a prerequisite for implementing a commit info page in the UI later.
> feat: save commits info in manifest repo

- docker-compose-earthly.yml
- docker-compose.yml
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/config/config.go
- services/rollout-service/pkg/cmd/server.go
* Add support for  environment variable `KUBERPULT_CD_SERVER_SECURE` to enable TLS communication to the cd-service.
> feat: Add TLS support for

- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
Listing the rollout status for each environment can make the tooltip to big in projects with many environments. Instead, we group the rollout status by environment group, which results in much fewer entries. The rollout status is accumulated in the same way as the overall rollout status displayed in the card, i.e. the most important rollout status is chosen.
> feat: Group the rollout status in the release tooltip by env-group

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
> fix: Improve alignment of lock & rollout status in release dialog

- .github/workflows/release.yml
Calls a cloudbuild webhook trigger which renovates the standard-setup dev-environment to include the latest version of kuberpult.
> fix: Automatically renovate the dev-env on new release

- go.mod
- go.sum
- pkg/api/v1/api.proto
- pkg/uuid/uuid.go
- pkg/uuid/uuid_test.go
- services/cd-service/pkg/event/event.go
- services/cd-service/pkg/repository/testutil/testutil.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/git.go
- services/cd-service/pkg/service/git_test.go
- services/frontend-service/src/ui/Pages/CommitInfo/CommitInfoPage.test.tsx
- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.test.tsx
- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.tsx
Adds a new event type "newRelease" and returns the events in the grpc call "GetCommitInfo"
The event is not yet rendered in the UI.
> feat: reading and returning events of type newRelease from GetCommitInfo

- README_DEVELOPERS.md
The current instructions build libgit2 without SSH support, which is required for the service.
> fix: Add libssh2 flag to the build instructions for libgit2

- services/rollout-service/pkg/argo/argo.go
The argo apiClient updateSpec endpoint reports false errors where it states that no application was updated, when after some seconds the watcher detects a modified event. To avoid this, we can directly call the Update endpoint which updates the whole application, not just the spec
> fix: use update call instead of updateSpec

- services/frontend-service/Earthfile
* Set `node` as the default user for the ui image. This solves the permission denied errors on ubuntu when trying to delete files which were generated by the  root user in the container. The `node` user has the same uid (1000) as the default uid for ubuntu users.
> fix: Set node as the default user for the ui image

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml.tpl
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/git.go
- services/cd-service/pkg/service/git_test.go
Introduces a new feature toggle via helm parameter `git.enableWritingCommitData`.
Only if it's set to true, kuberpult will write files in the `/commits`/ directory of the manifest repo. 
Rev: SRX-P6SHU8
> feat: add feature toggle for writing commit data

- charts/kuberpult/templates/rollout-service.yaml
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/revolution/revolution.go
- services/rollout-service/pkg/revolution/revolution_test.go
You can now set the environment variable REVOLUTION_DORA_MAX_EVENT_AGE to a duration like "2h" or "30m" to only send the most recent events to DORA.
> feat: Limit the age of events being sent to DORA

- charts/kuberpult/Makefile
- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/values.yaml.tpl
Add the option to add additional annotations to the `kuberpult-frontend-service`. 
Rev: [DSN-FCTBUB](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-NQPLdkfXUNc4bE9KOiO/STORY/-Np4ZYgecd7kNdYWMnVu/)
Jira: OTOP-734
> feat: Add annotations option to kuberpult-frontend-service helm chart

- services/cd-service/pkg/repository/transformer.go
It is ok if they do not exist, especially during clean-up.
> fix: do not expect /commit directories to always exist

- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
Remove the manual accumulation of commit messages & changes, which makes the transformers easier to understand & debug. It also makes future changes easier to implement.
It slightly changes the commit message for skipped services, making it shorter while still conveing the same information.
> fix: Refactor transformer architecture

- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/git_test.go
This was just a left-over from a merge. We are already doing the same thing in `writeCommitData`.
However, in `writeCommitData` we are correctly checking the feature flag.
> fix: do not create commits if the option is disabled

- pkg/api/v1/api.proto
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch.go
Release Train now run release train to specific commit hash instead of always to latest changes
REV: DSN-BADARR
> fix: Adapt Release train endpoint to take commitHash as optional input

- services/rollout-service/pkg/service/dispatcher.go
we got some errors (especially when restarting the rollout-service) that are indicating the revision is not a valid commit hash, so with this change we add it to the span to allow better debugging.
> fix: Add argoCds revision to span

- Earthfile
- charts/kuberpult/.gitignore
- charts/kuberpult/Chart.yaml.tpl
- charts/kuberpult/Makefile
- charts/kuberpult/run-kind.sh
- charts/kuberpult/templates/_helpers.tpl
- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/templates/rollout-service.yaml
- charts/kuberpult/values.yaml
- tests/integration-tests/cluster-setup/argocd-kuberpult.sh
- use unified .Charts.appVersion
- drop:
* .Values.cd.tag
* .Values.frontend.tag
* .Values.rollout.tag
- You need to replace cd.tag etc, with appVersion. Note that only the SAME version for ALL services is supported!
Reference: SRX-GH80MS
BREAKING CHANGE: removes/replaces helm chart parameters
> fix: BREAKING CHANGE simplify helm chart by introducing .Chart.appVersion

- README.md
Currently the maximum is 20 characters. Check https://github.com/freiheit-com/kuberpult/blob/bca7caa8931f5d5db56026f59545ad9016d78c0e/pkg/valid/validations.go#L48
> fix: Add maximum team name size to the Readme

- services/cd-service/pkg/argocd/reposerver/reposerver.go
- services/cd-service/pkg/argocd/reposerver/reposerver_test.go
The errors from that endpoint are currenlty spamming but it's not an actual issue. The data returned by this endpoint is only informational in the argocd ui.
> fix: Implement GetRevisionMetadata

- .github/workflows/release.yml
Due to #1378 the release workflow fails as Earthly is not installed there, this should fix that.
> fix: add Earthly to release workflow

- services/rollout-service/pkg/argo/argo.go
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/notifier/notifier.go
- services/rollout-service/pkg/revolution/revolution.go
- services/rollout-service/pkg/service/broadcast.go
- services/rollout-service/pkg/service/dispatcher.go
- services/rollout-service/pkg/service/service.go
- services/rollout-service/pkg/versions/versions.go
This is a prerequisite PR for #1396 
Here we address or silence all the errors generated by exhaustruct in the CD service. The decision for whether to address or silence an error was the mere convenience; if a struct initialization seemed too large or too complicated, the error was silenced, otherwise it was addressed.
> chore: initialize all struct in rollout service

- services/cd-service/pkg/argocd/render.go
- services/cd-service/pkg/argocd/reposerver/reposerver.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/event/event.go
- services/cd-service/pkg/fs/fs.go
- services/cd-service/pkg/mapper/environments_config.go
- services/cd-service/pkg/repository/credentials.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/testrepository/testrepository.go
- services/cd-service/pkg/repository/testssh/server.go
- services/cd-service/pkg/repository/testutil/testutil.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/environment.go
- services/cd-service/pkg/service/git.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/version.go
This is a prerequisite PR for #1396 
Here we address or silence all the errors generated by `exhaustruct` in the CD service. The decision for whether to address or silence an error was the mere convenience; if a struct initialization seemed too large or too complicated, the error was silenced, otherwise it was addressed.
> chore: initialize all struct in CD service

- pkg/auth/auth.go
- pkg/auth/azure.go
- pkg/auth/dex.go
- pkg/metrics/metrics.go
- pkg/setup/setup.go
- pkg/testfs/testfs.go
- tests/integration-tests/main_test.go
This is a prerequisite PR for #1396 
Here we address or silence all the errors generated by exhaustruct in the CD service. The decision for whether to address or silence an error was the mere convenience; if a struct initialization seemed too large or too complicated, the error was silenced, otherwise it was addressed.
> chore: initialize all struct in `pkg`

- services/cd-service/pkg/service/batch.go
- services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
- services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
- services/frontend-service/src/ui/components/ProductVersion/__snapshots__/ProductVersion.test.tsx.snap
- services/frontend-service/src/ui/components/ServiceLane/EnvSelectionDialog.test.tsx
- services/frontend-service/src/ui/components/ServiceLane/EnvSelectionDialog.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.test.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
- Adding the action of a release train is blocked if there is a release train or deployment already in the list of actions
- Adding the action of a deployment is blocked if there is a release train already in the list of actions
- Add release train to sideBar via Release Train button on Product Version Page
- Only one environment selectable in popup from Release Train button
Example of release train
REV: DSN-3ZRNTG
> feat: Add release train to sideBar

- Earthfile
- infrastructure/earthly/go/Earthfile
Here we add the [`exhaustruct`](https://github.com/GaijinEntertainment/go-exhaustruct) linter to CI. The CI will fail if there are uninitialized struct fields in Go code (excluding test and generated files).
Note that `golangci-lint`, which is currently executed in the CI, does [support](https://golangci-lint.run/usage/linters/#exhaustruct) `exhaustruct`. However, there seems to be an issue when running `exhaustruct` through `golangci-lint`: it doesn't respect the `//exhaustruct:ignore` comments. Therefore, we will stick to running `exhaustruct` separately.
> feat: add `exhaustruct` to CI

- services/rollout-service/pkg/argo/argo.go
- services/rollout-service/pkg/argo/argo_test.go
Creating new apps could fail because we were considering that an application exists in argo if there is at least one application that is self-managed. Also more testing was done to not only check the number of events in the argo processor, but also the types.
> fix: improve check for non-existing argo apps

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/utils/Links.test.tsx
- services/frontend-service/src/ui/utils/Links.tsx
This PR introduces a new button on a release dialog that redirects the user to the new commit page, highlighted  in the picture.
> feat: commit history button

- services/rollout-service/pkg/argo/argo.go
The original error is swallowed at the moment, making it hard to debug.
> fix: include argocd error in error logs

- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/values.yaml
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/config/config.go
The batchClient can timeout with the static value we use. Therefore we should make the timeout configurable in the chart.
> feat: make batchClient timeout configurable

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.test.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
Currently environment colors are inconsistent between the environments page and the release dialogue, as shown below.
| ![](https://i.imgur.com/LchXL1G.png) |
| :---: |
| _Figure 1: the environments page (left) and the release dialogue for an arbitrary app (right). Note that `development` has different colors in the two pages_|
These colors are determined by the `priority` field of `Environment` and `EnvironmentGroup` types; the environments page refers to the `EnvironmentGroup` type, while the release dialogue refers to the `Environment` type. This inconsistency was introduced in #1321.
This PR fixes this by modifying the logic of calculating the CSS style in the `EnvironmentChip` component (which consequently determines the CSS style for the color) to be similar to that of the …
> fix: make colors between `EnvironmentCard` and `EnvironmentChip` consistent

- infrastructure/scripts/create-testdata/create-release.sh
base64 command wasn't setup properly for macOS. make kuberpult-earthly would fail on macOS.
> fix: change base64 input parameter from '-b0' to 'b 0'

- services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
- services/frontend-service/src/ui/utils/Links.test.tsx
- services/frontend-service/src/ui/utils/Links.tsx
This adds a link to the Readme of the current version of kuberpult to version link that is displayed at the top left of the main page.
Before:
Now:
Reference: SRX-7X37EW
> feat: link readme in UI

- services/frontend-service/src/setupTests.ts
- services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
- services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
- services/frontend-service/src/ui/utils/store.tsx
- store.tsx:
* remove getSummary, useDisplaySummary, useSummary, updateSummary,
GetSummaryResponse
* those all use one global store for one summary, thus the summary
would not be usable from different component at the same time
* also they tightly coupled with UI (snackbar, loading state) which is
break separation
- ProductVersion.tsx:
* separate the state of product version into two clear booleans
instead of ambiguous displaySummary/response.summaryReady):
- showSummary: should a product version be shown at all?
- summaryLoading: is the version info still loading?
* rename tag change handler to onChangeTag (from non-obvious
openClose)
- also remove superfluous onSelect handler
- also dont try to load summaries here -- updating the search params
will take care of that already, dont …
> fix: productversion cleanup (SRX-AX9683)

- infrastructure/scripts/create-testdata/Readme.md
- infrastructure/scripts/create-testdata/create-environments.sh
You no longer need to copy the environments inside the test_data_template folder into the manifest repo and push the changes. Kuberpult now receives all environment data and configurations through the rest endpoint, by running the new create-environments.sh script
> feat:  generating environments for local test data is done through rest endpoint

- services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
- services/frontend-service/src/ui/components/dropdown/dropdown.tsx
- services/frontend-service/src/ui/components/textfield/__snapshots__/textfield.test.tsx.snap
- services/frontend-service/src/ui/components/textfield/textfield.scss
- services/frontend-service/src/ui/components/textfield/textfield.test.tsx
- services/frontend-service/src/ui/components/textfield/textfield.tsx
* get rid of floating label transitions
* rename `floatingLabel` parameter to better reflect what it does
Comparison:
* Before  
* After
Rev: SRX-53N7TA
> feat: remove use of MDCTextField in top bar

- services/cd-service/pkg/repository/transformer.go
When previous or next commit id is provided but kuberpult does not find the folder for those commits, previously we were throwing an error. Now we simply log a warning and move on.
> fix: warning when can't find prev or next commit ID

- services/cd-service/pkg/argocd/render.go
- services/cd-service/pkg/repository/repository.go
A first look at profiling data indicates that the rendering of the root apps takes quite a lot of time. This adds more detailed traces for the rendering.
> fix: add tracing for root app rendering

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/queue.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/testssh/server.go
Theoretically we could end up in a situation where we are trying to fit an infinite amount of commits in one push. That is probably not an ideal thing to do. There should be a limit on this, especially in environments with high concurrency.
This change adds a new config option `.git.maximumCommitsPerPush` to the helm chart that is used as an upper limit for the number of commits per push.
> feat: limit number of batched commits per push

- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/values.yaml
- docker-compose-earthly.yml
- pkg/api/v1/api.proto
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/version.go
- services/cd-service/pkg/service/version_test.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/config/config.go
- services/frontend-service/pkg/handler/applications.go
- services/frontend-service/pkg/handler/grpc.go
- services/frontend-service/pkg/handler/handle.go
- services/frontend-service/pkg/handler/release.go
- services/frontend-service/pkg/interceptors/interceptors.go
- services/rollout-service/pkg/versions/versions_test.go
* add new endpoint `/api/application/<app>/release/<release>/manifests`
* `/api` is protected via IAP by default
* set `KUBERPULT_API_ENABLE_DESPITE_NO_AUTH=true` to disable IAP protection (only recommended for local dev)
Rev: SRX-MJL1MD
> feat: implement endpoint to retrieve manifests

- services/frontend-service/package.json
Note that the selected versions are the currently installed ones.
So effectively, this should not change anything.
> fix: use fixed version for msal packages

- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
If next and prev commits were invalid, they could end up crashing cd-service (i.e id = 1)
> fix: verify validity of next and prev commit IDs

- services/frontend-service/src/ui/Pages/CommitInfo/CommitInfoPage.scss
- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.scss
- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.test.tsx
- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.tsx
* removed beta header
* added (i) info icon
* added tooltips for next/prev commit
* Table styling: adapted with of columns and border
* Improved "\n" rendering in commit message
New:
Old:
> fix: Render CommitInfoPage nicer

- services/cd-service/pkg/repository/transformer_test.go
the test had both an env lock and an app lock, so it wasn't that clear which was necessary. The test is now split up into 2 tests: one with only an app lock and one with only an env lock.
Still, even more tests are needed, specifically for https://github.com/freiheit-com/kuberpult/issues/1486
Also slightly formatted an error message.
> fix: refactor tests to be more specific

- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
the context was used with a different type on accident, so metrics were effectively always disabled
> fix: repair datadog metrics

- pkg/sorting/sorting.go
- pkg/sorting/sorting_test.go
- services/cd-service/pkg/mapper/environments_config.go
- services/cd-service/pkg/repository/transformer.go
The ID of events written to the /commits/ directory were nondeterministic, because we iterate over a map. This sorts the keys of the map before iterating.
> fix: stabilize order of events by sorting the manifests

- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.scss
- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.tsx
Now it looks like this when there is no commit linked:
When only the next commit is linked:
When only the previous commit is linked:
The tooltip is shown whenever the user hovers over the (i) symbol.
> fix: explain missing next/previous buttons better

- go.mod
It was already using docker images versioned 1.21.
> chore: upgrade go to 1.21 consistently

- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
- services/cd-service/policy.csv
- For RBAC, group to role mapping is supported
REV: DSN-PKCOP2
> feat: Add paring for groups in policy.csv

- pkg/auth/rbac.go
> fix: Allow RBAC policy to contain empty Lines

- .github/workflows/execution-plan-pr.yml
- .github/workflows/execution-plan-snippet-earthly.yml
- Earthfile
- infrastructure/docker/builder/Makefile
- infrastructure/docker/git-ssh/Makefile
- infrastructure/earthly/go/Earthfile
- services/cd-service/Makefile
- services/frontend-service/Makefile
- services/rollout-service/Makefile
This PR includes the following:
* Do not save built images locally when running in the CI.
* Cancel stale commits' runs when a new commit is pushed.
* Install docker with apt in integration tests instead of earthly installing it every time.
> fix(ci): Optimize CI performance

- pkg/auth/dex.go
- services/frontend-service/pkg/cmd/server.go
- The dex service is called `kuberpult-dex`
- The dex routes are now added to the mux which is served -> before they were implicitly added to `http.DefaultServeMux` but the mux which was served was `http.NewServeMux()`
Now when you try to access any of
```
"/environments",
"/environments/",
"/environment-groups",
"/environment-groups/",
"/release",
```
if `c.DexEnabled` you should get forwarded.
For setup of the values.yaml (I only paste dex-relevant stuff, of course you'd also need a manifest repo connected etc.):
```YAML
auth:
dexAuth:
baseURL: https://kuberpult.example.com
clientId: sample-id-kuberpult-dex
clientSecret: sample-secret-kuberpult-dex
enabled: true
installDex: true
policy_csv: |
p, role:Developer, CreateLock, *:*, *, allow
g, your-github-org:your-github-team, …
```
> fix(dex): Add correct dex service name and mux

- infrastructure/earthly/go/Earthfile
- trivy/Earthfile
* Using shared cache can consume a large amount of disk space because the buildkit creates a copy fof the cache mount for each concurrent build. If multiple builds are triggered at the same time then it consumes all the remaining disk space available and the buildkit will crash.
> fix(ci): Disable cache sharing between builds

- charts/kuberpult/Chart.yaml.tpl
Dex only supports machine to machine auth from `v2.38.0` see:
https://github.com/dexidp/dex/releases/tag/v2.38.0
In my eyes it makes sense to directly upgrade to latest (as of now `v2.39.1`), as it will probably be used more and more once #1554  is merged.
The aligning version of the chart would be `0.17.1` : https://github.com/dexidp/helm-charts/releases
For testing:
```shell
#!/usr/bin/env bash
KUBERPULT_URL="https://kuberpult.com"
TOKEN="$(gcloud auth print-access-token)"
ACCESS_TOKEN_JSON=$(curl -X POST "${KUBERPULT_URL}/dex/token" -H "Content-Type: application/x-www-form-urlencoded" --user kuberpult-dex:kuberpult-dex-secret --data-urlencode "connector_id=google-oidc" --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" --data-urlencode "scope=openid email …
```
> chore(dex): upgrade dex version so it supports machine-machine auth

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml
- docker-compose-earthly.yml
- docs/database.md
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/db.go
- services/cd-service/pkg/repository/db_test.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/service/git.go
While we are still implementing the database, this feature toggle allows operators to already write the "ESL" (event sourcing light) table.
This is useful for storing the historical data already, and it can be used as a proof that the database setup works, without degrading performance by writing lots of data to lots of tables and also writing to the manifest repo at the same time.
Writing to the manifest repo will later be separated into its own service.
> feat: allow writing to only the esl table

- cli/cmd/kuberpult-client/main.go
- cli/pkg/cli_utils/repeated_types_test.go
- cli/pkg/cmd/cli.go
- cli/pkg/cmd/handlers.go
- cli/pkg/cmd/parsing.go
- cli/pkg/cmd/parsing_test.go
- cli/pkg/kuberpult_utils/auth_params.go
- cli/pkg/release/http.go
- cli/pkg/release/http_test.go
- cli/pkg/release/parsing_test.go
- cli/pkg/release/release.go
Here to add two functionalities for the Kuberpult CLI:
- ability to talk to an arbitrary Kuberpult URL (the `--url` flag)
- reading authentication information from the user (the `--author_name` and `--author_email` flags, the `KUBERPULT_IAP_TOKEN`)
> feat(cli): allow CLI to talk to arbitrary Kuberpult instances

- go.mod
- go.sum
This upgrade resolves [CVE-2024-21661](https://github.com/argoproj/argo-cd/security/advisories/GHSA-6v85-wr92-q4p7)
> chore: Update argo-cd to v2.9.9

- go.mod
- go.sum
This resolves [CVE-2024-31989](https://github.com/argoproj/argo-cd/security/advisories/GHSA-9766-5277-j5hr)
> chore: Upgrade argocd to v2.9.15

- charts/kuberpult/templates/rollout-service.yaml
- charts/kuberpult/values.yaml
- services/frontend-service/pkg/cmd/server.go
- services/rollout-service/pkg/cmd/server.go
The fix in https://github.com/freiheit-com/kuberpult/pull/1628 was only fixing the server side part but not the client-side problem.
> fix: allow configuring the grpc recv message size for grpc clients

- database/migrations/sqlite/1714726277027648_events.up.sql
Migrations fail if they have to be run again because this index already exists
> fix: check if index does not already exist

- database/migrations/sqlite/1716384616708554_deployments.up.sql
- pkg/db/db.go
- pkg/db/db_test.go
- pkg/testutil/testutil.go
- services/cd-service/pkg/repository/repository.go
There were three issues:
1) Querying a deployment did not handle NULL for "releaseVersion" field
2) Custom migration called "GetEnvironmentApplicationVersion" which queried the DB, not the repository
3) The migration script for postgres had a syntax error ("NULLABLE" instead of "NULL")
> fix(db): handle NULL in deployments query and deployments migration

- charts/kuberpult/templates/manifest-repo-export-service.yaml
- charts/kuberpult/tests/charts_test.go
- services/manifest-repo-export-service/pkg/cmd/server.go
this fixes missing env vars,
adds chart tests
and handles the logging initialization better.
The logging with `fmt.Printf` did not work on kubernetes, so we now wrap the whole "Run" function into the logger.
> fix(db): add missing env vars for export-service

- charts/kuberpult/templates/manifest-repo-export-service.yaml
The manifest-repo-export-service has no endpoints at all, so it also does not need probes.
The probes were essentially broken in kubernetes.
> fix(db): remove probes

- .gitignore
Background: Some IDEs run into errors when processing the go modules. The workaround is to run "go mod vendor", which creates this directory.
Ref: SRX-L070MM
> chore: add vendor to gitignore

- database/migrations/postgres/1717749007994908_releases.up.sql
- database/migrations/sqlite/1717749007994908_releases.up.sql
- pkg/db/db.go
- pkg/db/db_test.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/transformer_test.go
This only takes care of the custom migrations for the releases tables. It does not use the table yet, except during startup.
> chore(db): migrate releases table

- pkg/db/db.go
When running custom migrations, if no locks were found on some environment, the db would store this information as 'null'. Now stores an empty list
> fix: null db locks on migrations

- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/repository_test.go
- Previously we were getting the commit of the tag which works for lightweight tags
- For annotated tags was previously only using the ID as a commit but need to reference the target of the tag
> fix(productVersion): correct annotated tag usage when calling git tags

- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch_test.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/version.go
- services/manifest-repo-export-service/pkg/repository/repository.go
- services/manifest-repo-export-service/pkg/repository/transformer.go
The manifest-export service accidentally used the manifest repo to gather data. Now it uses the database.
> fix(db): render argo manifests correctly

- services/cd-service/pkg/repository/repository.go
- The commit for annotated tags was pointing at the commit hash of the tag object 
- Fixed to point at the commit object instead
> fix(productVersion): correct Annotated tag for running release trains

- services/manifest-repo-export-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/cmd/server_test.go
- services/manifest-repo-export-service/pkg/repository/repository.go
manifest-repo-export-service creates a metric that outputs the delay between "last processed event" and "last event that should be processed". Its measured in seconds and is exposed on datadog
> chore(manifest-export-service): expose a metric for esl processing delays

- docker-compose-earthly.yml
Added KUBERPULT_ENABLE_METRICS and KUBERPULT_DOGSTATSD_ADDR environment variables to the docker compose file.
> fix(docker-compose): add datadog env variables to docker compose file

- pkg/db/db.go
- services/manifest-repo-export-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/db/cutoff.go
Use Utc time in all records in database. Also, log warning when processDelay metric is negative.
> fix(db): use UTC times in database

- pkg/db/db.go
- pkg/db/db_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_db_test.go
- services/manifest-repo-export-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/repository/transformer.go
- services/manifest-repo-export-service/pkg/repository/transformer_test.go
This Esl is created in the database. Also, in each release in the database the environment will be deleted from the manifest(actually, a new release with new eslID will be created).
Also, The manifest-export-service will read this esl, and delete environment directory in the git repo.
> feat(ESL): Esl for DeleteEnvFromApp to Database

- pkg/api/v1/api.proto
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/config/config.go
- services/frontend-service/pkg/service/config.go
- services/frontend-service/src/ui/App/index.tsx
If the user is not logged in, it needs to be redirected to the `/login` page. 
This is only true if Dex is enabled, thus, we need to check this condition on the frontend service.
> feat: read DexEnabled variable frontend service

- charts/kuberpult/install-kuberpult-helm.sh
- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/templates/manifest-repo-export-service.yaml
- charts/kuberpult/tests/charts_test.go
- charts/kuberpult/values.yaml
- services/cd-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/cmd/server.go
- tests/integration-tests/cluster-setup/argocd-kuberpult.sh
Refactored helm charts.
All options under cd.db. are moved to db. in helm charts.
The dbOption cloudsql is renamed to "postgreSQL".
The sqlite db option is removed.
A helm parameter is added cloudSqlProxyEnabled: true that just adds the proxy
BREAKING CHANGE: helm chart values related to db change. dbOption cloudsql should be renamed to postgreSQL. Options under cd.db should move to db.
> feat(charts): Add an option to enable cloudSqlProxy in helm charts

- .github/workflows/release.yml
Up until now, kuberpult only had "full" releases on GitHub: https://github.com/freiheit-com/kuberpult/releases
This PR changes that to make the distinction between "pre-release" (the new default) and "full release", which will only be set manually.
> chore(ci): Only create pre-releases by default

- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.scss
- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.test.tsx
- services/frontend-service/src/ui/components/CommitInfo/CommitInfo.tsx
Added a select option to select local or utc timezone in events page.
> chore(ui): option to select timezone in events page

- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
The `priority` field on env level is discouraged and not used in the frontend anymore. However, it's still used in the rollout service for deciding whether to send dora events. Also, we discussed whether "production" in the dora sense should include canary environments and came to the conclusion that they should indeed be included.
> feat: use priority from envGroup for dora events, include canary envs

- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/values.yaml
- pkg/auth/dex.go
- pkg/auth/dex_test.go
- services/frontend-service/pkg/cmd/server.go
- services/frontend-service/pkg/config/config.go
- services/frontend-service/pkg/handler/handle.go
- services/frontend-service/pkg/interceptors/interceptors.go
When installing multiple instances of Kuberpult using Dex on the same cluster, there are namespace independent resources such as ClusterRoles that need to have a different naming. 
Dex allows this by setting the fullNameOverride that allows to provide a custom naming for all Dex resources.  Kuberpult needs to make the DexServiceURL configurable and do not use a constant value.
> feat: Add full name override for DEX resources

- charts/kuberpult/values.yaml
This change restores the original behavior of "fullNameOverride", so that there is no breaking change in the helm chart values.
The field was introduced in #1734 where the default value was changed accidentally.
> fix(dex): restore default value for fullNameOverride

- infrastructure/scripts/create-testdata/create-release.sh
Use `sha1sum` to generate the hashes instead of relying on the output of `/dev/urandom`
> fix: Fix random hash generation for create-release.sh on MacOS

- pkg/auth/dex.go
- services/frontend-service/pkg/interceptors/interceptors.go
The formatting for the dex service url was applied twice, thus returning an invalid url.
> fix(dex): do not format the serviceUrl twice

- pkg/db/db.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_db_test.go
- services/manifest-repo-export-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/repository/transformer.go
The original attempt was to read "last_value" of a squence to determine the *next* Primary Key and also write it into the json blob.
This was error prone, and especially failed on the first startup (with an "empty" sequence).
This PR changes this approach. It was necessary to add an interface function to set the transformer ID.
Background: The transformer ID is required for the commit events, so that we can easily find all commit events of one transformer.
> fix(db): replace sequence prediction

- pkg/auth/dex.go
Generates a random string for `state` field on the `/login` request
> fix: Generate APP_STATE on every login request

- services/frontend-service/package.json
- services/frontend-service/src/setupTests.ts
- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/Pages/CommitInfo/CommitInfoPage.test.tsx
- services/frontend-service/src/ui/Pages/CommitInfo/CommitInfoPage.tsx
- services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.test.tsx
- services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx
- services/frontend-service/src/ui/Pages/Home/Home.test.tsx
- services/frontend-service/src/ui/Pages/Home/Home.tsx
- services/frontend-service/src/ui/Pages/Locks/LocksPage.test.tsx
- services/frontend-service/src/ui/Pages/Locks/LocksPage.tsx
- services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.test.tsx
- services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.tsx
- services/frontend-service/src/ui/Pages/ReleaseTrain/ReleaseTrainPage.test.tsx
- services/frontend-service/src/ui/Pages/ReleaseTrain/ReleaseTrainPage.tsx
- services/frontend-service/src/ui/Pages/Releases/ReleasesPage.test.tsx
- services/frontend-service/src/ui/Pages/Releases/ReleasesPage.tsx
- services/frontend-service/src/ui/utils/DexAuthProvider.test.tsx
- services/frontend-service/src/ui/utils/DexAuthProvider.tsx
- services/frontend-service/src/ui/utils/LoadingStateSpinner.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
When Dex is enabled the user is now redirected to a login page if it tries to access Kuberpult.
> feat: Add Login Page when Dex enabled and validate token

- tests/integration-tests/release_test.go
Note that this issue only happens when the DB is enabled. Once the DB will be production ready, this change must be reverted. Will be reverted in: Ref SRX-8D1YX3
> fix(db): workaround for integration test issue

- services/frontend-service/src/ui/utils/DexAuthProvider.tsx
Changes the login page description to `You are currently not logged in. Please log in to continue.`
Adds a random value to the `/login` url to avoid caching when redirecting to DEX.
> fix: Change Login page description and avoid cashing

- charts/kuberpult/values.yaml
- database/migrations/postgres/1720611031124325_event_sourcing_light_failed.up.sql
- database/migrations/sqlite/1720611031124325_event_sourcing_light_failed.up.sql
- pkg/api/v1/api.proto
- pkg/db/db.go
- pkg/db/db_test.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/service/esl.go
- services/cd-service/pkg/service/esl_test.go
- services/frontend-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/cmd/server.go
Whenever the manifest-export service fails to process and esl, it will save it in the failed esls table and skip it.
There's a new Endpoint in cd-service/frontend-service which Gives the list of last 20 failed esls.
> feat(cd-service): store Failed Esl Events

- go.mod
- go.sum
Patches https://github.com/argoproj/argo-cd/security/advisories/GHSA-jmvp-698c-4x3w
> chore: Upgrade argo-cd to v2.9.20

- pkg/db/db.go
- pkg/db/db_test.go
- pkg/db/transactions.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer_db_test.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/batch_test.go
- services/cd-service/pkg/service/environment.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/version.go
- services/manifest-repo-export-service/pkg/repository/repository.go
- services/manifest-repo-export-service/pkg/repository/transformer_test.go
- tests/integration-tests/release_test.go
By default, all transactions are now retried 3 times.
This also removes writing the argo apps from the cd-service (if the db is enabled), because the manifest-repo-export service already takes care of that.
Another change is to wrap all errors from the database, and unwrap TransformerErrors accordingly in ProcessBatch, so that we have both detailed error messages (wrap) and correct return codes (unwrap).
Ref: SRX-4CJW8O
> fix(db): retry all transactions by default

- services/rollout-service/pkg/argo/argo.go
Before, we added a diff exclusion for the sync policy in the applications. Turns out the diff needs to be referenced from the app spec instead of from the object itself.
> fix: change allowUnexported for updating Argo apps

- services/cd-service/Buildfile.yaml
- services/cloudrun-service/Buildfile.yaml
- services/frontend-service/Buildfile.yaml
- services/rollout-service/Buildfile.yaml
- remove apiVersion, as it is only in one Buildfile and thus seems used
- remove kind, as it is only in one Buildfile and thus seems used
- remove metadata.name, as it is not in all Buildfiles and thus seems used
- remove metadata.tier, as it is not in all Buildfiles and thus seems used
- remove metadata.version, as it is not in all Buildfiles and thus seems used
- remove metadata.builder, as it is not in all Buildfiles and thus seems used
> fix(chore): clean up buildfiles

- services/frontend-service/src/ui/components/dropdown/dropdown.scss
- services/frontend-service/src/ui/components/dropdown/dropdown.tsx
Aligned the team filter buttons and also made the Clear button white for consistency purposes 
BEFORE:
AFTER:
Ref: SRX-7KZ8HP
> fix: Align the team filter buttons

- services/frontend-service/src/ui/components/LockDisplay/LockDisplay.scss
- services/frontend-service/src/ui/components/LockDisplay/LockDisplay.tsx
- services/frontend-service/src/ui/components/LocksTable/LocksTable.scss
- services/frontend-service/src/ui/components/LocksTable/LocksTable.tsx
Now every column where there is the possibility to have a very long value (Environment, Lock Message, Team and Application)  is limited to a width and height of 15vw and 5vw in case of overflow a scroll will appear. This makes so the rest of the width is redistributed by the other flex box elements.  
BEFORE:
AFTER:
Ref: SRX-7KZ8HP
> fix: Render long lock messages nicer

- charts/kuberpult/templates/ingress.yaml
- charts/kuberpult/tests/charts_test.go
- charts/kuberpult/values.yaml
- docs/ingress.md
Ref: SRX-XCZB2E
You can now select which parts of kuberpult
you want to expose in the ingress.
BREAKING CHANGE:
In order to get the same behavior as before, set
ingress.allowedPaths.oldRestApi: true
ingress.allowedPaths.restApi: true
ingress.allowedPaths.dex: true
ingress.allowedPaths.ui: true
Recommendation: Only allow paths that are required for your setup.
> feat: allow disabling ingress paths

- services/manifest-repo-export-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/repository/transformer.go
Group locks do not really need to be handled in the manifest-export, because a group lock is just a list of locks for multiple envs, meaning the cd-service creates separate events for each one.
Ref: SRX-KNBOC7
> feat(db): handle group locks

- pkg/db/overview.go
Upon overview recalculation, the team locks were being added to the app locks. We fix this.
Ref: SRX-QMIIYB
> fix: team locks overview

- services/frontend-service/Earthfile
- services/frontend-service/Makefile
- services/frontend-service/package.json
now we have eslint-check/eslint-fix and scss-check/scss-lintlint
Ref: SRX-KNBOC7
> chore: renaming pnpm scripts to be consistent

- services/frontend-service/src/assets/_variables.scss
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.scss
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.test.tsx
- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
- services/frontend-service/src/ui/components/chip/EnvironmentGroupChip.tsx
- services/frontend-service/src/ui/components/chip/chip.scss
Ref: SRX-KNBOC7
This renders app locks on the main page with a orange-ish background color, as part of the service lane header (where the app name appears on the home page). This was done to make locks more obvious.
Also added tooltips to the app name and team name.
Before:
Now:
> feat(ui): Display app locks more prominently

- docs/database.md
> feat(db): Update database documentation

- cli/pkg/locks/app_lock_parsing.go
- cli/pkg/locks/env_lock_parsing.go
- cli/pkg/locks/group_lock_parsing.go
- cli/pkg/locks/lock.go
- cli/pkg/locks/team_lock_parsing.go
Only the team locks are fully migrated to the new /api endpoint. Env, app and group locks are still on the old path, while the team locks are only on the /api. As such, there is no doubt on which endpoint to use on each case, so no flag is necessary.
Ref: SRX-QMIIYB
> fix(cli): removed use dex auth flag from locks

- cli/pkg/cmd/cli.go
- cli/pkg/cmd/handlers.go
- cli/pkg/locks/env_lock_parsing.go
- cli/pkg/locks/group_lock_parsing.go
- cli/pkg/locks/group_lock_parsing_test.go
- cli/pkg/locks/lock.go
> feat(cli): delete group locks

- services/manifest-repo-export-service/pkg/repository/transformer.go
- tests/integration-tests/cluster-setup/argocd-kuberpult.sh
- tests/integration-tests/cluster-setup/setup-cluster-ssh.sh
- tests/integration-tests/cluster-setup/setup-postgres.sh
- tests/integration-tests/rollout_test.go
* Restore rollout-tests that were disabled until the migration to the export-service.
* Improve stability of the integration tests
Ref: SRX-QVB8S7
> fix(ci): Restore rollout tests

- services/rollout-service/pkg/argo/argo.go
- services/rollout-service/pkg/argo/argo_test.go
We need a unit-test for this case plus the AllowUnexported does not guarantee the exclusion. There is a package called `cmpopts` that gives exactly what we want.
Ref: SRX-87V1VH
> fix: add option for ignoring sync policy in argo request

- charts/kuberpult/templates/ingress.yaml
- charts/kuberpult/tests/charts_test.go
The syntax used in the ingress does not work with nginx ingresses. As I understand the routing a simple Prefix routing should do the job here.
Ref: SRX-87V1VH
> fix: use prefix match instead of implementation specific path

- pkg/db/cutoff.go
- pkg/db/cutoff_test.go
- services/cd-service/pkg/repository/repository.go
- services/manifest-repo-export-service/pkg/cmd/server.go
If we were previously running with `db.writeEslTableOnly=true`, but now are running with `db.writeEslTableOnly=false` (which is the recommended way to enable the database), then we would have many events in the event_sourcing_light table that have not been processed - possibly over days or weeks. We must not apply events that are that outdated!
So, we write the current transformer to the cutoff, so it doesn't get processed, when we are using only the esl table
Ref: SRX-KNBOC7
> fix(db): write to cutoff table if writeEslTableOnly=true

- cli/pkg/release/http.go
- cli/pkg/release/http_test.go
- cli/pkg/release/parsing.go
- cli/pkg/release/parsing_test.go
- cli/pkg/release/release.go
- pkg/api/v1/api.proto
- pkg/db/db.go
- pkg/db/overview.go
- pkg/db/overview_test.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/service/batch.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
- services/frontend-service/pkg/handler/commit_deployments_test.go
- services/frontend-service/pkg/handler/release.go
- services/manifest-repo-export-service/pkg/repository/transformer.go
- services/manifest-repo-export-service/pkg/repository/transformer_test.go
Ref: SRX-LUOQKA
- Create Release endpoint now accepts is_prepublish flag.
- prepublish releases are not shown in the overview
- prepublish releases are skipped during cleanup process
- a new flag is added to the cli for creating prepublish releases
> feat(cd-service): accept prepublish releases

- services/rollout-service/pkg/argo/argo.go
- services/rollout-service/pkg/argo/argo_test.go
Currently all of the teams need to be specified if we want to have the self managed applications in one project. However, this is not extendable at all. Instead, we should have an all option (marked as `*`).
Ref: SRX-SC9GBF
> feat: Add  as an option for the self managed apps

- charts/kuberpult/templates/_helpers.tpl
- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/templates/frontend-service.yaml
- charts/kuberpult/templates/ingress.yaml
- charts/kuberpult/templates/manifest-repo-export-service.yaml
- charts/kuberpult/templates/rollout-service.yaml
- charts/kuberpult/tests/charts_test.go
- charts/kuberpult/values.yaml
Ref: SRX-BUFHA5
BREAKING CHANGE: `rollout.podAnnotations` in helm charts is moved to `rollout.pod.annotations`. Now we have these parameters:
[frontend|cd|rollout|manifestRepoExport].pod.annotations
[frontend|cd|rollout|manifestRepoExport].service.annotations
ingress.annotations
> chore(charts): consistent pod annotations

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
This enables the deploy button in the release dialog only if the same version is not already deployed on the given environment.
Ref: SRX-78FWXB
> fix(ui): Disable deploy button if it is a no-op

- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/service/overview.go
* Pass the context to the OverviewServiceServer and use it in `update` function for correct logging.
Ref: SRX-GWLFAS
> fix: Pass context to OverviewServiceServer

- database/migrations/postgres/1726064901745858_transaction_timestamps.up.sql
- database/migrations/sqlite/1726064901745858_transaction_timestamps.up.sql
- pkg/db/db.go
- services/manifest-repo-export-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/repository/repository.go
We need to store the relation between commit hash (repo state) and cd-service transaction timestamp (database state), so that we have a 1 to 1 temporal relation between database state and repository state. 
Ref: SRX-R7B9VQ
> chore: store relation between commit hash and transaction timestamp

- charts/kuberpult/run-kind.sh
This fixes the issue where the rollout-service could not communicate with argo cd (permission denied). It has actually nothing to do with permissions, the project was just misconfigured.
Ref: SRX-78FWXB
> chore: enable argo cd to use the development cluster in run-kind

- services/manifest-repo-export-service/pkg/cmd/server.go
This is just a quick-fix, in the future we will make this configurable via helm chart.
For now the committer is always "kuberpult".
Ref: SRX-VESFP9
> fix: write same committer to git as in cd-service

- infrastructure/scripts/create-testdata/create-release.sh
The random value in the testdata is not guaranteed to be unique, so we add the release number which is unique
and it is also helpful for the human observer.
Ref: SRX-78FWXB
> chore: make it easier to see release versions in test data

- services/frontend-service/package.json
- services/frontend-service/pnpm-lock.yaml
- services/frontend-service/src/ui/components/EnvironmentConfigDialog/EnvironmentConfigDialog.test.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
Ref: SRX-4ZO090
* Most of the warnings were because of deprecated `testing-library/react` and `react-use-sub` packages. Some changes were needed after updating the packages.
* One of the warnings was because of the `console.error` in the code, which I mocked it to not write anything in the tests.
> chore(ui): remove warnings in tests

- .github/workflows/execution-plan-snippet-earthly.yml
- .github/workflows/execution-plan-snippet.yml
- .github/workflows/integration-tests.yml
- .github/workflows/release.yml
- .github/workflows/trivy-scan.yml
- Earthfile
- Makefile
- README.md
- charts/kuberpult/Chart.yaml.tpl
- charts/kuberpult/Earthfile
- cli/Makefile
- services/cd-service/Earthfile
- services/cd-service/Makefile
- services/cloudrun-service/Earthfile
- services/cloudrun-service/Makefile
- services/frontend-service/Earthfile
- services/frontend-service/Makefile
- services/manifest-repo-export-service/Earthfile
- services/manifest-repo-export-service/Makefile
- services/rollout-service/Earthfile
- services/rollout-service/Makefile
Ref: SRX-82AUA2
New Images on PRs and Main have `pr-` and `main-` prefix before their image tag.
BREAKING CHANGE: The old github registry will not be used anymore. Use Google registry instead.
> chore(registry): remove unnecassary github registry

- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
- services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/utils/store.tsx
This fixes an issue where the UI does not render anything if it cannot find a release.
Instead of "giving up", kuberpult now logs the issue in the console.
Ref: SRX-4WQBET
> fix(ui): Continue rendering if a release was not found

- pkg/db/db.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/release_train_prognosis.go
in db.go:
- EnvironmentFromRow extract maping from row to db environment object
- remove extra closeRows calls in DBSelectEnvironment, already handled by
defer
- add a DBSelectEnvironmentsBatch to query for multple environments at once
* currently hardcoded to bail at more than 1024 environments
* would need paging for more
in repository.go:
- use DBSelectEnvironmentsBatch instead of looping over queries
in transformer.go:
- fetch environment configs as early as possible
- reuse those configs e.g. in prognosis
> fix(db): get all environment configs at the start of a release train

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml
- docker-compose.yml
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
This introduces a new helm option "cd.backendConfig.disableQueue`. When true, the cd-service processes incoming requests in parallel.
> fix: allow disabling the request queue

- services/cd-service/pkg/repository/repository.go
- services/manifest-repo-export-service/pkg/repository/repository.go
While the helm parameter argocd.generateFiles=false technically worked, it would still request a lot of data that is not necessary. With this change, we reduce the number of queries to the database for the case argocd.generateFiles=false.
> fix(db): Do not write argo apps if disabled

- pkg/db/cutoff.go
- pkg/db/db.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/service/commit_deployment.go
- services/cd-service/pkg/service/version.go
- services/manifest-repo-export-service/pkg/repository/repository.go
- services/manifest-repo-export-service/pkg/repository/transformer.go
> fix: pass context along to avoid disconnected spans

- pkg/db/db.go
- pkg/db/overview.go
- pkg/db/overview_test.go
- services/cd-service/pkg/argocd/reposerver/reposerver_test.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_db_test.go
- services/cd-service/pkg/repository/transformer_test.go
- services/cd-service/pkg/service/batch_test.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
Ref: SRX-09Z4A6
* Removed `ForceOverviewRecalculation`. Instead updated overview accordingly when creating a new environment or a new undeployVersion.
> fix(cd-service): Remove overview cache recalculation, update overview  on create environment and undeployVersion

- docker-compose.yml
- services/cd-service/pkg/cmd/server.go
- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
Ref: SRX-8WMJ13
- When no `KUBERPULT_MINOR_REGEXES` env var provided, The list of minor regexes to use should be empty
- Added a description for minor regexes to the tooltip
> fix(cd-service): empty list of regexes when no regex provided

- pkg/db/db.go
Note that this migration is not technically required. It was just there to provide additional context to the user. It only influences the UI, not what was actually deployed.
For now, we remove it. The migration itself seems fine, but the dection IF the migration is necessary is flawed, leading the cd-service to potentially clone the git repo, even when it is not necessary. And that is a very costly operation with large git repos.
> fix(db): Do not run deployment migrations

- pkg/db/db.go
- pkg/db/overview.go
- pkg/db/transactions.go
- pkg/db/transactions_test.go
- services/cd-service/pkg/repository/error.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_db_test.go
* The /release endpoint continues even if in an edge case, the app was not found in the overview.
* The postgres error 23505 is now considered retryable. This happens especially in the /release endpoint
> fix: continue if app is not found in overview

- cli/pkg/locks/app_lock_parsing.go
- cli/pkg/locks/app_lock_parsing_test.go
- cli/pkg/locks/env_lock_parsing.go
- cli/pkg/locks/env_lock_parsing_test.go
- cli/pkg/locks/group_lock_parsing.go
- cli/pkg/locks/group_lock_parsing_test.go
- cli/pkg/locks/lock.go
- cli/pkg/locks/lock_test.go
- cli/pkg/locks/team_lock_parsing.go
- cli/pkg/locks/team_lock_parsing_test.go
- cli/pkg/release/http.go
- cli/pkg/release/http_test.go
- cli/pkg/release/parsing.go
- cli/pkg/release/parsing_test.go
- cli/pkg/release/release.go
- cli/pkg/releasetrain/releasetrain.go
- cli/pkg/releasetrain/releasetrain_parsing.go
- cli/pkg/releasetrain/releasetrain_parsing_test.go
- cli/pkg/releasetrain/releasetrain_test.go
There was no option for providing a ci_link in the cli.
Added this parameter as a command line argument to the following commands:
- release
- release-train
- create-env-lock
- create-app-lock
- create-team-lock
- create-group-lock
Also added unit tests to test this feature.
Ref: SRX-G46ZAL
> feat(cli): added ci_link command line argument

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml
- pkg/db/overview.go
- pkg/db/overview_test.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/transformer.go
> chore(cd-service): regularly delete old overview caches

- pkg/db/db.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/service/git_test.go
- services/cd-service/pkg/service/overview_test.go
This reduces the number of queries to the releases table, roughly by a factor of 25 (average number of releases per app).
This also reduces the number of cases where we actually load all the manifests from the releases table.
And it fixes a few tests that had a nil context.
Ref: SRX-LEIHOZ
> fix: reduce number of queries to get releases

- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
Previously the release train to "latest" would consider all apps.
Now it only considers apps that exist (have a release) in the target env.
Ref: SRX-LEIHOZ
> fix: improve "upstream/latest" release trains

- services/frontend-service/pkg/service/batch.go
The formating of the logs was incorrect. The error was not being printed.
Ref: SRX-BJVFRL
> fix(frontend-service): Fixed log format

- pkg/auth/azure_test.go
- pkg/setup/health_test.go
Ref: SRX-AHGZTR
Ref: SRX-TI3JNJ
- TestHealthReporterRetry: There's a background job going on in the ReportHealth function which should be completed before we check the expectations. Sometimes it may be left behind(It's pretty rare). So, if we wait for that and then do the checks, it would solve the problem.
- TestValidateTokenStatic: It seems that we are testing not our code but the code of an underlying library `golang-jwt`. We shouldn't test the error messages that are returned by the library not us.
> fix(tests): fix TestHealthReporterRetry, TestValidateTokenStatic

- services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
When it was rendered at the end, it would not be rendered at all depending on the length of the commit message.
Ref: SRX-8WMJ13
> fix(ui): move minor icon to the start of the title of the release

- pkg/db/db.go
- services/manifest-repo-export-service/pkg/repository/transformer.go
- services/manifest-repo-export-service/pkg/service/git.go
The function `ShouldUseOtherTables` does not make sense in the manifest-repo-export-service, because the whole service is not running, if `ShouldUseOtherTables()==false`.
Ref: SRX-2CSAEK
> fix(db): remove dead code

- cli/pkg/cli_utils/http.go
- cli/pkg/cmd/cli.go
- cli/pkg/cmd/handlers.go
- cli/pkg/cmd/parsing.go
- cli/pkg/cmd/parsing_test.go
- cli/pkg/deployments/deployments.go
- cli/pkg/locks/lock.go
- cli/pkg/release/release.go
- cli/pkg/releasetrain/releasetrain.go
> fix(kuberpult-cli): add timeout to the args

- charts/kuberpult/templates/manifest-repo-export-service.yaml
Altered the mount point of the emptyDir volume for the manifeset-repo-export-service pod.
It now mounts to the home folder so that the service can create the repo from scratch and be the owner.
Altered the size from 10Gi to 30Gi.
The relevant documentation was added to the chart.
Ref: SRX-F26M7C
> fix(charts): manifest-repo-export-service pod now stores manifest repo in an emptyDir volume 

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/templates/manifest-repo-export-service.yaml
- charts/kuberpult/tests/charts_test.go
- charts/kuberpult/values.yaml
- docs/database.md
Ref: SRX-NMC7OD
BREAKING CHANGE: The postgreSQL Database is now required.
The helm-parameter `db.writeEslTableOnly` is not supported anymore.
The helm-parameter `db.dbOption` now only supports the option "postgreSQL", which is now also the default.
See docs/database.md for details.
Note that there is now some "dead code", especially in the cd-service that deals with git. This will be removed later on.
> feat: require database

- docs/database.md
- services/manifest-repo-export-service/pkg/cmd/server.go
The `measurePushes` method sends metrics to datadog about wether the manifest repo export service successfully pushed to git.
This PR makes the service write the metric, as a success, even when there are no pushes.
Ref: SRX-PLAY6B
> fix(manifest-repo-export-service): measure pushes write when nothing to push

- services/cd-service/pkg/service/overview.go
We already had access to all of this information on the GetAppDEtails endpoint, no need to query the database again
Ref: SRX-E9K6SV
> fix: improve app details calculate warnings performance

- .github/workflows/release.yml
As of now we have an issue with rate limiting for trivy. This is a workaround, so that we can easier create releases, even when trivy does not work.
Ref: SRX-2CSAEK
> fix(trivy): run trivy as late as possible

- pkg/db/db.go
- pkg/db/db_test.go
The following columns have lists of strings which are now sorted:
* `environments.applications`
* `releases.environments`
* `all_environments.json`
The column `all_apps.json` was already being previously sorted.
4 new test cases were added for each of the tables testing that string lists are ordered when inserted.
The `all_apps` table had no write and read test suite so a new one was created with the corresponding test case.
Ref: SRX-FEUSCN
> feat(db): string lists inserted into the databse are sorted

- services/cd-service/pkg/repository/transformer.go
Fixes a nil pointer when a manifest for a non-existing environment is submitted in the /release endpoint.
Ref: SRX-QCRRU1
> fix(cd-service): Added new check for non existing env

- pkg/setup/setup.go
- services/rollout-service/pkg/cmd/server.go
The rollout service is crashing and the logs do not provide useful feedback.
This PR adds logs to improve visibility in the kuberpult background task shutdown process.
Ref: SRX-FEUSCN
> fix(rollout-service): improved logging

- services/cd-service/pkg/repository/transformer.go
Collecting metrics for all envs/apps/locks takes significant time, so we add some spans around it.
> fix: add tracing for metrics collection

- pkg/db/overview.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
We already have the number of locks in the overview cache,
so there's no need to calculate it again.
This also removes some dead code.
> fix: Speed up metrics collection by using the overview cache

- services/cd-service/pkg/repository/repository.go
Generating metrics for all apps and all envs can take quite some time.
We previously had some endpoints that directly send the metrics, in order to have the metrics faster. Given how slow the metrics calculations currently are, this is not feasible. We will now send metrics only on the background task "RegularlySendDatadogMetrics".
> fix: only send metrics as background job

- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_db_test.go
- services/cd-service/pkg/repository/transformer_test.go
This is a performance optimization.
We run the metrics every 5 minutes.
With this change, only half the apps will be handled each run.
So effectively this means that the metrics are only updated
every 10 minutes.
> fix: re-enable metrics and send half the metrics each 5 minutes

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/SideBar/SideBar.tsx
- services/frontend-service/src/ui/utils/store.tsx
There were two issues that were fixed:
1) Team locks appeared on all environments, even though it should appear on only one.
2) Team locks could not be deleted.
> fix(ui): deletion of team locks

- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_db_test.go
Note that the create environments endpoint is still recalculating the whole overview cache, which is inefficient. This will be fixed in another PR.
> fix: do not run overview twice when creating environments

- pkg/api/v1/api.proto
- pkg/buf.yaml
- services/frontend-service/buf.yaml
- services/frontend-service/pkg/handler/commit_deployments_test.go
- services/frontend-service/pkg/handler/handle_test.go
This fixes a problem in the frontend service,
where the json.Unmarshal is using the wrong protobuf field.
The problem occured in the frontend-service environments.go
`err := json.Unmarshal([]byte(config[0]), &envConfig)`
> fix: set group properly in the environments table

- pkg/db/db.go
- pkg/db/db_test.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/frontend-service/src/ui/utils/store.tsx
- services/manifest-repo-export-service/pkg/repository/transformer_test.go
- services/manifest-repo-export-service/pkg/service/git_test.go
Before this change, update an existing environment would set the applications column to be empty.
That in turn resulted into GetAppDetails not returning all the deployments.
> fix: create-environment should not overwrite applications

- pkg/db/db_test.go
There were multiple complex queries without unit tests. This PR adds tests to 3 complex queries related to environments.
This PR added a support testing function for testing the `TestReadReleasesWithoutEnvironments ` method.
This method is used for database migrations in case a release is in the database without environments, but with any manifest. Our `DBInsertRelease` method automatically adds any environment that has a manifest to the release's environments list. The new method bypasses the insertion for testing purposes.
Ref: SRX-THO0EO
> fix(db): test complex environment queries

- pkg/db/db.go
- pkg/db/db_test.go
- services/cd-service/pkg/repository/repository.go
There were multiple complex queries without unit tests. This PR adds tests to 3 complex queries related to deployments.
This PR also changes the name of one database method to be more explicit. The naming for the two involved db methods changed as follows:
| Previous Name | Current Name |
|---|---|
| DBSelectAllLatestDeploymentsForApplication | DBSelectAllLatestDeploymentsForApplication  |
| DBSelectAllLatestDeployments | DBSelectAllLatestDeploymentsOnEnvironment |
Ref: SRX-THO0EO
> fix(db): test complex deployments queries

- .github/workflows/trivy-scan.yml
- database/migrations/postgres/1732538194911882_force_overview_recalculation.up.sql
- database/migrations/sqlite/1732538194911882_force_overview_recalculation.up.sql
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer_db_test.go
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
This PR contains several bug fixes:
* When Creating a new environment, previous environments in the overview should not change.
* In GetAppDetails, if we cannot obtain an environment we should ignore it and continue with the others.
* In ReleaseDialog we should get the locks from appdetails. In overview we should show all locks of application.
> fix(cd-service): fix overview calculation when creating a new environment

- .github/workflows/release.yml
The previous trivy PR did not alter the release workflow to use the new cache correctly. This is now fixed.
Ref: SRX-R4I0PO
> fix(ci): release trivy scan

- services/manifest-repo-export-service/pkg/cmd/server.go
The manifest repo sometimes fails to push. In this case we only log the time of the back-off. This PR adds the logging of the error that caused the push to fail along the backoff time.
Ref: SRX-UVTOID
> fix(manifest-repo-export-service): log push failures

- services/cd-service/pkg/service/version.go
The cd-service was parsing the git revision inside a transaction. This meant that if the operation failed we had opened a connection to the database for no reason.
This PR moves this operation outside of the transaction.
> fix(cd-service): removed revision parsing from transaction.

- services/rollout-service/pkg/argo/argo.go
Our `CreateArgoApplication` function created an argo app in the argo grpc api format.
This function creates an ignore differences empty array if there are no ignore differences items.
However, the apps that come from argocd come with this array as nil if there are no ignore differences.
This causes a lot of unnecessary update requests.
This PR corrects this problem.
> fix(rollout-service): fix diff arog app

- services/rollout-service/pkg/service/broadcast.go
In the `applyKuberpultEvent` method of the `Broadcast`'s `appState` we were incorrectly comparing the argocd state with the kuberpult state.
This meant that if argocd had one version deployed, and a request was received from the cd-service (kuberpultEvent) to update a deployment to that same version, we would not update the `appState` to that version, causing a split between the rollout-service's inner state kuberpult version and the real kuberpult version.
The consequence would be that later, we could generate an argo notification to deploy to the earlier version that the rollout service has in its inner state, while both the cd-service "wanted" the more recent one deployed.
> fix(rollout-service): fixed version comparison in broadcast's app state

- services/cd-service/pkg/repository/transformer.go
We currently have no span to measure the performance of DeleteEnvFromApp transformer. This PR adds one.
Ref: SRX-7XFFEN
> fix(cd-service): new span to measure performance of DeleteEnvFromApp

- services/cd-service/pkg/repository/transformer_db_test.go
- services/cd-service/pkg/service/version.go
When merging for Wawi support two sequential exec plans on main failed due to this flaky test.
The test has our usual order of (+want,-got) switched which was fixed.
The test is flaky because the `lastDeployment` gauges have a timestamp for a value which can be different from 0.
This PR only fixes the order of the diff.
> fix(ci): fix flaky test diff

- services/cd-service/pkg/repository/transformer_db_test.go
Ref: SRX-PXQRS5
lastDeployed is a float time difference. It can be anywhere between 0 and 1. For us if it's less than 1 minute is enough.
> fix(cd-service): fix flaky datadog gauge test

- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
When an overview gets created it checks for deployments on environments that belong to an app. This created a particular blind spot:
1. Delete env from app, thus deleting all manifests from all current releases and the environment from the app itself;
2. Add new release on this app with manifest for said environment, which adds the environment back to the app;
3. When the overview gets recalculated the deployment is "reactivated", because we do not delete deployments and the environment is now part of the app again;
This PR adds a check in the overview calculation that checks if the deployment's environment is present in the release's environments list.
Ref: SRX-R9Q5YN
> fix(cd-service): solved problem with overview creation.

- services/rollout-service/pkg/revolution/revolution.go
- services/rollout-service/pkg/revolution/revolution_test.go
The revolution package was lacking unit tests. This PR creates new test cases and fixes a small bug with the test code itself that caused some tests to block/not fail.
We also add a log in the main revolution subscriber for visibility.
Ref: SRX-L5QORI
> fix(rollout-service): revolution tests

- pkg/db/db.go
- pkg/db/db_test.go
- services/cd-service/pkg/service/overview.go
The `GetAppDetails` endpoint collects information about the deployments of an app.
One of these is the latest queued version. Currently the endpoint would evaluate one deployment at a time and, when it was decided to be a valid deployment, the database would be queried for this deployment's latest queued version.
This PR queries the database for all latest deployment attempts. Then when analyzing each deployment it just pulls from this information cached in a map.
This might slow down `GetAppDetails` requests that have no current deployments (since before we would not query the queued versions for invalid deployments). This will translate in improved performance. And in most cases, most apps will have deployments
Ref: SRX-016Y9E
> fix(cd-service): improve get app details deployments

- services/cd-service/pkg/service/overview.go
- services/frontend-service/src/ui/App/index.test.tsx
- services/frontend-service/src/ui/App/index.tsx
- services/frontend-service/src/ui/Pages/Locks/LocksPage.test.tsx
- services/frontend-service/src/ui/Pages/Locks/LocksPage.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
It does not remove the app locks from the overview. See [2182](https://github.com/freiheit-com/kuberpult/pull/2182)
Ref: SRX-JTRV7H
> chore(ui): all app locks from locks page are now accessing the all app locks endpoint

- services/cd-service/pkg/repository/transformer.go
There was a bug where we were writing an empty time into the application log, resulting in locks created around 2025 years ago
Ref: SRX-JTRV7H
> fix: app lock creation date bug

- charts/kuberpult/templates/manifest-repo-export-service.yaml
- database/migrations/postgres/1733938275776162_migrationcutoff.up.sql
- database/migrations/sqlite/1733938275776162_migrationcutoff.up.sql
- docker-compose.yml
- pkg/api/v1/api.proto
- pkg/db/db.go
- pkg/tracing/span.go
- services/manifest-repo-export-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/migrations/migration.go
- services/manifest-repo-export-service/pkg/migrations/migration_test.go
- services/manifest-repo-export-service/pkg/migrations/types.go
- services/manifest-repo-export-service/pkg/migrations/types_test.go
- services/manifest-repo-export-service/pkg/service/git_test.go
- services/manifest-repo-export-service/pkg/service/migration.go
- services/manifest-repo-export-service/pkg/service/migration_test.go
By "custom migrations" we mean those db migrations that can not be solved by plain SQL, so they are implemented in go.
This provides the basic setup to move the custom migrations to the manifest-export-service.
* It creates a new endpoint to accept migrations, however the endpoint is not called yet.
* It provides the setup like reading/writing to the custom_migration_cutoff table
However, this change does not include actually moving the migrations from cd- to export-service. This will be done in a separate PR.
> fix: move custom migrations to manifest-export

- .github/workflows/execution-plan-snippet-earthly.yml
With this change, builds of microservices are not cancelled, only because another microservice failed to build.
The advantage is that we can see issues in service X, even if service Y fails.
> fix(ci): do not cancel builds (WIP)

- .gitignore
The docker.env file is used to supply environment variables to docker compose. This is used for example when testing datadog integrations where we need the datadog api key.
> fix: add docker.env to gitignore

- docker-compose.yml
If the manifest export needs to clone a big manifest repository, it can take longer to start up.
So we increase the retries in docker-compose.
> fix: increase retries in docker-compose

- services/manifest-repo-export-service/pkg/service/migration.go
This bug effectively made the manifest-export-service slower to start up, as it would repeat migrations that were already done on the last startup.
> fix: write correct version after custom migration

- services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
Apps should always have releases.
However, due to bug with deleting apps, some apps have no releases.
For these apps, it was impossible to undeploy them, because the undeploy endpoint expects at least 1 release.
With this change, we add actions for both prepareUndeploy and undeploy into the planned actions.
Ref: SRX-LZZMFQ
> fix(ui): Allow apps without release to be deleted

- pkg/db/db.go
- services/cd-service/pkg/repository/repository_test.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_db_test.go
- services/cd-service/pkg/repository/transformer_test.go
We already queried all releases during the prognosis, now we do not query the latest release again.
This also fixed:
* a bug where deployments ignored team locks
* a bug where the release trains hangs forever, if `cd.maxNumberOfThreads` is 0.
* adapted tests to use the db instead of git
* adapted test that run release train in parallel to work with sqlite (we can't just do multiple transactions with sqlite)
Ref: SRX-M65AQ8
> fix(db): reduce calls to releases tables

- database/migrations/postgres/1737404419146074_git_sync_status.up.sql
- database/migrations/sqlite/1737404419146074_git_sync_status.up.sql
- pkg/db/db_sync_status.go
- pkg/db/db_test.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer_db_test.go
- services/manifest-repo-export-service/pkg/cmd/server.go
cd-service now writes to git_sync_data table upon transformer execution
manifest-export-service now writes to git_sync_data table upon transformer execution or failure
Ref: SRX-IV81DS
> chore: implement sync status on cd-service and manifest export

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/button/ExpandButton.test.tsx
- services/frontend-service/src/ui/components/button/ExpandButton.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
If the environment has a planned deploy then the button will cancel that planned action instead of warning about a duplicate action.
Ref: SRX-3I6YKY
> feat(ui): cancel planned 'deploy' actions

- pkg/api/v1/api.proto
- services/cd-service/pkg/service/overview.go
- services/cd-service/pkg/service/overview_test.go
- services/frontend-service/src/assets/_components.scss
- services/frontend-service/src/ui/Pages/Compliance/CompliancePage.tsx
- services/frontend-service/src/ui/components/Compliance/Compliance.scss
- services/frontend-service/src/ui/components/Compliance/Compliance.test.tsx
- services/frontend-service/src/ui/components/Compliance/Compliance.tsx
Adds a way to select the time frame for which you want to download the deployment history.
Ref: SRX-4I9LE6
> feat: filter deployment history by a time frame

- database/migrations/postgres/1720428454051313_fk_deployments.up.sql
- database/migrations/postgres/1738701911056713_delete_fk_constraints.up.sql
Parallel release trains spawn new transactions. This means that for a release train we will have one outer transaction and N inner transactions (based on the number of parallel processing go routines and number of environments to process). As the outer transaction has not yet been committed, inner transactions will not be able to view the most recent event written to the event_sourcing_light table. This ALWAYS results in a FK violation if anything is deployed by the release train, as the transformer ID that the deployments try to reference does not exist on the current database view of the inner transaction. 
Rolling back the outer transaction causes inner transactions to also be rolled back, so simply removing these fk_constrains works and kuberpult won't be left in an inconsistent state …
> fix(cd): migration to delete foreign key on deployments and deployment history

- services/frontend-service/.prettierrc
The `jsxBracketSameLine` was deprecated in favour of `bracketSameLine` as shown [here](https://prettier.io/docs/options/#deprecated-jsx-brackets).
Ref: SRX-JWS0HZ
> chore: change deprecated prettier rule

- charts/kuberpult/templates/rollout-service.yaml
- services/rollout-service/cmd/server/main.go
- services/rollout-service/pkg/cmd/server.go
- services/rollout-service/pkg/cmd/server_test.go
- services/rollout-service/pkg/service/dispatcher.go
- services/rollout-service/pkg/service/dispatcher_test.go
- services/rollout-service/pkg/service/service_test.go
- services/rollout-service/pkg/versions/versions.go
- services/rollout-service/pkg/versions/versions_test.go
> feat: use db directly from rollout-service

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/button/ExpandButton.test.tsx
- services/frontend-service/src/ui/components/button/ExpandButton.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
Allow canceling planned locks with the buttons changing styles to indicate their behavior.
Ref: SRX-JWS0HZ
> feat(ui): allow canceling planned locks

- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
- services/frontend-service/src/ui/components/button/ExpandButton.test.tsx
- services/frontend-service/src/ui/components/button/ExpandButton.tsx
- services/frontend-service/src/ui/utils/store.test.tsx
- services/frontend-service/src/ui/utils/store.tsx
If an environment is already locked then the lock button will be used to plan removing those locks as well as canceling the plan.
Ref: SRX-92NLH7
> feat(ui): add sensible actions for lock button when already locked

- pkg/db/db_deployments.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
Use the DB instead of the git repo to get the versions deployed at a certain commit hash.
Ref: SRX-GRTE1B
> fix(cd-service): migrate release train by commit hash

- services/cd-service/pkg/service/git.go
- services/frontend-service/pkg/cmd/server.go
- services/manifest-repo-export-service/pkg/service/git_test.go
Use manifest-repo's `GetGitTags` instead of cd-service's
Ref: SRX-SH4OGB
> chore: remove GetGitTags from cd-service

- services/frontend-service/src/ui/components/GitSyncStatusDescription/GitSyncStatusDescription.tsx
- services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
- services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
- services/frontend-service/src/ui/components/RolloutStatusDescription/RolloutStatusDescription.scss
- services/frontend-service/src/ui/components/RolloutStatusDescription/RolloutStatusDescription.tsx
Fixed CSS on rollout/git sync status inside rollout service from:
to:
Also added tooltip descriptions for every Rollout and Git Sync Status:
Ref: SRX-YO3HLA
> feat(ui): New release dialog rollout/gitsync status style and pop-tooltips 

- services/cd-service/pkg/repository/transformer.go
This pulls the call to get the current timestamp from the DB outside of the for loop.
It should be a little more efficient, but since it's just a "select now()" so it should not make a big difference in time spent.
Ref: SRX-E3IK25
> fix: reduce number of calls in DeleteEnvFromApp

- pkg/db/db_sync_status.go
- pkg/db/db_test.go
- services/manifest-repo-export-service/pkg/service/git.go
- services/manifest-repo-export-service/pkg/service/git_test.go
When the git sync status is enabled, we are able to retry events that might have failed on the manifest export service.
When we retry an event, we pickup the failed event, copy it into the event_sourcing_light table, but with a new eslVersion, so that the manifest export service can naturally pick it up.
An issue arises when certain deployments depend on these failed events. The way the manifest export service detects which deployments to write to git is by filtering the deployments table by the deployments that the transformer that is currently being processed has generated. If the event is retried, a new eslVersion is given to the event and we lose the reference to the deployments.
So if, for example, a release train transformer with tID: X fails and gets retried, it gets given another …
> fix(export-service): Update transformer eslversion upon failed esl event retry

- cli/pkg/cmd/handlers.go
- cli/pkg/cmd/parsing.go
- cli/pkg/cmd/types.go
- cli/pkg/release/http.go
- cli/pkg/release/http_test.go
- cli/pkg/release/parsing.go
- cli/pkg/release/parsing_test.go
- cli/pkg/release/release.go
- cli/pkg/sorting/sorting.go
- cli/pkg/sorting/sorting_test.go
- services/frontend-service/pkg/handler/release.go
This dry-run parameter toggles the behavior:
With dry-run, we return the diff of the manifests, instead of creating a new release.
Ref: SRX-J7MZFR
> feat(cli): adding dry-run parameter for release endpoint

- services/manifest-repo-export-service/pkg/repository/repository_test.go
- services/manifest-repo-export-service/pkg/repository/transformer.go
The endpoints for release trains and new releases now only create a commit, if a deployment happened. 
Ref: SRX-YSWDSA
> feat(export-service): avoid empty commits with release trains and create release

- services/frontend-service/pkg/handler/commit_deployments.go
- services/frontend-service/pkg/handler/commit_deployments_test.go
- services/frontend-service/pkg/handler/handle.go
We need to supply the auther headers when invoking a grpc call.
Ref: SRX-WLGQSK
> fix: author headers in publicapi

- charts/kuberpult/templates/cd-service.yaml
- charts/kuberpult/values.yaml
- docker-compose.yml
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/repository.go
- services/cd-service/pkg/repository/transformer.go
- services/cd-service/pkg/repository/transformer_test.go
The goal here is to avoid that only *parts* of a release train are successful.
This introduce a new experimental helm parameter
"cd.experimentalParallelismOneTransaction".
When set to true the release trains to environment groups are changed:
* The go routines (1 per env) now only produce the prognosis (list of versions to be deployed).
* The go routines use a read only transaction.
* Only the requests go routine is applying the changes with a writing transaction.
Ref: SRX-JEU54H
> fix: Run release trains with only one writing transaction

- .github/workflows/execution-plan-pr.yml
- README.md
This changes the github workflow to not run only one action per PR at a time.
Reasoning is that the cancellation via "cancel-in-progress: true" does not work (it does not seem to cancel anything), so this just slows us down. Note that also clicking on "cancel" in the workflow also does not work properly at the moment.
Ref: SRX-JEU54H
> fix: disable github concurrency limitations

- pkg/db/db.go
- services/cd-service/pkg/cmd/server.go
- services/cd-service/pkg/repository/transformer_test.go
- services/manifest-repo-export-service/pkg/cmd/server.go
- services/rollout-service/pkg/cmd/server.go
Kuberpult did not support sqlite already,
this just gets rid of some effectively dead code.
Ref: SRX-LQWK6B
> fix: remove sqlite leftovers

- pkg/testutil/testutil.go
- services/rollout-service/pkg/argo/argo.go
- services/rollout-service/pkg/argo/argo_test.go
- services/rollout-service/pkg/cmd/server.go
The test is now run 100 times, to ensure consistent behavior. 100 tests still run in less than 1 second.
Also added a logging utility to allow logging with FromContext in tests.
Ref: SRX-3LNLJ9
> fix: repair flaky test TestReactToKuberpultEvents

- infrastructure/make/go/include.mk
- infrastructure/scripts/execution-plan/create-matrix.sh
This fixes some details about which service needs to be build,
and tags all `main` images as `pr` image, if they are not build in the current CI job.
Ref: SRX-3FH1FA
> fix(ci): tag as main

- infrastructure/docker/ui/Makefile
- infrastructure/scripts/execution-plan/create-matrix.sh
The "ui" image is only used for local development.
Nowhere in the CI is it referenced.
We do not need to push it necessarily,
but with this change, it will be build it in the CI if something changed.
Ref: SRX-O4HMIP
> fix: build ui in CI

- services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
- services/frontend-service/src/ui/utils/store.tsx
The issue here was that '.response.tagData.filter'
always returned a new object, which react counts as "different enough"
to re-render indefinitely.
"useMemo" fixes that.
Ref: SRX-YABX15
> fix(ui): do not re-render GetProductSummary

- .dockerignore
- services/frontend-service/.dockerignore
The dockerignore file needs to be in the location of the context, which is the root of this repo.
Ref: SRX-Q21BDN
> fix(ci): improve docker ignore file

- pkg/db/db.go
- pkg/db/db_releases.go
- services/cd-service/pkg/repository/transformer.go
- also merge DBSelectReleaseBy{Version,ReleaseNumbers} as they both would suffer from the same issue
- make DBWriteNewReleaseEvent robust against the same null pointer
Ref: SRX-M6Z1XN
> fix: null pointer deref in DBSelectReleaseByVersion
